// <auto-generated/>
#nullable enable

using System.Text.Json;
using Corvus.Json;
using Corvus.Json.Specs.Tests.Infrastructure;
using Drivers;
using Xunit;

namespace JsonSchemaTestSuite.Draft4.MinItems;

[Trait("JsonSchemaTestSuite", "Draft4")]
public class SuiteMinItemsValidation : IClassFixture<SuiteMinItemsValidation.Fixture>
{
    private readonly Fixture _fixture;
    public SuiteMinItemsValidation(Fixture fixture)
    {
        _fixture = fixture;
    }

    [Fact]
    public void TestLongerIsValid()
    {
        using var doc = JsonDocument.Parse("[1, 2]");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(_fixture.GeneratedType, doc.RootElement);
        Assert.True(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    [Fact]
    public void TestExactLengthIsValid()
    {
        using var doc = JsonDocument.Parse("[1]");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(_fixture.GeneratedType, doc.RootElement);
        Assert.True(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    [Fact]
    public void TestTooShortIsInvalid()
    {
        using var doc = JsonDocument.Parse("[]");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(_fixture.GeneratedType, doc.RootElement);
        Assert.False(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    [Fact]
    public void TestIgnoresNonArrays()
    {
        using var doc = JsonDocument.Parse("\"\"");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(_fixture.GeneratedType, doc.RootElement);
        Assert.True(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    public class Fixture : IAsyncLifetime
    {
        private JsonSchemaBuilderDriver? _driver;

        public global::System.Type GeneratedType { get; private set; } = null!;

        public async Task InitializeAsync()
        {
            _driver = DriverFactory.CreateDraft4Driver();
            GeneratedType = await _driver.GenerateTypeForJsonSchemaTestSuite(
                "minItems.json",
                "#/0/schema",
                "JsonSchemaTestSuiteDraft4MinItems",
                "MinItemsValidation",
                validateFormat: false,
                optionalAsNullable: false,
                useImplicitOperatorString: false);
        }

        public Task DisposeAsync()
        {
            _driver?.Dispose();
            return Task.CompletedTask;
        }
    }
}
