const fs = require('fs');
const outPath = process.argv[2];
const L = [];
function w(s) { L.push(s); }

w('// <copyright file="YamlEventParser.cs" company="Endjin Limited">');
w('// Copyright (c) Endjin Limited. All rights reserved.');
w('// </copyright>');
w('');
w('using System.Buffers;');
w('using System.Diagnostics.CodeAnalysis;');
w('using System.Runtime.CompilerServices;');
w('');
w('#if STJ');
w('namespace Corvus.Yaml.Internal;');
w('#else');
w('namespace Corvus.Text.Json.Yaml.Internal;');
w('#endif');
w('');
w('/// <summary>');
w('/// A zero-allocation push-model YAML event parser that fires <see cref="YamlEventCallback"/>');
w('/// delegates for each YAML parse event.');
w('/// </summary>');
w('internal ref struct YamlEventParser');
w('{');
w('    private readonly ReadOnlySpan<byte> _buffer;');
w('    private readonly YamlEventCallback _callback;');
w('    private readonly YamlReaderOptions _options;');
w('    private int _pos;');
w('    private int _line;');
w('    private int _column;');
w('    private int _depth;');
w('    private int _flowMinIndent;');
w('    private bool _secondaryTagRedefined;');
w('    private int _secondaryTagPrefixStart;');
w('    private int _secondaryTagPrefixLength;');
w('    private byte[]? _scratchBuffer;');
w('');
w('    /// <summary>');
w('    /// Initializes a new instance of the <see cref="YamlEventParser"/> struct.');
w('    /// </summary>');
w('    /// <param name="yaml">The UTF-8 YAML buffer to parse.</param>');
w('    /// <param name="callback">The callback to invoke for each event.</param>');
w('    /// <param name="options">The YAML reader options.</param>');
w('    public YamlEventParser(ReadOnlySpan<byte> yaml, YamlEventCallback callback, YamlReaderOptions options)');
w('    {');
w('        _buffer = yaml;');
w('        _callback = callback;');
w('        _options = options;');
w('    }');
w('');
w('    /// <summary>');
w('    /// Parses the YAML buffer and fires events via the callback.');
w('    /// </summary>');
w('    /// <returns><see langword="true"/> if parsing completed; <see langword="false"/> if stopped early.</returns>');
w('    public bool Parse()');
w('    {');
w('        try');
w('        {');
w('            SkipBom();');
w('            return ParseAllDocuments();');
w('        }');
w('        finally');
w('        {');
w('            if (_scratchBuffer != null)');
w('            {');
w('                ArrayPool<byte>.Shared.Return(_scratchBuffer);');
w('            }');
w('        }');
w('    }');