from collections.abc import Callable, Mapping
from typing import Any

RUST_CRATE_VERSION: str

class SchemaCompilationError(Exception): ...
class SchemaEvaluationDepthError(Exception): ...

class SchemaResult:
    @property
    def is_match(self) -> bool: ...
    @property
    def message(self) -> str: ...
    @property
    def evaluation_location(self) -> str: ...
    @property
    def schema_evaluation_location(self) -> str: ...
    @property
    def document_evaluation_location(self) -> str: ...

class JsonSchemaResultsCollector:
    def __init__(self, level: int) -> None: ...
    @staticmethod
    def create(level: int) -> JsonSchemaResultsCollector: ...
    @property
    def level_value(self) -> int: ...
    @property
    def results(self) -> list[SchemaResult]: ...
    @property
    def result_count(self) -> int: ...
    def collect_annotations(self) -> dict[str, dict[str, dict[str, Any]]]: ...

class Validator:
    def __call__(self, instance: Any) -> bool: ...
    def is_valid(self, instance: Any) -> bool: ...
    def is_valid_json(self, text: str | bytes) -> bool: ...
    def evaluate(self, instance: Any, collector: JsonSchemaResultsCollector | None = None) -> bool: ...

def compile(
    schema: Any,
    *,
    default_dialect: int = 4,
    assert_format: bool | None = None,
    assert_format_in_legacy_drafts: bool = False,
    assert_content: bool = True,
    formats: Mapping[str, Callable[[str], bool]] | None = None,
    resolve_document: Callable[[str], Any] | None = None,
    base_uri: str | None = None,
    entry_point: str | None = None,
    max_depth: int = 128,
) -> Validator: ...
def schema_location_fragment(schema_location: str) -> str: ...
