// <copyright file="TestCaseGenerator.cs" company="Endjin Limited">
// Copyright (c) Endjin Limited. All rights reserved.
// </copyright>

using System.Text;
using System.Text.Json;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.Extensions.Configuration;

namespace Corvus.JsonSchema.TestSuite.CodeGenerator;

/// <summary>
/// Generates xUnit test classes for the JSON Schema Test Suite
/// using the V4 runtime Roslyn compilation driver.
/// </summary>
internal static class TestCaseGenerator
{
    private static readonly IConfiguration Config;

    static TestCaseGenerator()
    {
        Config = new ConfigurationBuilder()
            .AddJsonFile("appsettings.json", optional: false, reloadOnChange: false)
            .Build();
    }

    public static void GenerateTests(Action<string> fileCallback)
    {
        StringBuilder builder = new();

        string outputPath = Config["outputPath"] ?? throw new InvalidOperationException("You must provide an <outputPath> in app settings.");
        outputPath = Path.GetFullPath(outputPath);

        // Delete the output directory
        if (Directory.Exists(outputPath))
        {
            Directory.Delete(outputPath, true);
        }

        foreach (TestGroup testGroup in ProvideTestGroups())
        {
            string namespaceGroup = ToPascalCase(testGroup.Name);

            foreach (TestFile testFile in testGroup.Files)
            {
                HashSet<string> suiteNames = [];

                string relativePath = Path.ChangeExtension(testFile.RelativePath, ".cs");
                string outputFile = Path.Combine(outputPath, relativePath);

                string namespaceSuffix = GetNamespaceFromPath(testFile.NamespaceRelativePath);
                string namespaceValue = $"JsonSchemaTestSuite.{namespaceGroup}{(namespaceSuffix.Length > 0 ? "." : string.Empty)}{namespaceSuffix}";

                // The featureName passed to the V4 driver becomes a namespace prefix via
                // "{featureName}Feature.{scenarioName}". Using the dotted namespaceValue
                // creates intermediate namespace segments (e.g. "Uri") that can collide with
                // generated type names. Flatten it to a single identifier to avoid this.
                string flatFeatureName = namespaceValue.Replace(".", string.Empty);
                fileCallback(relativePath);

                // Work on a new test file
                builder.Clear();

                builder
                    .AppendLine("// <auto-generated/>")
                    .AppendLine("#nullable enable")
                    .AppendLine()
                    .AppendLine("using System.Text.Json;")
                    .AppendLine("using Corvus.Json;")
                    .AppendLine("using Corvus.Json.Specs.Tests.Infrastructure;")
                    .AppendLine("using Drivers;")
                    .AppendLine("using Xunit;")
                    .AppendLine()
                    .AppendLine($"namespace {namespaceValue};");

                foreach (TestSuite testSuite in testFile.TestSuites)
                {
                    string pascalSuiteName = GetUniqueName(ToPascalCase(testSuite.SuiteName), suiteNames);
                    builder
                        .AppendLine()
                        .AppendLine($"[Trait(\"JsonSchemaTestSuite\", \"{namespaceGroup}\")]")
                        .AppendLine($"public class Suite{pascalSuiteName} : IClassFixture<Suite{pascalSuiteName}.Fixture>")
                        .AppendLine("{")
                        .AppendLine("    private readonly Fixture _fixture;")
                        .AppendLine($"    public Suite{pascalSuiteName}(Fixture fixture)")
                        .AppendLine("    {")
                        .AppendLine("        _fixture = fixture;")
                        .AppendLine("    }");

                    HashSet<string> testNames = [];

                    foreach (TestSpecification test in testSuite.TestSpecifications)
                    {
                        string testName = GetUniqueName(ToPascalCase(test.TestDescription), testNames);

                        builder
                            .AppendLine()
                            .AppendLine("    [Fact]")
                            .AppendLine($"    public void Test{testName}()")
                            .AppendLine("    {")
                            .AppendLine($"        using var doc = JsonDocument.Parse({SymbolDisplay.FormatLiteral(test.Instance, true)});")
                            .AppendLine($"        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(_fixture.GeneratedType, doc.RootElement.Clone());")
                            .AppendLine($"        Assert.{(test.Expectation ? "True" : "False")}(instance.Validate(ValidationContext.ValidContext).IsValid);")
                            .AppendLine("    }");
                    }

                    builder
                        .AppendLine()
                        .AppendLine("    public class Fixture : IAsyncLifetime")
                        .AppendLine("    {")
                        .AppendLine("        private JsonSchemaBuilderDriver? _driver;")
                        .AppendLine()
                        .AppendLine("        public global::System.Type GeneratedType { get; private set; } = null!;")
                        .AppendLine()
                        .AppendLine("        public async Task InitializeAsync()")
                        .AppendLine("        {")
                        .AppendLine($"            _driver = DriverFactory.{GetFactoryMethodName(testGroup.DriverSettingsKey)}();")
                        .AppendLine($"            GeneratedType = await _driver.GenerateTypeForVirtualFile(")
                        .AppendLine($"                {SymbolDisplay.FormatLiteral(testSuite.Schema, true)},")
                        .AppendLine($"                {SymbolDisplay.FormatLiteral(testFile.NamespaceRelativePath, true)},")
                        .AppendLine($"                {SymbolDisplay.FormatLiteral(flatFeatureName, true)},")
                        .AppendLine($"                {SymbolDisplay.FormatLiteral(pascalSuiteName, true)},")
                        .AppendLine($"                validateFormat: {(testSuite.ValidateFormat ? "true" : "false")},")
                        .AppendLine("                optionalAsNullable: false,")
                        .AppendLine("                useImplicitOperatorString: false);")
                        .AppendLine("        }")
                        .AppendLine()
                        .AppendLine("        public Task DisposeAsync()")
                        .AppendLine("        {")
                        .AppendLine("            _driver?.Dispose();")
                        .AppendLine("            return Task.CompletedTask;")
                        .AppendLine("        }")
                        .AppendLine("    }")
                        .AppendLine("}");
                }

                Directory.CreateDirectory(Path.GetDirectoryName(outputFile)!);
                File.WriteAllText(outputFile, builder.ToString());
            }
        }
    }

    private static string GetFactoryMethodName(string driverSettingsKey) => driverSettingsKey switch
    {
        "jsonSchemaBuilder4DriverSettings" => "CreateDraft4Driver",
        "jsonSchemaBuilder6DriverSettings" => "CreateDraft6Driver",
        "jsonSchemaBuilder7DriverSettings" => "CreateDraft7Driver",
        "jsonSchemaBuilder201909DriverSettings" => "CreateDraft201909Driver",
        "jsonSchemaBuilder202012DriverSettings" => "CreateDraft202012Driver",
        "jsonSchemaBuilderOpenApi30DriverSettings" => "CreateOpenApi30Driver",
        _ => throw new InvalidOperationException($"Unknown driver settings key: {driverSettingsKey}"),
    };

    public static IEnumerable<TestGroup> ProvideTestGroups()
    {
        TestConfiguration jsonSchemaTestSuite = new();
        Config.Bind("jsonSchemaTestSuite", jsonSchemaTestSuite);

        // Always work with the full path
        string baseDirectory = Path.GetFullPath(jsonSchemaTestSuite.BaseDirectory);
        foreach (TestCollection collection in jsonSchemaTestSuite.Collections)
        {
            string currentDirectory = Path.Combine(baseDirectory, collection.Directory);
            List<TestFile> testFiles = [];

            foreach (string file in Directory.EnumerateFiles(currentDirectory, "*.json", SearchOption.AllDirectories))
            {
                List<TestSuite> testSuites = [];

                string relativePath = Path.GetRelativePath(currentDirectory, file);
                string baseRelativePath = Path.GetRelativePath(baseDirectory, file);

                PathOptions? pathOptions = collection.Options?.FirstOrDefault(fe => IsInPath(relativePath, fe.Path));
                FileExclusions? fileExclusions = collection.Exclusions?.FirstOrDefault(fe => EqualsPath(fe.File, relativePath));

                if (fileExclusions is FileExclusions f && f.Suites is null)
                {
                    // Entire file excluded
                    continue;
                }

                string json = File.ReadAllText(file);
                using JsonDocument doc = JsonDocument.Parse(json);

                foreach (JsonElement testSuiteElement in doc.RootElement.EnumerateArray())
                {
                    List<TestSpecification> testList = [];
                    string suiteName = testSuiteElement.GetProperty("description").GetString()!;
                    string schema = testSuiteElement.GetProperty("schema").GetRawText();

                    SuiteExclusions? suiteExclusions = null;
                    if (fileExclusions is FileExclusions fe)
                    {
                        suiteExclusions = fe.Suites?.FirstOrDefault(s => s.Name == suiteName);
                    }

                    // If the entire suite is excluded (no individual tests specified), skip it
                    if (suiteExclusions is SuiteExclusions se2 && se2.Tests is null)
                    {
                        continue;
                    }

                    foreach (JsonElement test in testSuiteElement.GetProperty("tests").EnumerateArray())
                    {
                        string testDescription = test.GetProperty("description").GetString()!;

                        if (suiteExclusions is SuiteExclusions se)
                        {
                            if (se.Tests is List<TestExclusion> te &&
                                te.Any(t => t.Name == testDescription))
                            {
                                continue;
                            }
                        }

                        string data = test.GetProperty("data").GetRawText();
                        bool valid = test.GetProperty("valid").GetBoolean();

                        testList.Add(new TestSpecification(testDescription, data, valid));
                    }

                    if (testList.Count > 0)
                    {
                        testSuites.Add(new TestSuite(suiteName, schema, testList, pathOptions?.ValidateFormat ?? false));
                    }
                }

                if (testSuites.Count > 0)
                {
                    testFiles.Add(new TestFile(jsonSchemaTestSuite.BaseDirectory, baseRelativePath, relativePath, testSuites));
                }
            }

            if (testFiles.Count > 0)
            {
                yield return new(collection.Name, collection.DriverSettingsKey, testFiles);
            }
        }
    }

    internal static string ToPascalCase(string s)
    {
        if (string.IsNullOrEmpty(s))
        {
            return s;
        }

        StringBuilder result = new();
        bool nextUpper = true;

        foreach (char c in s)
        {
            if (c == ' ' || c == '-' || c == '_' || c == '/' || c == '\\' || c == '.')
            {
                nextUpper = true;
            }
            else if (char.IsLetterOrDigit(c))
            {
                result.Append(nextUpper ? char.ToUpperInvariant(c) : c);
                nextUpper = false;
            }
            else
            {
                nextUpper = true;
            }
        }

        // Ensure the result starts with a letter
        if (result.Length > 0 && char.IsDigit(result[0]))
        {
            result.Insert(0, '_');
        }

        return result.ToString();
    }

    private static string GetNamespaceFromPath(string path)
    {
        string namespacePath = Path.GetDirectoryName(path)!;
        string fileNameWithoutExtension = Path.GetFileNameWithoutExtension(path)!;
        string[] segments = namespacePath.Split([Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar], StringSplitOptions.RemoveEmptyEntries);
        string fileNameSegment = ToPascalCase(fileNameWithoutExtension);
        if (segments.Length > 0)
        {
            return $"{string.Join('.', segments.Select(p => ToPascalCase(p)))}.{fileNameSegment}";
        }

        return fileNameSegment;
    }

    private static string GetUniqueName(string v, HashSet<string> names)
    {
        if (names.Add(v))
        {
            return v;
        }

        int index = 1;
        while (true)
        {
            string name = $"{v}{index++}";
            if (names.Add(name))
            {
                return name;
            }
        }
    }

    private static bool IsInPath(string currentPath, string basePath)
    {
        return NormalizePath(currentPath).StartsWith(NormalizePath(basePath));
    }

    private static bool EqualsPath(string currentPath, string basePath)
    {
        return NormalizePath(currentPath).Equals(NormalizePath(basePath));
    }

    private static string NormalizePath(string path)
    {
        return path.Replace('\\', '/').TrimEnd('/');
    }
}

public record TestGroup(string Name, string DriverSettingsKey, List<TestFile> Files);
public record TestFile(string BaseDirectory, string RelativePath, string NamespaceRelativePath, List<TestSuite> TestSuites);
public record TestSuite(string SuiteName, string Schema, List<TestSpecification> TestSpecifications, bool ValidateFormat);
public record TestSpecification(string TestDescription, string Instance, bool Expectation);

public class TestConfiguration
{
    public string BaseDirectory { get; set; }
    public List<TestCollection> Collections { get; set; }
}

public class TestCollection
{
    public string Name { get; set; }
    public string DriverSettingsKey { get; set; }
    public string Directory { get; set; }
    public List<PathOptions>? Options { get; set; }
    public List<FileExclusions>? Exclusions { get; set; }
}

public class PathOptions
{
    public string Path { get; set; }
    public bool? ValidateFormat { get; set; }
}

public class FileExclusions
{
    public string File { get; set; }
    public string? Reason { get; set; }
    public List<SuiteExclusions>? Suites { get; set; }
}

public class SuiteExclusions
{
    public string Name { get; set; }
    public string? Reason { get; set; }
    public List<TestExclusion>? Tests { get; set; }
}

public class TestExclusion
{
    public string Name { get; set; }
    public string? Reason { get; set; }
}