// Derived from code licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licensed this code under the MIT license.

using Corvus.Text.Json.Internal;
using Xunit;

namespace Corvus.Text.Json.Tests;

public partial class JsonRegexValidatorTests
{
    [Theory]
    // Basic
    [InlineData("", JsonRegexOptions.None, true)]
    [InlineData(" ", JsonRegexOptions.IgnorePatternWhitespace, true)]
    [InlineData("  ", JsonRegexOptions.IgnorePatternWhitespace, true)]
    [InlineData("(?#)", JsonRegexOptions.None, true)]
    [InlineData("(?# )", JsonRegexOptions.None, true)]
    [InlineData("(?#", JsonRegexOptions.None, false)]
    [InlineData("(?# ", JsonRegexOptions.None, false)]
    [InlineData("(?# \n )", JsonRegexOptions.None, true)]
    [InlineData("(?# \n )", JsonRegexOptions.IgnorePatternWhitespace, true)]
    [InlineData("(?# #)", JsonRegexOptions.IgnorePatternWhitespace, true)]
    [InlineData("#(?#", JsonRegexOptions.IgnorePatternWhitespace, true)]
    [InlineData("(?#)(?#)", JsonRegexOptions.None, true)]
    [InlineData("(?#)(?#)", JsonRegexOptions.IgnorePatternWhitespace, true)]
    [InlineData("(?#) (?#)", JsonRegexOptions.None, true)]
    [InlineData("(?#) (?#)", JsonRegexOptions.IgnorePatternWhitespace, true)]
    [InlineData(@"[a\p{Lu}(?#)b]", JsonRegexOptions.None, true)]
    [InlineData(@"[a\0(?#)b]", JsonRegexOptions.None, true)]
    [InlineData(@"[a\a(?#)b]", JsonRegexOptions.None, true)]
    [InlineData(@"[a\x00(?#)b]", JsonRegexOptions.None, true)]
    [InlineData(@"[a\u0000(?#)b]", JsonRegexOptions.None, true)]
    [InlineData(@"[a\](?#)b]", JsonRegexOptions.None, true)]
    [InlineData("(?", JsonRegexOptions.None, false)]
    [InlineData("(?", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("(? ", JsonRegexOptions.None, false)]
    [InlineData("(? ", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("(?i)", JsonRegexOptions.None, true)]
    [InlineData("(?im)", JsonRegexOptions.None, true)]
    [InlineData("(?im-x)", JsonRegexOptions.None, true)]
    [InlineData("(?im-x+n)", JsonRegexOptions.None, true)]
    [InlineData("(?i) ", JsonRegexOptions.None, true)]
    [InlineData("(?x) ", JsonRegexOptions.None, true)]
    [InlineData(" (?x) ", JsonRegexOptions.None, true)]
    [InlineData(" (?-x) ", JsonRegexOptions.IgnorePatternWhitespace, true)]
    [InlineData(" ( (?-x) ) ", JsonRegexOptions.IgnorePatternWhitespace, true)]
    [InlineData(" (?-x:) ", JsonRegexOptions.IgnorePatternWhitespace, true)]
    [InlineData(" (?-x: ) ", JsonRegexOptions.IgnorePatternWhitespace, true)]
    [InlineData(" (?-x: (?+x: ) ) ", JsonRegexOptions.IgnorePatternWhitespace, true)]
    [InlineData("(?-x", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("(?-x ", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("(?-x :", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("(?-x )", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("(?-x :)", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData(")", JsonRegexOptions.None, false)]
    [InlineData("a", JsonRegexOptions.None, true)]
    [InlineData("ab", JsonRegexOptions.None, true)]
    [InlineData("a*", JsonRegexOptions.None, true)]
    [InlineData("a*?", JsonRegexOptions.None, true)]
    [InlineData("a+", JsonRegexOptions.None, true)]
    [InlineData("a+?", JsonRegexOptions.None, true)]
    [InlineData("a?", JsonRegexOptions.None, true)]
    [InlineData("a??", JsonRegexOptions.None, true)]
    [InlineData("()", JsonRegexOptions.None, true)]
    [InlineData("(a)", JsonRegexOptions.None, true)]
    [InlineData("(", JsonRegexOptions.None, false)]
    [InlineData("#(", JsonRegexOptions.None, false)]
    [InlineData("#(", JsonRegexOptions.IgnorePatternWhitespace, true)]
    [InlineData("#\n(", JsonRegexOptions.None, false)]
    [InlineData("(a", JsonRegexOptions.None, false)]
    [InlineData("|", JsonRegexOptions.None, true)]
    [InlineData(" |", JsonRegexOptions.None, true)]
    [InlineData("| ", JsonRegexOptions.None, true)]
    [InlineData(" | ", JsonRegexOptions.None, true)]
    [InlineData("|", JsonRegexOptions.IgnorePatternWhitespace, true)]
    [InlineData(" |", JsonRegexOptions.IgnorePatternWhitespace, true)]
    [InlineData("| ", JsonRegexOptions.IgnorePatternWhitespace, true)]
    [InlineData(" | ", JsonRegexOptions.IgnorePatternWhitespace, true)]
    [InlineData("||", JsonRegexOptions.None, true)]
    [InlineData("(|)", JsonRegexOptions.None, true)]
    [InlineData("a{0}", JsonRegexOptions.None, true)]
    [InlineData("a{0,}", JsonRegexOptions.None, true)]
    [InlineData("a{0,1}", JsonRegexOptions.None, true)]
    [InlineData("a{1,0}", JsonRegexOptions.None, false)]
    [InlineData("a{0}?", JsonRegexOptions.None, true)]
    [InlineData("a{0,}?", JsonRegexOptions.None, true)]
    [InlineData("a{0,1}?", JsonRegexOptions.None, true)]
    [InlineData("a{", JsonRegexOptions.None, true)]
    [InlineData("a{0", JsonRegexOptions.None, true)]
    [InlineData("a{0,", JsonRegexOptions.None, true)]
    [InlineData("a{0,1", JsonRegexOptions.None, true)]
    [InlineData("a{0 }", JsonRegexOptions.IgnorePatternWhitespace, true)]
    [InlineData("a{0, }", JsonRegexOptions.IgnorePatternWhitespace, true)]
    [InlineData("a{0 ,}", JsonRegexOptions.IgnorePatternWhitespace, true)]
    [InlineData("a{0 ,1}", JsonRegexOptions.IgnorePatternWhitespace, true)]
    [InlineData("a{0, 1}", JsonRegexOptions.IgnorePatternWhitespace, true)]
    [InlineData("a{0,1 }", JsonRegexOptions.IgnorePatternWhitespace, true)]
    [InlineData("a* ?", JsonRegexOptions.IgnorePatternWhitespace, true)]
    [InlineData("a* ?", JsonRegexOptions.None, true)]
    [InlineData("*", JsonRegexOptions.None, false)]
    [InlineData("(*)", JsonRegexOptions.None, false)]
    [InlineData("a**", JsonRegexOptions.None, false)]
    [InlineData("+", JsonRegexOptions.None, false)]
    [InlineData("(+)", JsonRegexOptions.None, false)]
    [InlineData("a*+", JsonRegexOptions.None, false)]
    [InlineData("?", JsonRegexOptions.None, false)]
    [InlineData("(?)", JsonRegexOptions.None, false)]
    [InlineData("a*??", JsonRegexOptions.None, false)]
    [InlineData("{0}", JsonRegexOptions.None, false)]
    [InlineData("({0})", JsonRegexOptions.None, false)]
    [InlineData("a*{0}", JsonRegexOptions.None, false)]
    [InlineData("{0", JsonRegexOptions.None, true)]
    [InlineData("({0)", JsonRegexOptions.None, true)]
    [InlineData("a*{0", JsonRegexOptions.None, true)]
    [InlineData(@"\w", JsonRegexOptions.None, true)]
    [InlineData(@"\b\B\A\G\Z\z\w\W\s\W\s\S\d\D", JsonRegexOptions.None, true)]
    [InlineData(@"\c", JsonRegexOptions.None, false)]
    [InlineData(@"\c<", JsonRegexOptions.None, false)]
    [InlineData(@"\ca", JsonRegexOptions.None, true)]
    [InlineData(@"\cA", JsonRegexOptions.None, true)]
    [InlineData(@"\c A", JsonRegexOptions.None, false)]
    [InlineData(@"\c(a)", JsonRegexOptions.None, false)]
    [InlineData(@"\c>", JsonRegexOptions.None, false)]
    [InlineData(@"\c?", JsonRegexOptions.None, false)]
    [InlineData(@"\c@", JsonRegexOptions.None, true)]
    [InlineData(@"\c^", JsonRegexOptions.None, true)]
    [InlineData(@"\c_", JsonRegexOptions.None, true)]
    [InlineData(@"\c`", JsonRegexOptions.None, false)]
    [InlineData(@"\c{", JsonRegexOptions.None, false)]
    [InlineData(@"\cz", JsonRegexOptions.None, true)]
    [InlineData(@"\cZ", JsonRegexOptions.None, true)]
    [InlineData(@"\m", JsonRegexOptions.None, false)]
    [InlineData(@"\x", JsonRegexOptions.None, false)]
    [InlineData(@"\x ", JsonRegexOptions.None, false)]
    [InlineData(@"\x0", JsonRegexOptions.None, false)]
    [InlineData(@"\x0 ", JsonRegexOptions.None, false)]
    [InlineData(@"\x00", JsonRegexOptions.None, true)]
    [InlineData(@"\x00 ", JsonRegexOptions.None, true)]
    [InlineData(@"\x000", JsonRegexOptions.None, true)]
    [InlineData(@"\xff", JsonRegexOptions.None, true)]
    [InlineData(@"\xFF", JsonRegexOptions.None, true)]
    [InlineData(@"\xfF", JsonRegexOptions.None, true)]
    [InlineData(@"\xfff", JsonRegexOptions.None, true)]
    [InlineData(@"\xgg", JsonRegexOptions.None, false)]
    [InlineData(@"\m ", JsonRegexOptions.None, false)]
    [InlineData(@"\u", JsonRegexOptions.None, false)]
    [InlineData(@"\u0", JsonRegexOptions.None, false)]
    [InlineData(@"\u00", JsonRegexOptions.None, false)]
    [InlineData(@"\u000", JsonRegexOptions.None, false)]
    [InlineData(@"\u0000", JsonRegexOptions.None, true)]
    [InlineData(@"\u0000 ", JsonRegexOptions.None, true)]
    [InlineData(@"\u ", JsonRegexOptions.None, false)]
    [InlineData(@"\u0 ", JsonRegexOptions.None, false)]
    [InlineData(@"\ugggg", JsonRegexOptions.None, false)]
    [InlineData(@"\0", JsonRegexOptions.None, true)]
    [InlineData(@"\0 ", JsonRegexOptions.None, true)]
    [InlineData(@"\00", JsonRegexOptions.None, true)]
    [InlineData(@"\00 ", JsonRegexOptions.None, true)]
    [InlineData(@"\000", JsonRegexOptions.None, true)]
    [InlineData(@"\000 ", JsonRegexOptions.None, true)]
    [InlineData(@"\0000", JsonRegexOptions.None, true)]
    [InlineData(@"\0000 ", JsonRegexOptions.None, true)]
    [InlineData(@"\7", JsonRegexOptions.None, false)]
    [InlineData(@"\78", JsonRegexOptions.None, true)]
    [InlineData(@"\8", JsonRegexOptions.None, false)]
    [InlineData(@"\40", JsonRegexOptions.ECMAScript, true)]
    [InlineData(@"\401", JsonRegexOptions.ECMAScript, true)]
    [InlineData(@"\37", JsonRegexOptions.ECMAScript, true)]
    [InlineData(@"\371", JsonRegexOptions.ECMAScript, true)]
    [InlineData(@"\0000", JsonRegexOptions.ECMAScript, true)]
    [InlineData(@"\k", JsonRegexOptions.None, false)]
    [InlineData(@"\k ", JsonRegexOptions.None, false)]
    [InlineData(@"\k<", JsonRegexOptions.None, false)]
    [InlineData(@"\k< ", JsonRegexOptions.None, false)]
    [InlineData(@"\k<0", JsonRegexOptions.None, false)]
    [InlineData(@"\k<0 ", JsonRegexOptions.None, false)]
    [InlineData(@"\k<0>", JsonRegexOptions.None, true)]
    [InlineData(@"\k<0> ", JsonRegexOptions.None, true)]
    [InlineData(@"\k<00> ", JsonRegexOptions.None, true)]
    [InlineData(@"\k<a> ", JsonRegexOptions.None, false)]
    [InlineData(@"(?<a>)\k<a> ", JsonRegexOptions.None, true)]
    [InlineData(@"\k", JsonRegexOptions.ECMAScript, false)]
    [InlineData(@"\k ", JsonRegexOptions.ECMAScript, false)]
    [InlineData(@"\k<", JsonRegexOptions.ECMAScript, false)]
    [InlineData(@"\k< ", JsonRegexOptions.ECMAScript, false)]
    [InlineData(@"\k<0", JsonRegexOptions.ECMAScript, false)]
    [InlineData(@"\k<0 ", JsonRegexOptions.ECMAScript, false)]
    [InlineData(@"\k<0>", JsonRegexOptions.ECMAScript, false)]
    [InlineData(@"\k<0> ", JsonRegexOptions.ECMAScript, false)]
    [InlineData(@"\k'", JsonRegexOptions.None, false)]
    [InlineData(@"\k' ", JsonRegexOptions.None, false)]
    [InlineData(@"\k'0", JsonRegexOptions.None, false)]
    [InlineData(@"\k'0 ", JsonRegexOptions.None, false)]
    [InlineData(@"\k'0'", JsonRegexOptions.None, true)]
    [InlineData(@"\k'0' ", JsonRegexOptions.None, true)]
    [InlineData(@"\k'00' ", JsonRegexOptions.None, true)]
    [InlineData(@"\k'a' ", JsonRegexOptions.None, false)]
    [InlineData(@"(?<a>)\k'a' ", JsonRegexOptions.None, true)]
    [InlineData(@"\k<0' ", JsonRegexOptions.None, false)]
    [InlineData(@"\k'0> ", JsonRegexOptions.None, false)]
    [InlineData(@"\", JsonRegexOptions.None, false)]
    [InlineData(@"\ ", JsonRegexOptions.None, true)]
    [InlineData(@"\<", JsonRegexOptions.None, true)]
    [InlineData(@"\< ", JsonRegexOptions.None, true)]
    [InlineData(@"\<0", JsonRegexOptions.None, true)]
    [InlineData(@"\<0 ", JsonRegexOptions.None, true)]
    [InlineData(@"\<0>", JsonRegexOptions.None, true)]
    [InlineData(@"\<0> ", JsonRegexOptions.None, true)]
    [InlineData(@"\<00> ", JsonRegexOptions.None, true)]
    [InlineData(@"\<a> ", JsonRegexOptions.None, false)]
    [InlineData(@"(?<a>)\<a> ", JsonRegexOptions.None, true)]
    [InlineData(@"\", JsonRegexOptions.ECMAScript, false)]
    [InlineData(@"\ ", JsonRegexOptions.ECMAScript, false)]
    [InlineData(@"\<", JsonRegexOptions.ECMAScript, false)]
    [InlineData(@"\< ", JsonRegexOptions.ECMAScript, false)]
    [InlineData(@"\<0", JsonRegexOptions.ECMAScript, false)]
    [InlineData(@"\<0 ", JsonRegexOptions.ECMAScript, false)]
    [InlineData(@"\<0>", JsonRegexOptions.ECMAScript, false)]
    [InlineData(@"\<0> ", JsonRegexOptions.ECMAScript, false)]
    [InlineData(@"\'", JsonRegexOptions.None, true)]
    [InlineData(@"\' ", JsonRegexOptions.None, true)]
    [InlineData(@"\'0", JsonRegexOptions.None, true)]
    [InlineData(@"\'0 ", JsonRegexOptions.None, true)]
    [InlineData(@"\'0'", JsonRegexOptions.None, true)]
    [InlineData(@"\'0' ", JsonRegexOptions.None, true)]
    [InlineData(@"\'00' ", JsonRegexOptions.None, true)]
    [InlineData(@"\'a' ", JsonRegexOptions.None, false)]
    [InlineData(@"(?<a>)\'a' ", JsonRegexOptions.None, true)]
    [InlineData(@"\<0' ", JsonRegexOptions.None, true)]
    [InlineData(@"\'0> ", JsonRegexOptions.None, true)]
    [InlineData("\\p{Cc}", JsonRegexOptions.None, true)]
    [InlineData("\\p{ Cc }", JsonRegexOptions.None, false)]
    [InlineData("\\p{ Cc }", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("\\p {Cc}", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("\\p{xxx}", JsonRegexOptions.None, false)]
    [InlineData("\\p", JsonRegexOptions.None, false)]
    [InlineData("\\p{", JsonRegexOptions.None, false)]
    [InlineData("\\p{}", JsonRegexOptions.None, false)]
    [InlineData("\\p{} ", JsonRegexOptions.None, false)]
    [InlineData("\\p {} ", JsonRegexOptions.None, false)]
    [InlineData("\\p{Cc ", JsonRegexOptions.None, false)]
    [InlineData("\\p{IsArabicPresentationForms-A}", JsonRegexOptions.None, true)]
    [InlineData("(?:)", JsonRegexOptions.None, true)]
    [InlineData("(?:a)", JsonRegexOptions.None, true)]
    [InlineData("(?:", JsonRegexOptions.None, false)]
    [InlineData("(?: ", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("(?=)", JsonRegexOptions.None, true)]
    [InlineData("(?=a)", JsonRegexOptions.None, true)]
    [InlineData("(?=", JsonRegexOptions.None, false)]
    [InlineData("(?= ", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("(?!)", JsonRegexOptions.None, true)]
    [InlineData("(?!a)", JsonRegexOptions.None, true)]
    [InlineData("(?!", JsonRegexOptions.None, false)]
    [InlineData("(?! ", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("(?>)", JsonRegexOptions.None, true)]
    [InlineData("(?>a)", JsonRegexOptions.None, true)]
    [InlineData("(?>", JsonRegexOptions.None, false)]
    [InlineData("(?> ", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("(?<=)", JsonRegexOptions.None, true)]
    [InlineData("(?<=a)", JsonRegexOptions.None, true)]
    [InlineData("(?<=", JsonRegexOptions.None, false)]
    [InlineData("(?<= ", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("(?<!)", JsonRegexOptions.None, true)]
    [InlineData("(?<!a)", JsonRegexOptions.None, true)]
    [InlineData("(?<!", JsonRegexOptions.None, false)]
    [InlineData("(?<! ", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("(?<", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("(?<>", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("(?<a", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("(?<a>", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("(?<a>a", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("(?<a>a)", JsonRegexOptions.IgnorePatternWhitespace, true)]
    [InlineData("(?<a >a)", JsonRegexOptions.None, false)]
    [InlineData("(?<a >a)", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("(?< a>a)", JsonRegexOptions.None, false)]
    [InlineData("(?< a>a)", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("(?< a >a)", JsonRegexOptions.None, false)]
    [InlineData("(?< a >a)", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("(?<ab>a)", JsonRegexOptions.IgnorePatternWhitespace, true)]
    [InlineData("(?<0>a)", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("(?<1>a)", JsonRegexOptions.IgnorePatternWhitespace, true)]
    [InlineData("(?<10>a)", JsonRegexOptions.IgnorePatternWhitespace, true)]
    [InlineData("(?<1>)", JsonRegexOptions.None, true)]
    [InlineData("(?<1> )", JsonRegexOptions.None, true)]
    [InlineData("(?<1> )", JsonRegexOptions.IgnorePatternWhitespace, true)]
    [InlineData("(?'a')", JsonRegexOptions.IgnorePatternWhitespace, true)]
    [InlineData("(?(", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("(?(0", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("(?(0)", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("(?(0))", JsonRegexOptions.IgnorePatternWhitespace, true)]
    [InlineData("(?(0)a)", JsonRegexOptions.IgnorePatternWhitespace, true)]
    [InlineData("(?(0)a|)", JsonRegexOptions.IgnorePatternWhitespace, true)]
    [InlineData("(?(0)a|b)", JsonRegexOptions.IgnorePatternWhitespace, true)]
    [InlineData("(?(0)a|b|)", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("(?(0)a|b|c)", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("(?(0 )", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("(?(1))", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("(?(00))", JsonRegexOptions.IgnorePatternWhitespace, true)]
    [InlineData("(?(a))", JsonRegexOptions.IgnorePatternWhitespace, true)]
    [InlineData("(?<a>)(?(a))", JsonRegexOptions.IgnorePatternWhitespace, true)]
    [InlineData("(?<a>)(?(a ))", JsonRegexOptions.IgnorePatternWhitespace, true)]
    [InlineData("(?<a>)(?( a))", JsonRegexOptions.IgnorePatternWhitespace, true)]
    [InlineData("(?(()a()))", JsonRegexOptions.None, true)]
    [InlineData("(?((?<x>)a(?<y>)))", JsonRegexOptions.None, true)]
    [InlineData("(?(?'", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("(?(?'x'))", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("(?(?#", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("(?(?#)", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("(?(?#))", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("(?(?<", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("(?(?<a", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("(?(?<a>", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("(?(?<a>)", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("(?(?<a>))", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("(?(?<=))", JsonRegexOptions.IgnorePatternWhitespace, true)]
    [InlineData("(?(?<!))", JsonRegexOptions.IgnorePatternWhitespace, true)]
    [InlineData(@"\1", JsonRegexOptions.None, false)]
    [InlineData(@"\1 ", JsonRegexOptions.None, false)]
    [InlineData(@"()\1", JsonRegexOptions.None, true)]
    [InlineData(@"()\1 ", JsonRegexOptions.None, true)]
    [InlineData(@"()\10 ", JsonRegexOptions.None, true)]
    [InlineData(@"\1", JsonRegexOptions.ECMAScript, true)]
    [InlineData(@"\1 ", JsonRegexOptions.ECMAScript, true)]
    [InlineData(@"()\1", JsonRegexOptions.ECMAScript, true)]
    [InlineData(@"()\1 ", JsonRegexOptions.ECMAScript, true)]
    [InlineData(@"()\10 ", JsonRegexOptions.ECMAScript, true)]
    [InlineData(@"()()()()()()()()()()\10 ", JsonRegexOptions.ECMAScript, true)]
    [InlineData(@"[", JsonRegexOptions.None, false)]
    [InlineData(@"[ ", JsonRegexOptions.None, false)]
    [InlineData(@"[]", JsonRegexOptions.None, false)]
    [InlineData(@"[] ", JsonRegexOptions.None, false)]
    [InlineData(@"[a]", JsonRegexOptions.None, true)]
    [InlineData(@"[a] ", JsonRegexOptions.None, true)]
    [InlineData(@"[a-", JsonRegexOptions.None, false)]
    [InlineData(@"[a- ", JsonRegexOptions.None, false)]
    [InlineData(@"[a-]", JsonRegexOptions.None, true)]
    [InlineData(@"[a-] ", JsonRegexOptions.None, true)]
    [InlineData(@"[a-b]", JsonRegexOptions.None, true)]
    [InlineData(@"[a-b] ", JsonRegexOptions.None, true)]
    [InlineData(@"[a-[b]] ", JsonRegexOptions.None, true)]
    [InlineData(@"[a-b-[c]] ", JsonRegexOptions.None, true)]
    [InlineData(@"[a-[b]-c] ", JsonRegexOptions.None, false)]
    [InlineData(@"[a-z-[b]12]", JsonRegexOptions.None, false)]
    [InlineData(@"[[a]-b] ", JsonRegexOptions.None, true)]
    [InlineData(@"[[a]-[b]] ", JsonRegexOptions.None, true)]
    [InlineData(@"[\w-a] ", JsonRegexOptions.None, true)]
    [InlineData(@"[a-\w] ", JsonRegexOptions.None, false)]
    [InlineData(@"[\p{llll}-a] ", JsonRegexOptions.None, false)]
    [InlineData(@"[\p{Lu}-a] ", JsonRegexOptions.None, true)]
    [InlineData(@"[a-\p{Lu}] ", JsonRegexOptions.None, false)]
    [InlineData(@"[a-[:Ll:]] ", JsonRegexOptions.None, true)]
    [InlineData(@"[a-[:Ll]] ", JsonRegexOptions.None, true)]
    [InlineData(@"[a-[:", JsonRegexOptions.None, false)]
    [InlineData(@"[a-[:L", JsonRegexOptions.None, false)]
    [InlineData(@"[a-[:L:", JsonRegexOptions.None, false)]
    [InlineData(@"[a-[:L:]", JsonRegexOptions.None, false)]
    [InlineData(@"[\-]", JsonRegexOptions.None, true)]
    [InlineData(@"[a-b-c] ", JsonRegexOptions.None, true)]
    [InlineData(@"[-b-c] ", JsonRegexOptions.None, true)]
    [InlineData(@"[-[b] ", JsonRegexOptions.None, true)]
    [InlineData(@"[-[b]] ", JsonRegexOptions.None, true)]
    [InlineData(@"[--b ", JsonRegexOptions.None, false)]
    [InlineData(@"[--b] ", JsonRegexOptions.None, true)]
    [InlineData(@"[--[b ", JsonRegexOptions.None, false)]
    [InlineData(@"[--[b] ", JsonRegexOptions.None, false)]
    [InlineData(@"[--[b]] ", JsonRegexOptions.None, true)]
    [InlineData(@"[a--[b ", JsonRegexOptions.None, false)]
    [InlineData(@"[,--[a] ", JsonRegexOptions.None, true)]
    [InlineData(@"[,--[a]] ", JsonRegexOptions.None, true)]
    [InlineData(@"[\s-a]", JsonRegexOptions.None, true)]
    [InlineData(@"[\p{Lu}-a]", JsonRegexOptions.None, true)]
    [InlineData(@"[\c<-\c>]", JsonRegexOptions.None, false)]
    [InlineData(@"[\c>-\c<]", JsonRegexOptions.None, false)]
    [InlineData(@"[\c>-a]", JsonRegexOptions.None, false)]
    [InlineData(@"[a-\c>]", JsonRegexOptions.None, false)]
    [InlineData(@"[a--]", JsonRegexOptions.None, false)]
    [InlineData(@"[--a]", JsonRegexOptions.None, true)]
    [InlineData(@"[\--a]", JsonRegexOptions.None, true)]
    [InlineData(@"[\0-\1]", JsonRegexOptions.None, true)]
    [InlineData(@"[\1-\0]", JsonRegexOptions.None, false)]
    [InlineData(@"[\0-\01]", JsonRegexOptions.None, true)]
    [InlineData(@"[\01-\0]", JsonRegexOptions.None, false)]
    [InlineData(@"[[:x:]-a]", JsonRegexOptions.None, true)]
    [InlineData(@"[a-[:x:]]", JsonRegexOptions.None, true)]
    [InlineData(@"[\0-\ca]", JsonRegexOptions.None, true)]
    [InlineData(@"[\ca-\0]", JsonRegexOptions.None, false)]
    [InlineData(@"[\ca-\cA]", JsonRegexOptions.None, true)]
    [InlineData(@"[\cA-\ca]", JsonRegexOptions.None, true)]
    [InlineData(@"[\u0-\u1]", JsonRegexOptions.None, false)]
    [InlineData(@"[\u1-\u0]", JsonRegexOptions.None, false)]
    [InlineData(@"[\u0000-\u0000]", JsonRegexOptions.None, true)]
    [InlineData(@"[\u0000-\u0001]", JsonRegexOptions.None, true)]
    [InlineData(@"[\u0001-\u0000]", JsonRegexOptions.None, false)]
    [InlineData(@"[\u0001-a]", JsonRegexOptions.None, true)]
    [InlineData(@"[a-\u0001]", JsonRegexOptions.None, false)]
    [InlineData(@"[a-a]", JsonRegexOptions.None, true)]
    [InlineData(@"[a-A]", JsonRegexOptions.None, false)]
    [InlineData(@"[A-a]", JsonRegexOptions.None, true)]
    [InlineData(@"[a-a]", JsonRegexOptions.IgnoreCase, true)]
    [InlineData(@"[a-A]", JsonRegexOptions.IgnoreCase, false)]
    [InlineData(@"[A-a]", JsonRegexOptions.IgnoreCase, true)]
    [InlineData(@"[a-\x61]", JsonRegexOptions.None, true)]
    [InlineData(@"[\x61-a]", JsonRegexOptions.None, true)]
    [InlineData(@"[a-\x60]", JsonRegexOptions.None, false)]
    [InlineData(@"[\x62-a]", JsonRegexOptions.None, false)]
    [InlineData(@"[a-\x62]", JsonRegexOptions.None, true)]
    [InlineData(@"[\3-\cc]", JsonRegexOptions.None, true)]
    [InlineData(@"[\cc-\3]", JsonRegexOptions.None, true)]
    [InlineData(@"[\2-\cc]", JsonRegexOptions.None, true)]
    [InlineData(@"[\cc-\2]", JsonRegexOptions.None, false)]
    [InlineData(@"[\4-\cc]", JsonRegexOptions.None, false)]
    [InlineData(@"[\cc-\4]", JsonRegexOptions.None, true)]
    [InlineData(@"[\ca-\cb]", JsonRegexOptions.None, true)]
    [InlineData(@"[\ca-\cB]", JsonRegexOptions.None, true)]
    [InlineData(@"[\cA-\cb]", JsonRegexOptions.None, true)]
    [InlineData(@"[\cA-\cB]", JsonRegexOptions.None, true)]
    [InlineData(@"[\cb-\ca]", JsonRegexOptions.None, false)]
    [InlineData(@"[\cb-\cA]", JsonRegexOptions.None, false)]
    [InlineData(@"[\cB-\ca]", JsonRegexOptions.None, false)]
    [InlineData(@"[\cB-\cA]", JsonRegexOptions.None, false)]
    [InlineData(@"[\--#]", JsonRegexOptions.None, true)]
    [InlineData(@"[b-\-a]", JsonRegexOptions.None, false)]
    [InlineData(@"[b-\-\-a]", JsonRegexOptions.None, false)]
    [InlineData(@"()\2", JsonRegexOptions.None, false)]
    [InlineData(@"()()\2", JsonRegexOptions.None, true)]
    [InlineData(@"()\1", JsonRegexOptions.ExplicitCapture, false)]
    [InlineData(@"()\2", JsonRegexOptions.ExplicitCapture, false)]
    [InlineData(@"()()\2", JsonRegexOptions.ExplicitCapture, false)]
    [InlineData(@"()()(?n)\1\2", JsonRegexOptions.None, true)]
    [InlineData(@"()(?n)()\1\2", JsonRegexOptions.None, false)]
    [InlineData(@"(?n)()()\1\2", JsonRegexOptions.None, false)]
    [InlineData(@"()()(?n)\1\2", JsonRegexOptions.ExplicitCapture, false)]
    [InlineData(@"()(?n)()\1\2", JsonRegexOptions.ExplicitCapture, false)]
    [InlineData(@"(?n)()()\1\2", JsonRegexOptions.ExplicitCapture, false)]
    [InlineData(@"()()(?-n)\1\2", JsonRegexOptions.None, true)]
    [InlineData(@"()(?-n)()\1\2", JsonRegexOptions.None, true)]
    [InlineData(@"(?-n)()()\1\2", JsonRegexOptions.None, true)]
    [InlineData(@"()()(?-n)\1\2", JsonRegexOptions.ExplicitCapture, false)]
    [InlineData(@"()(?-n)()\1\2", JsonRegexOptions.ExplicitCapture, false)]
    [InlineData(@"(?-n)()()\1\2", JsonRegexOptions.ExplicitCapture, true)]
    [InlineData(@"()()(?n:\1\2)", JsonRegexOptions.None, true)]
    [InlineData(@"()()(?n:\1\2)", JsonRegexOptions.ExplicitCapture, false)]
    [InlineData(@"()()(?-n:\1\2)", JsonRegexOptions.None, true)]
    [InlineData(@"()()(?-n:\1\2)", JsonRegexOptions.ExplicitCapture, false)]
    [InlineData(@"(?n:)()()\1\2", JsonRegexOptions.None, true)]
    [InlineData(@"(?n:)()()\1\2", JsonRegexOptions.ExplicitCapture, false)]
    [InlineData(@"(?-n:)()()\1\2", JsonRegexOptions.None, true)]
    [InlineData(@"(?-n:)()()\1\2", JsonRegexOptions.ExplicitCapture, false)]
    [InlineData(@"(?n)(?-n)()()\1\2", JsonRegexOptions.None, true)]
    [InlineData(@"(?n)(?-n)()()\1\2", JsonRegexOptions.ExplicitCapture, true)]
    [InlineData(@"(?-n)(?n)()()\1\2", JsonRegexOptions.None, false)]
    [InlineData(@"(?-n)(?n)()()\1\2", JsonRegexOptions.ExplicitCapture, false)]
    // References
    [InlineData(@"[aeiou]", JsonRegexOptions.None, true)]
    [InlineData(@"(?<duplicateWord>\w+)\s\k<duplicateWord>\W(?<nextWord>\w+)", JsonRegexOptions.None, true)]
    [InlineData(@"((?<One>abc)\d+)?(?<Two>xyz)(.*)", JsonRegexOptions.None, true)]
    [InlineData(@"(\w+)\s(\1)", JsonRegexOptions.None, true)]
    [InlineData(@"\Bqu\w+", JsonRegexOptions.None, true)]
    [InlineData(@"\bare\w*\b", JsonRegexOptions.None, true)]
    [InlineData(@"\G(\w+\s?\w*),?", JsonRegexOptions.None, true)]
    [InlineData(@"\D+(?<digit>\d+)\D+(?<digit>\d+)?", JsonRegexOptions.None, true)]
    [InlineData(@"(\s\d{4}(-(\d{4}&#124;present))?,?)+", JsonRegexOptions.None, true)]
    [InlineData(@"^((\w+(\s?)){2,}),\s(\w+\s\w+),(\s\d{4}(-(\d{4}|present))?,?)+", JsonRegexOptions.None, true)]
    [InlineData(@"^[0-9-[2468]]+$", JsonRegexOptions.None, true)]
    [InlineData(@"[a-z-[0-9]]", JsonRegexOptions.None, true)]
    [InlineData(@"[\p{IsBasicLatin}-[\x00-\x7F]]", JsonRegexOptions.None, true)]
    [InlineData(@"[\u0000-\uFFFF-[\s\p{P}\p{IsGreek}\x85]]", JsonRegexOptions.None, true)]
    [InlineData(@"[a-z-[d-w-[m-o]]]", JsonRegexOptions.None, true)]
    [InlineData(@"((\w+(\s?)){2,}", JsonRegexOptions.None, false)]
    [InlineData(@"[a-z-[djp]]", JsonRegexOptions.None, true)]
    [InlineData(@"(\w)\1+.\b", JsonRegexOptions.None, true)]
    [InlineData(@"\d{4}\b", JsonRegexOptions.None, true)]
    [InlineData(@"\d{1,2},", JsonRegexOptions.None, true)]
    [InlineData(@"(?<!(Saturday|Sunday) )\b\w+ \d{1,2}, \d{4}\b", JsonRegexOptions.None, true)]
    [InlineData(@"(?<=\b20)\d{2}\b", JsonRegexOptions.None, true)]
    [InlineData(@"\b\w+\b(?!\p{P})", JsonRegexOptions.None, true)]
    [InlineData(@"\b(?!un)\w+\b", JsonRegexOptions.None, true)]
    [InlineData(@"\b(?ix: d \w+)\s", JsonRegexOptions.None, true)]
    [InlineData(@"(?:\w+)", JsonRegexOptions.None, true)]
    [InlineData(@"(?:\b(?:\w+)\W*)+", JsonRegexOptions.None, true)]
    [InlineData(@"(?:\b(?:\w+)\W*)+\.", JsonRegexOptions.None, true)]
    [InlineData(@"[^<>]*", JsonRegexOptions.None, true)]
    [InlineData(@"\b\w+(?=\sis\b)", JsonRegexOptions.None, true)]
    [InlineData(@"[a-z-[m]]", JsonRegexOptions.None, true)]
    [InlineData(@"^\D\d{1,5}\D*$", JsonRegexOptions.None, true)]
    [InlineData(@"[^0-9]", JsonRegexOptions.None, true)]
    [InlineData(@"(\p{IsGreek}+(\s)?)+", JsonRegexOptions.None, true)]
    [InlineData(@"\b(\p{IsGreek}+(\s)?)+\p{Pd}\s(\p{IsBasicLatin}+(\s)?)+", JsonRegexOptions.None, true)]
    [InlineData(@"\b.*[.?!;:](\s|\z)", JsonRegexOptions.None, true)]
    [InlineData(@"^.+", JsonRegexOptions.None, true)]
    [InlineData(@"[^o]", JsonRegexOptions.None, true)]
    [InlineData(@"\bth[^o]\w+\b", JsonRegexOptions.None, true)]
    [InlineData(@"(\P{Sc})+", JsonRegexOptions.None, true)]
    [InlineData(@"[^\p{P}\d]", JsonRegexOptions.None, true)]
    [InlineData(@"\b[A-Z]\w*\b", JsonRegexOptions.None, true)]
    [InlineData(@"\S+?", JsonRegexOptions.None, true)]
    [InlineData(@"y\s", JsonRegexOptions.None, true)]
    [InlineData(@"gr[ae]y\s\S+?[\s\p{P}]", JsonRegexOptions.None, true)]
    [InlineData(@"[\s\p{P}]", JsonRegexOptions.None, true)]
    [InlineData(@"[\p{P}\d]", JsonRegexOptions.None, true)]
    [InlineData(@"[^aeiou]", JsonRegexOptions.None, true)]
    [InlineData(@"(\w)\1", JsonRegexOptions.None, true)]
    [InlineData(@"[^\p{Ll}\p{Lu}\p{Lt}\p{Lo}\p{Nd}\p{Pc}\p{Lm}] ", JsonRegexOptions.None, true)]
    [InlineData(@"[^a-zA-Z_0-9]", JsonRegexOptions.None, true)]
    [InlineData(@"\P{Nd}", JsonRegexOptions.None, true)]
    [InlineData(@"(\(?\d{3}\)?[\s-])?", JsonRegexOptions.None, true)]
    [InlineData(@"^(\(?\d{3}\)?[\s-])?\d{3}-\d{4}$", JsonRegexOptions.None, true)]
    [InlineData(@"[0-9]", JsonRegexOptions.None, true)]
    [InlineData(@"\p{Nd}", JsonRegexOptions.None, true)]
    [InlineData(@"\b(\S+)\s?", JsonRegexOptions.None, true)]
    [InlineData(@"[^ \f\n\r\t\v]", JsonRegexOptions.None, true)]
    [InlineData(@"[^\f\n\r\t\v\x85\p{Z}]", JsonRegexOptions.None, true)]
    [InlineData(@"(\s|$)", JsonRegexOptions.None, true)]
    [InlineData(@"\b\w+(e)?s(\s|$)", JsonRegexOptions.None, true)]
    [InlineData(@"[ \f\n\r\t\v]", JsonRegexOptions.None, true)]
    [InlineData(@"(\W){1,2}", JsonRegexOptions.None, true)]
    [InlineData(@"(\w+)", JsonRegexOptions.None, true)]
    [InlineData(@"\b", JsonRegexOptions.None, true)]
    [InlineData(@"\b(\w+)(\W){1,2}", JsonRegexOptions.None, true)]
    [InlineData(@"(?>(\w)\1+).\b", JsonRegexOptions.None, true)]
    [InlineData(@"(\b(\w+)\W+)+", JsonRegexOptions.None, true)]
    [InlineData(@"\p{Sc}*(\s?\d+[.,]?\d*)\p{Sc}*", JsonRegexOptions.None, true)]
    [InlineData(@"p{Sc}*(?<amount>\s?\d+[.,]?\d*)\p{Sc}*", JsonRegexOptions.None, true)]
    [InlineData(@"^(\w+\s?)+$", JsonRegexOptions.None, true)]
    [InlineData(@"(?ix) d \w+ \s", JsonRegexOptions.None, true)]
    [InlineData(@"\bthe\w*\b", JsonRegexOptions.None, true)]
    [InlineData(@"\b(?i:t)he\w*\b", JsonRegexOptions.None, true)]
    [InlineData(@"^(\w+)\s(\d+)$", JsonRegexOptions.None, true)]
    [InlineData(@"^(\w+)\s(\d+)\r*$", JsonRegexOptions.Multiline, true)]
    [InlineData(@"(?m)^(\w+)\s(\d+)\r*$", JsonRegexOptions.Multiline, true)]
    [InlineData(@"(?s)^.+", JsonRegexOptions.None, true)]
    [InlineData(@"\b(\d{2}-)*(?(1)\d{7}|\d{3}-\d{2}-\d{4})\b", JsonRegexOptions.None, true)]
    [InlineData(@"\b\(?((\w+),?\s?)+[\.!?]\)?", JsonRegexOptions.None, true)]
    [InlineData(@"(?n)\b\(?((?>\w+),?\s?)+[\.!?]\)?", JsonRegexOptions.None, true)]
    [InlineData(@"\b\(?(?n:(?>\w+),?\s?)+[\.!?]\)?", JsonRegexOptions.None, true)]
    [InlineData(@"\b\(?((?>\w+),?\s?)+[\.!?]\)?", JsonRegexOptions.IgnorePatternWhitespace, true)]
    [InlineData(@"(?x)\b \(? ( (?>\w+) ,?\s? )+  [\.!?] \)? # Matches an entire sentence.", JsonRegexOptions.None, true)]
    [InlineData(@"\bb\w+\s", JsonRegexOptions.RightToLeft, true)]
    [InlineData(@"(?<=\d{1,2}\s)\w+,?\s\d{4}", JsonRegexOptions.RightToLeft, true)]
    [InlineData(@"\b(\w+\s*)+", JsonRegexOptions.ECMAScript, true)]
    [InlineData(@"((a+)(\1) ?)+", JsonRegexOptions.ECMAScript, true)]
    [InlineData(@"\b(D\w+)\s(d\w+)\b", JsonRegexOptions.None, true)]
    [InlineData(@"\b(D\w+)(?ixn) \s (d\w+) \b", JsonRegexOptions.None, true)]
    [InlineData(@"\b((?# case-sensitive comparison)D\w+)\s((?#case-insensitive comparison)d\w+)\b", JsonRegexOptions.None, true)]
    [InlineData(@"\b\(?((?>\w+),?\s?)+[\.!?]\)?", JsonRegexOptions.None, true)]
    [InlineData(@"\b(?<n2>\d{2}-)*(?(n2)\d{7}|\d{3}-\d{2}-\d{4})\b", JsonRegexOptions.None, true)]
    [InlineData(@"\b(\d{2}-\d{7}|\d{3}-\d{2}-\d{4})\b", JsonRegexOptions.None, true)]
    [InlineData(@"\bgr(a|e)y\b", JsonRegexOptions.None, true)]
    [InlineData(@"\b91*9*\b", JsonRegexOptions.None, true)]
    [InlineData(@"\ban+\w*?\b", JsonRegexOptions.None, true)]
    [InlineData(@"\ban?\b", JsonRegexOptions.None, true)]
    [InlineData(@"\b\d+\,\d{3}\b", JsonRegexOptions.None, true)]
    [InlineData(@"\b\d{2,}\b\D+", JsonRegexOptions.None, true)]
    [InlineData(@"(00\s){2,4}", JsonRegexOptions.None, true)]
    [InlineData(@"\b\w*?oo\w*?\b", JsonRegexOptions.None, true)]
    [InlineData(@"\b\w+?\b", JsonRegexOptions.None, true)]
    [InlineData(@"^\s*(System.)??Console.Write(Line)??\(??", JsonRegexOptions.None, true)]
    [InlineData(@"(System.)??", JsonRegexOptions.None, true)]
    [InlineData(@"\b(\w{3,}?\.){2}?\w{3,}?\b", JsonRegexOptions.None, true)]
    [InlineData(@"\b[A-Z](\w*?\s*?){1,10}[.!?]", JsonRegexOptions.None, true)]
    [InlineData(@"b.*([0-9]{4})\b", JsonRegexOptions.None, true)]
    [InlineData(@"\b.*?([0-9]{4})\b", JsonRegexOptions.None, true)]
    [InlineData(@"(a?)*", JsonRegexOptions.None, true)]
    [InlineData(@"(a\1|(?(1)\1)){0,2}", JsonRegexOptions.None, true)]
    [InlineData(@"(a\1|(?(1)\1)){2}", JsonRegexOptions.None, true)]
    [InlineData(@"(?<char>\w)\k<char>", JsonRegexOptions.None, true)]
    [InlineData(@"(?<2>\w)\k<2>", JsonRegexOptions.None, true)]
    [InlineData(@"(?<1>a)(?<1>\1b)*", JsonRegexOptions.None, true)]
    [InlineData(@"\b(\p{Lu}{2})(\d{2})?(\p{Lu}{2})\b", JsonRegexOptions.None, true)]
    [InlineData(@"\bgr[ae]y\b", JsonRegexOptions.None, true)]
    [InlineData(@"\b((?# case sensitive comparison)D\w+)\s(?ixn)((?#case insensitive comparison)d\w+)\b", JsonRegexOptions.None, true)]
    [InlineData(@"\{\d+(,-*\d+)*(\:\w{1,4}?)*\}(?x) # Looks for a composite format item.", JsonRegexOptions.None, true)]
    [InlineData(@"cat([a-\d]*)dog", JsonRegexOptions.None, false)]
    [InlineData(@"\k<1", JsonRegexOptions.None, false)]
    [InlineData(@"(?')", JsonRegexOptions.None, false)]
    [InlineData(@"(?<)", JsonRegexOptions.None, false)]
    [InlineData(@"(?imn )", JsonRegexOptions.None, false)]
    [InlineData(@"(?imn", JsonRegexOptions.None, false)]
    [InlineData(@"(?'cat'", JsonRegexOptions.None, false)]
    [InlineData(@"(?'", JsonRegexOptions.None, false)]
    [InlineData(@"(?'=)", JsonRegexOptions.None, false)]
    [InlineData(@"(?'!)", JsonRegexOptions.None, false)]
    [InlineData(@"[^", JsonRegexOptions.None, false)]
    [InlineData(@"[cat", JsonRegexOptions.None, false)]
    [InlineData(@"[^cat", JsonRegexOptions.None, false)]
    [InlineData(@"\p{cat", JsonRegexOptions.None, false)]
    [InlineData(@"\k<cat", JsonRegexOptions.None, false)]
    [InlineData(@"\p{cat}", JsonRegexOptions.None, false)]
    [InlineData(@"\P{cat", JsonRegexOptions.None, false)]
    [InlineData(@"\P{cat}", JsonRegexOptions.None, false)]
    [InlineData(@"(?<cat>", JsonRegexOptions.None, false)]
    [InlineData(@"\P{", JsonRegexOptions.None, false)]
    [InlineData(@"\k<>", JsonRegexOptions.None, false)]
    [InlineData(@"(?(", JsonRegexOptions.None, false)]
    [InlineData(@"(?()|", JsonRegexOptions.None, false)]
    [InlineData(@"?(a|b)", JsonRegexOptions.None, false)]
    [InlineData(@"?((a)", JsonRegexOptions.None, false)]
    [InlineData(@"?((a)a", JsonRegexOptions.None, false)]
    [InlineData(@"?((a)a|", JsonRegexOptions.None, false)]
    [InlineData(@"?((a)a|b", JsonRegexOptions.None, false)]
    [InlineData(@"?(a)", JsonRegexOptions.None, false)]
    [InlineData(@"[a", JsonRegexOptions.None, false)]
    [InlineData(@"?(a:b)", JsonRegexOptions.None, false)]
    [InlineData(@"(?(?", JsonRegexOptions.None, false)]
    [InlineData(@"(?(cat", JsonRegexOptions.None, false)]
    [InlineData(@"(?(cat)|", JsonRegexOptions.None, false)]
    [InlineData(@"foo(?<0>bar)", JsonRegexOptions.None, false)]
    [InlineData(@"foo(?'0'bar)", JsonRegexOptions.None, false)]
    [InlineData(@"foo(?<1bar)", JsonRegexOptions.None, false)]
    [InlineData(@"foo(?'1bar)", JsonRegexOptions.None, false)]
    [InlineData(@"\p{klsak", JsonRegexOptions.None, false)]
    [InlineData(@"(?c:cat)", JsonRegexOptions.None, false)]
    [InlineData(@"(??e:cat)", JsonRegexOptions.None, false)]
    [InlineData(@"[a-f-[]]+", JsonRegexOptions.None, false)]
    [InlineData(@"[A-[]+", JsonRegexOptions.None, false)]
    [InlineData(@"(?(?e))", JsonRegexOptions.None, false)]
    [InlineData(@"(?(?a)", JsonRegexOptions.None, false)]
    [InlineData(@"(?r:cat)", JsonRegexOptions.None, false)]
    [InlineData(@"\x2", JsonRegexOptions.None, false)]
    [InlineData(@"(cat) (?#cat)    \s+ (?#followed by 1 or more whitespace", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData(@"cat(?(?afdcat)dog)", JsonRegexOptions.None, false)]
    [InlineData(@"cat(?(?<cat>cat)dog)", JsonRegexOptions.None, false)]
    [InlineData(@"cat(?(?'cat'cat)dog)", JsonRegexOptions.None, false)]
    [InlineData(@"cat(?(?#COMMENT)cat)", JsonRegexOptions.None, false)]
    [InlineData(@"cat(?<>dog)", JsonRegexOptions.None, false)]
    [InlineData(@"cat(?<dog<>)_*>dog)", JsonRegexOptions.None, false)]
    [InlineData(@"cat(?<dog >)_*>dog)", JsonRegexOptions.None, false)]
    [InlineData(@"cat(?<dog!>)_*>dog)", JsonRegexOptions.None, false)]
    [InlineData(@"cat(?<dog)_*>dog)", JsonRegexOptions.None, false)]
    [InlineData(@"cat(?<1dog>dog)", JsonRegexOptions.None, false)]
    [InlineData(@"cat(?<0>dog)", JsonRegexOptions.None, false)]
    [InlineData(@"([5-\D]*)dog", JsonRegexOptions.None, false)]
    [InlineData(@"cat([6-\s]*)dog", JsonRegexOptions.None, false)]
    [InlineData(@"cat([c-\S]*)", JsonRegexOptions.None, false)]
    [InlineData(@"cat([7-\w]*)", JsonRegexOptions.None, false)]
    [InlineData(@"cat([a-\W]*)dog", JsonRegexOptions.None, false)]
    [InlineData(@"([f-\p{Lu}]\w*)\s([\p{Lu}]\w*)", JsonRegexOptions.None, false)]
    [InlineData(@"(cat) (?#cat)    \s+ (?#followed by 1 or more whitespace", JsonRegexOptions.None, false)]
    [InlineData(@"([1-\P{Ll}][\p{Ll}]*)\s([\P{Ll}][\p{Ll}]*)", JsonRegexOptions.None, false)]
    [InlineData(@"[\P]", JsonRegexOptions.None, false)]
    [InlineData(@"([\pcat])", JsonRegexOptions.None, false)]
    [InlineData(@"([\Pcat])", JsonRegexOptions.None, false)]
    [InlineData(@"(\p{", JsonRegexOptions.None, false)]
    [InlineData(@"(\p{Ll", JsonRegexOptions.None, false)]
    [InlineData(@"(cat)([\o]*)(dog)", JsonRegexOptions.None, false)]
    [InlineData(@"[\p]", JsonRegexOptions.None, false)]
    [InlineData(@"(?<cat>cat)\s+(?<dog>dog)\kcat", JsonRegexOptions.None, false)]
    [InlineData(@"(?<cat>cat)\s+(?<dog>dog)\k<cat2>", JsonRegexOptions.None, false)]
    [InlineData(@"(?<cat>cat)\s+(?<dog>dog)\k<8>cat", JsonRegexOptions.None, false)]
    [InlineData(@"^[abcd]{1}?*$", JsonRegexOptions.None, false)]
    [InlineData(@"^[abcd]*+$", JsonRegexOptions.None, false)]
    [InlineData(@"^[abcd]+*$", JsonRegexOptions.None, false)]
    [InlineData(@"^[abcd]?*$", JsonRegexOptions.None, false)]
    [InlineData(@"^[abcd]*?+$", JsonRegexOptions.None, false)]
    [InlineData(@"^[abcd]+?*$", JsonRegexOptions.None, false)]
    [InlineData(@"^[abcd]{1,}?*$", JsonRegexOptions.None, false)]
    [InlineData(@"^[abcd]??*$", JsonRegexOptions.None, false)]
    [InlineData(@"^[abcd]+{0,5}$", JsonRegexOptions.None, false)]
    [InlineData(@"^[abcd]?{0,5}$", JsonRegexOptions.None, false)]
    [InlineData(@"\ua", JsonRegexOptions.None, false)]
    [InlineData(@"^[abcd]*{0,5}$", JsonRegexOptions.None, false)]
    [InlineData(@"^[abcd]{0,16}?*$", JsonRegexOptions.None, false)]
    [InlineData(@"^[abcd]{1,}*$", JsonRegexOptions.None, false)]
    [InlineData(@"(?<cat>cat)\s+(?<dog>dog)\k<8>cat", JsonRegexOptions.ECMAScript, false)]
    [InlineData(@"(?<cat>cat)\s+(?<dog>dog)\k8", JsonRegexOptions.None, false)]
    [InlineData(@"(?<cat>cat)\s+(?<dog>dog)\k8", JsonRegexOptions.ECMAScript, false)]
    [InlineData(@"(cat)(\7)", JsonRegexOptions.None, false)]
    [InlineData(@"(cat)\s+(?<2147483648>dog)", JsonRegexOptions.None, false)]
    [InlineData(@"(cat)\s+(?<21474836481097>dog)", JsonRegexOptions.None, false)]
    [InlineData(@"^[abcd]{1}*$", JsonRegexOptions.None, false)]
    [InlineData(@"(cat)(\c*)(dog)", JsonRegexOptions.None, false)]
    [InlineData(@"(cat)(\c *)(dog)", JsonRegexOptions.None, false)]
    [InlineData(@"(cat)(\c?*)(dog)", JsonRegexOptions.None, false)]
    [InlineData(@"(cat)(\c`*)(dog)", JsonRegexOptions.None, false)]
    [InlineData(@"(cat)(\c\|*)(dog)", JsonRegexOptions.None, false)]
    [InlineData(@"^[abcd]{0,16}*$", JsonRegexOptions.None, false)]
    [InlineData(@"(cat)\c", JsonRegexOptions.None, false)]
    // Deep recursion
    [InlineData(@"((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((" +
"(((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((" +
"(((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((" +
"(((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((" +
"(((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((" +
"(((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((" +
"(((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((" +
"(((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((" +
"(((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((" +
"(((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((" +
"(((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((" +
"(((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((", JsonRegexOptions.None, false)]
    // Scan control
    [InlineData("(cat)(\\c\0*)(dog)", JsonRegexOptions.None, false)]
    [InlineData(@"(cat)(\c\[*)(dog)", JsonRegexOptions.None, false)]
    // Invalid grouping constructs
    [InlineData("(?<", JsonRegexOptions.None, false)]
    [InlineData("(?>-", JsonRegexOptions.None, false)]
    // Testgroup with options
    [InlineData("())", JsonRegexOptions.None, false)]
    [InlineData("[a-z-[aeiuo]", JsonRegexOptions.None, false)]
    [InlineData("[a-z-[aeiuo", JsonRegexOptions.None, false)]
    [InlineData("[a-z-[b]", JsonRegexOptions.None, false)]
    [InlineData("[a-z-[b", JsonRegexOptions.None, false)]
    [InlineData("[b-a]", JsonRegexOptions.None, false)]
    [InlineData(@"[a-c]{2,1}", JsonRegexOptions.None, false)]
    [InlineData(@"\d{2147483648}", JsonRegexOptions.None, false)]
    [InlineData("[a-z-[b][", JsonRegexOptions.None, false)]
    [InlineData("(?()|||||)", JsonRegexOptions.None, false)]
    [InlineData("[^]", JsonRegexOptions.None, false)]
    [InlineData("??", JsonRegexOptions.None, false)]
    [InlineData("(?=*)", JsonRegexOptions.None, false)]
    [InlineData("((((((*))))))", JsonRegexOptions.None, false)]
#if NET
    // Avoid OutOfMemoryException
    [InlineData("a{2147483647}", JsonRegexOptions.None, true)]
    [InlineData("a{2147483647,}", JsonRegexOptions.None, true)]
    [InlineData(@"(?(?N))", JsonRegexOptions.None, false)]
    [InlineData(@"(?(?i))", JsonRegexOptions.None, false)]
    [InlineData(@"(?(?I))", JsonRegexOptions.None, false)]
    [InlineData(@"(?(?M))", JsonRegexOptions.None, false)]
    [InlineData(@"(?(?s))", JsonRegexOptions.None, false)]
    [InlineData(@"(?(?S))", JsonRegexOptions.None, false)]
    [InlineData(@"(?(?x))", JsonRegexOptions.None, false)]
    [InlineData(@"(?(?X))", JsonRegexOptions.None, false)]
    [InlineData(@"(?(?n))", JsonRegexOptions.None, false)]
    [InlineData(@"(?(?m))", JsonRegexOptions.None, false)]
    [InlineData("(?<-", JsonRegexOptions.None, false)]
    [InlineData("(?<-", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData(@"^[^<>]*(((?'Open'<)[^<>]*)+((?'Close-Open'>)[^<>]*)+)*(?(Open)(?!))$", JsonRegexOptions.None, true)]
    [InlineData(@"((?'Close-Open'>)[^<>]*)+", JsonRegexOptions.None, false)]
    [InlineData(@"(((?'Open'<)[^<>]*)+((?'Close-Open'>)[^<>]*)+)*", JsonRegexOptions.None, true)]
    [InlineData(@"(?'Close-Open'>)", JsonRegexOptions.None, false)]
    [InlineData("(?<a-00>)", JsonRegexOptions.IgnorePatternWhitespace, true)]
    [InlineData("(?<a>)()(?<-0>)(?<-1>)(?<-2>)(?<-3>)", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("()(?<a>)(?<-0>)(?<-1>)(?<-2>)(?<-3>)", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("()()(?<-0>)(?<-1>)(?<-2>)(?<-3>)", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("(?<a>)(?<b>)(?<-1>)(?<-2>)", JsonRegexOptions.IgnorePatternWhitespace, true)]
    [InlineData("(?<-4>)(?<4>)", JsonRegexOptions.IgnorePatternWhitespace, true)]
    [InlineData("(?<4>)(?<-4>)", JsonRegexOptions.IgnorePatternWhitespace, true)]
    [InlineData("(?<a>)(?<-a>)", JsonRegexOptions.IgnorePatternWhitespace, true)]
    [InlineData("(?<-a>)(?<a>)", JsonRegexOptions.IgnorePatternWhitespace, true)]
    [InlineData("(?<a-0>", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("(?<a-0>)", JsonRegexOptions.IgnorePatternWhitespace, true)]
    [InlineData("(?<a-0 >)", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("(?<a- 0 >)", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("(?<a- 0>)", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("(?<-1>)", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("()(?<-1>)", JsonRegexOptions.IgnorePatternWhitespace, true)]
    [InlineData("(?<-1>)()", JsonRegexOptions.IgnorePatternWhitespace, true)]
    [InlineData("(?<-00>)", JsonRegexOptions.IgnorePatternWhitespace, true)]
    [InlineData("(?<a-", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("(?<a-0", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("(?<a-0)", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("(?<a>)(?<b>)(?<-0>)(?<-1>)(?<-2>)(?<-3>)", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("(?<-0>)(?<-1>)(?<-2>)(?<-3>)()()", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("(?<-0>)(?<-1>)(?<-2>)(?<-3>)()(?", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("(?<-0>)(?<-1>)(?<-2>)(?<-3>)()(?<a>)", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("(?<-0>)(?<-1>)(?<-2>)(?<-3>)(?<a>)()", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("(?<-0>)(?<-1>)(?<-2>)(?<-3>)(?<a>)(?", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("(?<-0>)(?<-1>)(?<-2>)(?<-3>)(?<a>)(?<b>)", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("(?<a-0>)(?<b-a>)", JsonRegexOptions.IgnorePatternWhitespace, true)]
    [InlineData("(?<a-0>)(?<-a>)", JsonRegexOptions.IgnorePatternWhitespace, true)]
    [InlineData("(?<a-a>)", JsonRegexOptions.IgnorePatternWhitespace, true)]
    [InlineData("(?<-0>)", JsonRegexOptions.IgnorePatternWhitespace, true)]
    [InlineData("(?<-0 >)", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("(?<- 0 >)", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("(?<- 0>)", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("(?<a-0')", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("(?'a-0>)", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("(?'-0')", JsonRegexOptions.IgnorePatternWhitespace, true)]
    [InlineData("(?'a-0')", JsonRegexOptions.IgnorePatternWhitespace, true)]
    [InlineData("(?<-0", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("(?<-0)", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData("(?<-0>", JsonRegexOptions.IgnorePatternWhitespace, false)]
    [InlineData(@"(?<cat>cat)\w+(?<dog-()*!@>dog)", JsonRegexOptions.None, false)]
    [InlineData(@"(?<cat>cat)\w+(?<dog-catdog>dog)", JsonRegexOptions.None, false)]
    [InlineData(@"(?<cat>cat)\w+(?<dog-1uosn>dog)", JsonRegexOptions.None, false)]
    [InlineData(@"(?<cat>cat)\w+(?<dog-16>dog)", JsonRegexOptions.None, false)]
    [InlineData(@"cat(?<->dog)", JsonRegexOptions.None, false)]
    [InlineData("a{2147483648}", JsonRegexOptions.None, false)]
    [InlineData("a{2147483648,}", JsonRegexOptions.None, false)]
    [InlineData("a{0,2147483647}", JsonRegexOptions.None, true)]
    [InlineData("a{0,2147483648}", JsonRegexOptions.None, false)]
    // Surrogate pair which is parsed as [char,char-char,char] as we operate on UTF-16 code units.
    [InlineData("[\uD82F\uDCA0-\uD82F\uDCA3]", JsonRegexOptions.IgnoreCase, false)]
    // [ inside a range is treated literally
    [InlineData(@"[[::]", JsonRegexOptions.None, true)]
    [InlineData(@"[[:X:]", JsonRegexOptions.None, true)]
    [InlineData(@"[[:ab:]", JsonRegexOptions.None, true)]

    // Following are borrowed from Rust regex tests ============
    // https://github.com/rust-lang/regex/blob/master/tests/noparse.rs
    //[InlineData(@"*", JsonRegexOptions.None, false)]  Already covered
    [InlineData(@"[A-", JsonRegexOptions.None, false)]
    [InlineData(@"[A", JsonRegexOptions.None, false)]
    [InlineData(@"[\A]", JsonRegexOptions.None, false)]
    [InlineData(@"[\z]", JsonRegexOptions.None, false)]
    //[InlineData(@"(", JsonRegexOptions.None, false)]  Already covered
    //[InlineData(@")", JsonRegexOptions.None, false)]  Already covered
    [InlineData(@"[a-Z]", JsonRegexOptions.None, false)]
    [InlineData(@"(?P<>a)", JsonRegexOptions.None, false)]
    [InlineData(@"(?P<na-me>)", JsonRegexOptions.None, false)]
    [InlineData(@"(?a)a", JsonRegexOptions.None, false)]
    [InlineData(@"a{2,1}", JsonRegexOptions.None, false)]
    //[InlineData(@"(?", JsonRegexOptions.None, false)]  Already covered
    //[InlineData(@"\8", JsonRegexOptions.None, false)]  Already covered
    [InlineData(@"\xG0", JsonRegexOptions.None, false)]
    [InlineData(@"\xF", JsonRegexOptions.None, false)]
    [InlineData(@"\x{fffg}", JsonRegexOptions.None, false)]
    [InlineData(@"(?a)", JsonRegexOptions.None, false)]
    //[InlineData(@"(?)", JsonRegexOptions.None, false)]  Already covered
    [InlineData(@"(?P<a>.)(?P<a>.)", JsonRegexOptions.None, false)]
    [InlineData(@"[a-\A]", JsonRegexOptions.None, false)]
    [InlineData(@"[a-\z]", JsonRegexOptions.None, false)]
    [InlineData(@"[a-\b]", JsonRegexOptions.None, false)] // Nim: not an error
    [InlineData(@"[a-\-]", JsonRegexOptions.None, false)]
    [InlineData(@"[a-\-b]", JsonRegexOptions.None, false)]
    [InlineData(@"[a-\-\-b]", JsonRegexOptions.None, false)]
    [InlineData(@"[a-\-\D]", JsonRegexOptions.None, false)]
    [InlineData(@"[a-\-\-\D]", JsonRegexOptions.None, false)]
    [InlineData(@"[a -\-\b]", JsonRegexOptions.None, true)]
    [InlineData(@"[\b]", JsonRegexOptions.None, true)] // errors in rust: class_no_boundary
    [InlineData(@"a{10000000}", JsonRegexOptions.None, true)] // errors in rust: too_big
    [InlineData(@"a{1001", JsonRegexOptions.None, true)] // errors in rust: counted_no_close
    [InlineData(@"a{-1,1}", JsonRegexOptions.None, true)] // errors in rust: counted_nonnegative
    [InlineData(@"\\", JsonRegexOptions.None, true)] // errors in rust: unfinished_escape
    [InlineData(@"(?-i-i)", JsonRegexOptions.None, true)] // errors in rust: double_neg
    [InlineData(@"(?i-)", JsonRegexOptions.None, true)] // errors in rust: neg_empty
    [InlineData(@"[a-[:lower:]]", JsonRegexOptions.None, true)] // errors in rust: range_end_no_class
    // End of Rust parser tests ==============

    // Following are borrowed from Nim tests
    // https://github.com/nitely/nim-regex/blob/eeefb4f51264ff3bc3b36caf55672a74f52f5ef5/tests/tests.nim
    //[InlineData(@"?", JsonRegexOptions.None, false)]  Already covered
    [InlineData(@"?|?", JsonRegexOptions.None, false)]
    [InlineData(@"?abc", JsonRegexOptions.None, false)]
    [InlineData(@"(?P<abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_>abc", JsonRegexOptions.None, false)] // Nim: not an error
    [InlineData(@"(?Pabc", JsonRegexOptions.None, false)]
    [InlineData(@"(?u-q)", JsonRegexOptions.None, false)]
    [InlineData(@"(?uq)", JsonRegexOptions.None, false)]
    [InlineData(@"(\b)", JsonRegexOptions.None, true)]
    //[InlineData(@"(+)", JsonRegexOptions.None, false)]  Already covered
    [InlineData(@"(a)b)", JsonRegexOptions.None, false)]
    [InlineData(@"(b(a)", JsonRegexOptions.None, false)]
    [InlineData(@"[-", JsonRegexOptions.None, false)]
    [InlineData(@"[-a", JsonRegexOptions.None, false)]
    [InlineData(@"[[:abc:]]", JsonRegexOptions.None, true)] // Nim: "Invalid ascii set. `abc` is not a valid name"
    [InlineData(@"[[:alnum:", JsonRegexOptions.None, false)]
    [InlineData(@"[[:alnum]]", JsonRegexOptions.None, true)] // Nim: "Invalid ascii set. Expected [:name:]"
    //[InlineData(@"[]", JsonRegexOptions.None, false)]  Already covered
    [InlineData(@"[]a", JsonRegexOptions.None, false)]
    [InlineData(@"[]abc", JsonRegexOptions.None, false)]
    [InlineData(@"[\\", JsonRegexOptions.None, false)]
    //[InlineData(@"[^]", JsonRegexOptions.None, false)]  Already covered
    //[InlineData(@"[a-", JsonRegexOptions.None, false)]  Already covered
    [InlineData(@"[a-\w]", JsonRegexOptions.None, false)]
    //[InlineData(@"[a", JsonRegexOptions.None, false)]  Already covered
    [InlineData(@"[abc", JsonRegexOptions.None, false)]
    [InlineData(@"[d-c]", JsonRegexOptions.None, false)]
    [InlineData(@"[z-[:alnum:]]", JsonRegexOptions.None, true)] // Nim: "Invalid set range. Start must be lesser than end"
    [InlineData(@"{10}", JsonRegexOptions.None, false)]
    [InlineData(@"*abc", JsonRegexOptions.None, false)]
    [InlineData(@"\12", JsonRegexOptions.None, true)] // Nim: "Invalid octal literal. Expected 3 octal digits, but found 2"
    [InlineData(@"\12@", JsonRegexOptions.None, true)] // Nim: "Invalid octal literal. Expected octal digit, but found @"
    [InlineData(@"\b?", JsonRegexOptions.None, true)]
    [InlineData(@"\b*", JsonRegexOptions.None, true)]
    [InlineData(@"\b+", JsonRegexOptions.None, true)]
    [InlineData(@"\p{11", JsonRegexOptions.None, false)]
    [InlineData(@"\p{11}", JsonRegexOptions.None, false)]
    [InlineData(@"\p{Bb}", JsonRegexOptions.None, false)]
    [InlineData(@"\p11", JsonRegexOptions.None, false)]
    [InlineData(@"\pB", JsonRegexOptions.None, false)]
    [InlineData(@"\u123", JsonRegexOptions.None, false)]
    [InlineData(@"\U123", JsonRegexOptions.None, false)]
    [InlineData(@"\U123@a", JsonRegexOptions.None, false)]
    [InlineData(@"\u123@abc", JsonRegexOptions.None, false)]
    [InlineData(@"\UFFFFFFFF", JsonRegexOptions.None, false)]
    [InlineData(@"\x{00000000A}", JsonRegexOptions.None, false)]
    [InlineData(@"\x{2f894", JsonRegexOptions.None, false)]
    [InlineData(@"\x{61@}", JsonRegexOptions.None, false)]
    [InlineData(@"\x{7fffffff}", JsonRegexOptions.None, false)] // Nim: not an error (supports Unicode beyond basic multilingual plane)
    [InlineData(@"\x{FFFFFFFF}", JsonRegexOptions.None, false)]
    //[InlineData(@"+", JsonRegexOptions.None, false)]  Already covered
    [InlineData(@"+abc", JsonRegexOptions.None, false)]
    [InlineData(@"a???", JsonRegexOptions.None, false)]
    [InlineData(@"a??*", JsonRegexOptions.None, false)]
    [InlineData(@"a??+", JsonRegexOptions.None, false)]
    [InlineData(@"a?*", JsonRegexOptions.None, false)]
    [InlineData(@"a?+", JsonRegexOptions.None, false)]
    [InlineData(@"a(?P<>abc)", JsonRegexOptions.None, false)]
    [InlineData(@"a(?P<asd)", JsonRegexOptions.None, false)]
    [InlineData(@"a{,}", JsonRegexOptions.None, true)] // Nim error
    [InlineData(@"a{,1}", JsonRegexOptions.None, true)] // Nim error
    [InlineData(@"a{0,101}", JsonRegexOptions.None, true)] // Nim error: "Invalid repetition range. Expected 100 repetitions or less, but found: 101"
    [InlineData(@"a{0,a}", JsonRegexOptions.None, true)] // Nim error
    [InlineData(@"a{0,bad}", JsonRegexOptions.None, true)] // Nim error: "Invalid repetition range. Range can only contain digits"
    [InlineData(@"a{1,,,2}", JsonRegexOptions.None, true)] // Nim error
    [InlineData(@"a{1,,}", JsonRegexOptions.None, true)] // Nim error
    [InlineData(@"a{1,,2}", JsonRegexOptions.None, true)] // Nim error
    [InlineData(@"a{1,", JsonRegexOptions.None, true)] // Nim error
    [InlineData(@"a{1,}??", JsonRegexOptions.None, false)]
    [InlineData(@"a{1,}?", JsonRegexOptions.None, true)]
    [InlineData(@"a{1,}*", JsonRegexOptions.None, false)]
    [InlineData(@"a{1,}+", JsonRegexOptions.None, false)]
    [InlineData(@"a{1,101}", JsonRegexOptions.None, true)]
    [InlineData(@"a{1,x}", JsonRegexOptions.None, true)] // Nim error
    [InlineData(@"a{1", JsonRegexOptions.None, true)] // Nim error
    [InlineData(@"a{1}??", JsonRegexOptions.None, false)]
    [InlineData(@"a{1}?", JsonRegexOptions.None, true)]
    [InlineData(@"a{1}*", JsonRegexOptions.None, false)]
    [InlineData(@"a{1}+", JsonRegexOptions.None, false)]
    [InlineData(@"a{1111111111}", JsonRegexOptions.None, true)] // Nim error: "Invalid repetition range. Max value is 32767."
    [InlineData(@"a{1x}", JsonRegexOptions.None, true)] // Nim error
    //[InlineData(@"a*??", JsonRegexOptions.None, false)]  Already covered
    [InlineData(@"a*{,}", JsonRegexOptions.None, true)] // Nim error
    //[InlineData(@"a*{0}", JsonRegexOptions.None, false)]   Already covered
    [InlineData(@"a*{1}", JsonRegexOptions.None, false)]
    //[InlineData(@"a**", JsonRegexOptions.None, false)]  Already covered
    [InlineData(@"a*****", JsonRegexOptions.None, false)]
    //[InlineData(@"a*+", JsonRegexOptions.None, false)]  Already covered
    [InlineData(@"a+??", JsonRegexOptions.None, false)]
    [InlineData(@"a+*", JsonRegexOptions.None, false)]
    [InlineData(@"a++", JsonRegexOptions.None, false)]
    [InlineData(@"a|?", JsonRegexOptions.None, false)]
    [InlineData(@"a|?b", JsonRegexOptions.None, false)]
    [InlineData(@"a|*", JsonRegexOptions.None, false)]
    [InlineData(@"a|*b", JsonRegexOptions.None, false)]
    [InlineData(@"a|+", JsonRegexOptions.None, false)]
    [InlineData(@"a|+b", JsonRegexOptions.None, false)]
    [InlineData(@"aaa(?Pabc", JsonRegexOptions.None, false)]
    [InlineData(@"abc(?P<abc", JsonRegexOptions.None, false)]
    [InlineData(@"abc(?Pabc)", JsonRegexOptions.None, false)]
    [InlineData(@"abc(?q)", JsonRegexOptions.None, false)]
    [InlineData(@"abc[]", JsonRegexOptions.None, false)]
    [InlineData(@"abc\A{10}", JsonRegexOptions.None, true)] // Nim error:  "Invalid repetition range, either char, shorthand (i.e: \\w), group, or set expected before repetition range"
    [InlineData(@"\uD87E\uDC94(?Pabc", JsonRegexOptions.None, false)]
    [InlineData(@"\uD87E\uDC94aaa(?Pabc", JsonRegexOptions.None, false)]
    [InlineData(@"\uD87E\uDC94\uD87E\uDC94\uD87E\uDC94(?Pabc", JsonRegexOptions.None, false)]
#endif
    public void Validate_Validates(string pattern, JsonRegexOptions options, bool expected)
    {
        bool actual = JsonRegexValidator.Validate(pattern, options);

        if (expected != actual)
        {
            actual = JsonRegexValidator.Validate(pattern, options);
        }

        Assert.Equal(expected, actual);
    }
}