// <auto-generated/>
#nullable enable

using System.Text.Json;
using Corvus.Json;
using Corvus.Json.Specs.Tests.Infrastructure;
using Drivers;
using Xunit;

namespace JsonSchemaTestSuite.AdditionalDraft202012.Repro481;

[Trait("JsonSchemaTestSuite", "AdditionalDraft202012")]
public class SuiteMixedCaseEmail : IClassFixture<SuiteMixedCaseEmail.Fixture>
{
    private readonly Fixture _fixture;
    public SuiteMixedCaseEmail(Fixture fixture)
    {
        _fixture = fixture;
    }

    [Fact]
    public void TestDataEndjinCorvusNet()
    {
        using var doc = JsonDocument.Parse("\"Endjin@corvus.net\"");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(_fixture.GeneratedType, doc.RootElement.Clone());
        Assert.True(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    public class Fixture : IAsyncLifetime
    {
        private JsonSchemaBuilderDriver? _driver;

        public global::System.Type GeneratedType { get; private set; } = null!;

        public async Task InitializeAsync()
        {
            _driver = DriverFactory.CreateAdditionalDraft202012Driver();
            GeneratedType = await _driver.GenerateTypeForJsonSchemaTestSuite(
                "Repro481.json",
                "#/0/schema",
                "JsonSchemaTestSuiteAdditionalDraft202012Repro481",
                "MixedCaseEmail",
                validateFormat: true,
                optionalAsNullable: false,
                useImplicitOperatorString: false);
        }

        public Task DisposeAsync()
        {
            _driver?.Dispose();
            return Task.CompletedTask;
        }
    }
}
