// <auto-generated/>
#nullable enable

using System.Text.Json;
using Corvus.Json;
using Corvus.Json.Specs.Tests.Infrastructure;
using Drivers;
using Xunit;

namespace JsonSchemaTestSuite.Draft201909.Optional.Format.IdnEmail;

[Trait("JsonSchemaTestSuite", "Draft201909")]
public class SuiteValidationOfAnInternationalizedEMailAddresses : IClassFixture<SuiteValidationOfAnInternationalizedEMailAddresses.Fixture>
{
    private readonly Fixture _fixture;
    public SuiteValidationOfAnInternationalizedEMailAddresses(Fixture fixture)
    {
        _fixture = fixture;
    }

    [Fact]
    public void TestAllStringFormatsIgnoreIntegers()
    {
        using var doc = JsonDocument.Parse("12");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(_fixture.GeneratedType, doc.RootElement.Clone());
        Assert.True(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    [Fact]
    public void TestAllStringFormatsIgnoreFloats()
    {
        using var doc = JsonDocument.Parse("13.7");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(_fixture.GeneratedType, doc.RootElement.Clone());
        Assert.True(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    [Fact]
    public void TestAllStringFormatsIgnoreObjects()
    {
        using var doc = JsonDocument.Parse("{}");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(_fixture.GeneratedType, doc.RootElement.Clone());
        Assert.True(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    [Fact]
    public void TestAllStringFormatsIgnoreArrays()
    {
        using var doc = JsonDocument.Parse("[]");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(_fixture.GeneratedType, doc.RootElement.Clone());
        Assert.True(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    [Fact]
    public void TestAllStringFormatsIgnoreBooleans()
    {
        using var doc = JsonDocument.Parse("false");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(_fixture.GeneratedType, doc.RootElement.Clone());
        Assert.True(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    [Fact]
    public void TestAllStringFormatsIgnoreNulls()
    {
        using var doc = JsonDocument.Parse("null");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(_fixture.GeneratedType, doc.RootElement.Clone());
        Assert.True(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    [Fact]
    public void TestAValidIdnEMailExampleExampleTestInHangul()
    {
        using var doc = JsonDocument.Parse("\"실례@실례.테스트\"");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(_fixture.GeneratedType, doc.RootElement.Clone());
        Assert.True(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    [Fact]
    public void TestAnInvalidEMailIdnEMailAddress()
    {
        using var doc = JsonDocument.Parse("\"2962\"");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(_fixture.GeneratedType, doc.RootElement.Clone());
        Assert.False(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    [Fact]
    public void TestAValidEMailAddress()
    {
        using var doc = JsonDocument.Parse("\"joe.bloggs@example.com\"");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(_fixture.GeneratedType, doc.RootElement.Clone());
        Assert.True(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    public class Fixture : IAsyncLifetime
    {
        private JsonSchemaBuilderDriver? _driver;

        public global::System.Type GeneratedType { get; private set; } = null!;

        public async Task InitializeAsync()
        {
            _driver = DriverFactory.CreateDraft201909Driver();
            GeneratedType = await _driver.GenerateTypeForVirtualFile(
                "{\r\n            \"$schema\": \"https://json-schema.org/draft/2019-09/schema\",\r\n            \"format\": \"idn-email\"\r\n        }",
                "optional\\format\\idn-email.json",
                "JsonSchemaTestSuiteDraft201909OptionalFormatIdnEmail",
                "ValidationOfAnInternationalizedEMailAddresses",
                validateFormat: true,
                optionalAsNullable: false,
                useImplicitOperatorString: false);
        }

        public Task DisposeAsync()
        {
            _driver?.Dispose();
            return Task.CompletedTask;
        }
    }
}
