// <auto-generated/>
#nullable enable

using System.Text.Json;
using Corvus.Json;
using Corvus.Json.Specs.Tests.Infrastructure;
using Drivers;
using Xunit;

namespace JsonSchemaTestSuite.Draft202012.Optional.Format.RelativeJsonPointer;

[Trait("JsonSchemaTestSuite", "Draft202012")]
public class SuiteValidationOfRelativeJSONPointersRJP : IClassFixture<SuiteValidationOfRelativeJSONPointersRJP.Fixture>
{
    private readonly Fixture _fixture;
    public SuiteValidationOfRelativeJSONPointersRJP(Fixture fixture)
    {
        _fixture = fixture;
    }

    [Fact]
    public void TestAllStringFormatsIgnoreIntegers()
    {
        using var doc = JsonDocument.Parse("12");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(_fixture.GeneratedType, doc.RootElement.Clone());
        Assert.True(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    [Fact]
    public void TestAllStringFormatsIgnoreFloats()
    {
        using var doc = JsonDocument.Parse("13.7");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(_fixture.GeneratedType, doc.RootElement.Clone());
        Assert.True(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    [Fact]
    public void TestAllStringFormatsIgnoreObjects()
    {
        using var doc = JsonDocument.Parse("{}");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(_fixture.GeneratedType, doc.RootElement.Clone());
        Assert.True(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    [Fact]
    public void TestAllStringFormatsIgnoreArrays()
    {
        using var doc = JsonDocument.Parse("[]");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(_fixture.GeneratedType, doc.RootElement.Clone());
        Assert.True(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    [Fact]
    public void TestAllStringFormatsIgnoreBooleans()
    {
        using var doc = JsonDocument.Parse("false");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(_fixture.GeneratedType, doc.RootElement.Clone());
        Assert.True(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    [Fact]
    public void TestAllStringFormatsIgnoreNulls()
    {
        using var doc = JsonDocument.Parse("null");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(_fixture.GeneratedType, doc.RootElement.Clone());
        Assert.True(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    [Fact]
    public void TestAValidUpwardsRJP()
    {
        using var doc = JsonDocument.Parse("\"1\"");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(_fixture.GeneratedType, doc.RootElement.Clone());
        Assert.True(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    [Fact]
    public void TestAValidDownwardsRJP()
    {
        using var doc = JsonDocument.Parse("\"0/foo/bar\"");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(_fixture.GeneratedType, doc.RootElement.Clone());
        Assert.True(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    [Fact]
    public void TestAValidUpAndThenDownRJPWithArrayIndex()
    {
        using var doc = JsonDocument.Parse("\"2/0/baz/1/zip\"");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(_fixture.GeneratedType, doc.RootElement.Clone());
        Assert.True(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    [Fact]
    public void TestAValidRJPTakingTheMemberOrIndexName()
    {
        using var doc = JsonDocument.Parse("\"0#\"");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(_fixture.GeneratedType, doc.RootElement.Clone());
        Assert.True(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    [Fact]
    public void TestAnInvalidRJPThatIsAValidJSONPointer()
    {
        using var doc = JsonDocument.Parse("\"/foo/bar\"");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(_fixture.GeneratedType, doc.RootElement.Clone());
        Assert.False(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    [Fact]
    public void TestNegativePrefix()
    {
        using var doc = JsonDocument.Parse("\"-1/foo/bar\"");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(_fixture.GeneratedType, doc.RootElement.Clone());
        Assert.False(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    [Fact]
    public void TestExplicitPositivePrefix()
    {
        using var doc = JsonDocument.Parse("\"+1/foo/bar\"");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(_fixture.GeneratedType, doc.RootElement.Clone());
        Assert.False(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    [Fact]
    public void TestIsNotAValidJsonPointer()
    {
        using var doc = JsonDocument.Parse("\"0##\"");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(_fixture.GeneratedType, doc.RootElement.Clone());
        Assert.False(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    [Fact]
    public void TestZeroCannotBeFollowedByOtherDigitsPlusJsonPointer()
    {
        using var doc = JsonDocument.Parse("\"01/a\"");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(_fixture.GeneratedType, doc.RootElement.Clone());
        Assert.False(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    [Fact]
    public void TestZeroCannotBeFollowedByOtherDigitsPlusOctothorpe()
    {
        using var doc = JsonDocument.Parse("\"01#\"");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(_fixture.GeneratedType, doc.RootElement.Clone());
        Assert.False(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    [Fact]
    public void TestEmptyString()
    {
        using var doc = JsonDocument.Parse("\"\"");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(_fixture.GeneratedType, doc.RootElement.Clone());
        Assert.False(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    [Fact]
    public void TestMultiDigitIntegerPrefix()
    {
        using var doc = JsonDocument.Parse("\"120/foo/bar\"");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(_fixture.GeneratedType, doc.RootElement.Clone());
        Assert.True(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    public class Fixture : IAsyncLifetime
    {
        private JsonSchemaBuilderDriver? _driver;

        public global::System.Type GeneratedType { get; private set; } = null!;

        public async Task InitializeAsync()
        {
            _driver = DriverFactory.CreateDraft202012Driver();
            GeneratedType = await _driver.GenerateTypeForJsonSchemaTestSuite(
                "optional\\format\\relative-json-pointer.json",
                "#/0/schema",
                "JsonSchemaTestSuiteDraft202012OptionalFormatRelativeJsonPointer",
                "ValidationOfRelativeJSONPointersRJP",
                validateFormat: true,
                optionalAsNullable: false,
                useImplicitOperatorString: false);
        }

        public Task DisposeAsync()
        {
            _driver?.Dispose();
            return Task.CompletedTask;
        }
    }
}
