<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <NoWarn>$(NoWarn);CS1591;SA1615;CA1822</NoWarn>
    <LangVersion>Preview</LangVersion>
    <PreserveCompilationContext>true</PreserveCompilationContext>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Corvus.Text.Json\Corvus.Text.Json.csproj" />
    <ProjectReference Include="..\..\src\Corvus.Text.Json.Validator\Corvus.Text.Json.Validator.csproj" />
    <ProjectReference Include="..\Corvus.Text.Json.ClassicBenchmarkModels\Corvus.Text.Json.ClassicBenchmarkModels.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\Corvus.Text.Json.ClassicBenchmarkModels\person-array-schema.json" Link="person-array-schema.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>