// <auto-generated/>
#nullable enable

using System.Text.Json;
using Corvus.Json;
using Corvus.Json.Specs.Tests.Infrastructure;
using Drivers;
using Xunit;

namespace JsonSchemaTestSuite.Draft201909.Content;

[Trait("JsonSchemaTestSuite", "Draft201909")]
public class SuiteValidationOfStringEncodedContentBasedOnMediaType : IClassFixture<SuiteValidationOfStringEncodedContentBasedOnMediaType.Fixture>
{
    private readonly Fixture _fixture;
    public SuiteValidationOfStringEncodedContentBasedOnMediaType(Fixture fixture)
    {
        _fixture = fixture;
    }

    [Fact]
    public void TestAValidJSONDocument()
    {
        using var doc = JsonDocument.Parse("\"{\\\"foo\\\": \\\"bar\\\"}\"");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(_fixture.GeneratedType, doc.RootElement.Clone());
        Assert.True(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    [Fact]
    public void TestAnInvalidJSONDocumentValidatesTrue()
    {
        using var doc = JsonDocument.Parse("\"{:}\"");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(_fixture.GeneratedType, doc.RootElement.Clone());
        Assert.True(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    [Fact]
    public void TestIgnoresNonStrings()
    {
        using var doc = JsonDocument.Parse("100");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(_fixture.GeneratedType, doc.RootElement.Clone());
        Assert.True(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    public class Fixture : IAsyncLifetime
    {
        private JsonSchemaBuilderDriver? _driver;

        public global::System.Type GeneratedType { get; private set; } = null!;

        public async Task InitializeAsync()
        {
            _driver = DriverFactory.CreateDraft201909Driver();
            GeneratedType = await _driver.GenerateTypeForJsonSchemaTestSuite(
                "content.json",
                "#/0/schema",
                "JsonSchemaTestSuiteDraft201909Content",
                "ValidationOfStringEncodedContentBasedOnMediaType",
                validateFormat: false,
                optionalAsNullable: false,
                useImplicitOperatorString: false);
        }

        public Task DisposeAsync()
        {
            _driver?.Dispose();
            return Task.CompletedTask;
        }
    }
}

[Trait("JsonSchemaTestSuite", "Draft201909")]
public class SuiteValidationOfBinaryStringEncoding : IClassFixture<SuiteValidationOfBinaryStringEncoding.Fixture>
{
    private readonly Fixture _fixture;
    public SuiteValidationOfBinaryStringEncoding(Fixture fixture)
    {
        _fixture = fixture;
    }

    [Fact]
    public void TestAValidBase64String()
    {
        using var doc = JsonDocument.Parse("\"eyJmb28iOiAiYmFyIn0K\"");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(_fixture.GeneratedType, doc.RootElement.Clone());
        Assert.True(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    [Fact]
    public void TestAnInvalidBase64StringIsNotAValidCharacterValidatesTrue()
    {
        using var doc = JsonDocument.Parse("\"eyJmb28iOi%iYmFyIn0K\"");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(_fixture.GeneratedType, doc.RootElement.Clone());
        Assert.True(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    [Fact]
    public void TestIgnoresNonStrings()
    {
        using var doc = JsonDocument.Parse("100");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(_fixture.GeneratedType, doc.RootElement.Clone());
        Assert.True(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    public class Fixture : IAsyncLifetime
    {
        private JsonSchemaBuilderDriver? _driver;

        public global::System.Type GeneratedType { get; private set; } = null!;

        public async Task InitializeAsync()
        {
            _driver = DriverFactory.CreateDraft201909Driver();
            GeneratedType = await _driver.GenerateTypeForJsonSchemaTestSuite(
                "content.json",
                "#/1/schema",
                "JsonSchemaTestSuiteDraft201909Content",
                "ValidationOfBinaryStringEncoding",
                validateFormat: false,
                optionalAsNullable: false,
                useImplicitOperatorString: false);
        }

        public Task DisposeAsync()
        {
            _driver?.Dispose();
            return Task.CompletedTask;
        }
    }
}

[Trait("JsonSchemaTestSuite", "Draft201909")]
public class SuiteValidationOfBinaryEncodedMediaTypeDocuments : IClassFixture<SuiteValidationOfBinaryEncodedMediaTypeDocuments.Fixture>
{
    private readonly Fixture _fixture;
    public SuiteValidationOfBinaryEncodedMediaTypeDocuments(Fixture fixture)
    {
        _fixture = fixture;
    }

    [Fact]
    public void TestAValidBase64EncodedJSONDocument()
    {
        using var doc = JsonDocument.Parse("\"eyJmb28iOiAiYmFyIn0K\"");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(_fixture.GeneratedType, doc.RootElement.Clone());
        Assert.True(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    [Fact]
    public void TestAValidlyEncodedInvalidJSONDocumentValidatesTrue()
    {
        using var doc = JsonDocument.Parse("\"ezp9Cg==\"");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(_fixture.GeneratedType, doc.RootElement.Clone());
        Assert.True(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    [Fact]
    public void TestAnInvalidBase64StringThatIsValidJSONValidatesTrue()
    {
        using var doc = JsonDocument.Parse("\"{}\"");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(_fixture.GeneratedType, doc.RootElement.Clone());
        Assert.True(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    [Fact]
    public void TestIgnoresNonStrings()
    {
        using var doc = JsonDocument.Parse("100");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(_fixture.GeneratedType, doc.RootElement.Clone());
        Assert.True(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    public class Fixture : IAsyncLifetime
    {
        private JsonSchemaBuilderDriver? _driver;

        public global::System.Type GeneratedType { get; private set; } = null!;

        public async Task InitializeAsync()
        {
            _driver = DriverFactory.CreateDraft201909Driver();
            GeneratedType = await _driver.GenerateTypeForJsonSchemaTestSuite(
                "content.json",
                "#/2/schema",
                "JsonSchemaTestSuiteDraft201909Content",
                "ValidationOfBinaryEncodedMediaTypeDocuments",
                validateFormat: false,
                optionalAsNullable: false,
                useImplicitOperatorString: false);
        }

        public Task DisposeAsync()
        {
            _driver?.Dispose();
            return Task.CompletedTask;
        }
    }
}

[Trait("JsonSchemaTestSuite", "Draft201909")]
public class SuiteValidationOfBinaryEncodedMediaTypeDocumentsWithSchema : IClassFixture<SuiteValidationOfBinaryEncodedMediaTypeDocumentsWithSchema.Fixture>
{
    private readonly Fixture _fixture;
    public SuiteValidationOfBinaryEncodedMediaTypeDocumentsWithSchema(Fixture fixture)
    {
        _fixture = fixture;
    }

    [Fact]
    public void TestAValidBase64EncodedJSONDocument()
    {
        using var doc = JsonDocument.Parse("\"eyJmb28iOiAiYmFyIn0K\"");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(_fixture.GeneratedType, doc.RootElement.Clone());
        Assert.True(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    [Fact]
    public void TestAnotherValidBase64EncodedJSONDocument()
    {
        using var doc = JsonDocument.Parse("\"eyJib28iOiAyMCwgImZvbyI6ICJiYXoifQ==\"");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(_fixture.GeneratedType, doc.RootElement.Clone());
        Assert.True(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    [Fact]
    public void TestAnInvalidBase64EncodedJSONDocumentValidatesTrue()
    {
        using var doc = JsonDocument.Parse("\"eyJib28iOiAyMH0=\"");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(_fixture.GeneratedType, doc.RootElement.Clone());
        Assert.True(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    [Fact]
    public void TestAnEmptyObjectAsABase64EncodedJSONDocumentValidatesTrue()
    {
        using var doc = JsonDocument.Parse("\"e30=\"");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(_fixture.GeneratedType, doc.RootElement.Clone());
        Assert.True(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    [Fact]
    public void TestAnEmptyArrayAsABase64EncodedJSONDocument()
    {
        using var doc = JsonDocument.Parse("\"W10=\"");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(_fixture.GeneratedType, doc.RootElement.Clone());
        Assert.True(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    [Fact]
    public void TestAValidlyEncodedInvalidJSONDocumentValidatesTrue()
    {
        using var doc = JsonDocument.Parse("\"ezp9Cg==\"");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(_fixture.GeneratedType, doc.RootElement.Clone());
        Assert.True(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    [Fact]
    public void TestAnInvalidBase64StringThatIsValidJSONValidatesTrue()
    {
        using var doc = JsonDocument.Parse("\"{}\"");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(_fixture.GeneratedType, doc.RootElement.Clone());
        Assert.True(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    [Fact]
    public void TestIgnoresNonStrings()
    {
        using var doc = JsonDocument.Parse("100");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(_fixture.GeneratedType, doc.RootElement.Clone());
        Assert.True(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    public class Fixture : IAsyncLifetime
    {
        private JsonSchemaBuilderDriver? _driver;

        public global::System.Type GeneratedType { get; private set; } = null!;

        public async Task InitializeAsync()
        {
            _driver = DriverFactory.CreateDraft201909Driver();
            GeneratedType = await _driver.GenerateTypeForJsonSchemaTestSuite(
                "content.json",
                "#/3/schema",
                "JsonSchemaTestSuiteDraft201909Content",
                "ValidationOfBinaryEncodedMediaTypeDocumentsWithSchema",
                validateFormat: false,
                optionalAsNullable: false,
                useImplicitOperatorString: false);
        }

        public Task DisposeAsync()
        {
            _driver?.Dispose();
            return Task.CompletedTask;
        }
    }
}
