// <auto-generated/>
#nullable enable

using System.Text.Json;
using Corvus.Json;
using Corvus.Json.Specs.Tests.Infrastructure;
using Drivers;
using Xunit;

namespace JsonSchemaTestSuite.Draft202012.Anchor;

[Trait("JsonSchemaTestSuite", "Draft202012")]
public class SuiteLocationIndependentIdentifier : IClassFixture<SuiteLocationIndependentIdentifier.Fixture>
{
    private readonly Fixture _fixture;
    public SuiteLocationIndependentIdentifier(Fixture fixture)
    {
        _fixture = fixture;
    }

    [Fact]
    public void TestMatch()
    {
        using var doc = JsonDocument.Parse("1");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(_fixture.GeneratedType, doc.RootElement.Clone());
        Assert.True(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    [Fact]
    public void TestMismatch()
    {
        using var doc = JsonDocument.Parse("\"a\"");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(_fixture.GeneratedType, doc.RootElement.Clone());
        Assert.False(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    public class Fixture : IAsyncLifetime
    {
        private JsonSchemaBuilderDriver? _driver;

        public global::System.Type GeneratedType { get; private set; } = null!;

        public async Task InitializeAsync()
        {
            _driver = DriverFactory.CreateDraft202012Driver();
            GeneratedType = await _driver.GenerateTypeForJsonSchemaTestSuite(
                "anchor.json",
                "#/0/schema",
                "JsonSchemaTestSuiteDraft202012Anchor",
                "LocationIndependentIdentifier",
                validateFormat: false,
                optionalAsNullable: false,
                useImplicitOperatorString: false);
        }

        public Task DisposeAsync()
        {
            _driver?.Dispose();
            return Task.CompletedTask;
        }
    }
}

[Trait("JsonSchemaTestSuite", "Draft202012")]
public class SuiteLocationIndependentIdentifierWithAbsoluteURI : IClassFixture<SuiteLocationIndependentIdentifierWithAbsoluteURI.Fixture>
{
    private readonly Fixture _fixture;
    public SuiteLocationIndependentIdentifierWithAbsoluteURI(Fixture fixture)
    {
        _fixture = fixture;
    }

    [Fact]
    public void TestMatch()
    {
        using var doc = JsonDocument.Parse("1");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(_fixture.GeneratedType, doc.RootElement.Clone());
        Assert.True(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    [Fact]
    public void TestMismatch()
    {
        using var doc = JsonDocument.Parse("\"a\"");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(_fixture.GeneratedType, doc.RootElement.Clone());
        Assert.False(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    public class Fixture : IAsyncLifetime
    {
        private JsonSchemaBuilderDriver? _driver;

        public global::System.Type GeneratedType { get; private set; } = null!;

        public async Task InitializeAsync()
        {
            _driver = DriverFactory.CreateDraft202012Driver();
            GeneratedType = await _driver.GenerateTypeForJsonSchemaTestSuite(
                "anchor.json",
                "#/1/schema",
                "JsonSchemaTestSuiteDraft202012Anchor",
                "LocationIndependentIdentifierWithAbsoluteURI",
                validateFormat: false,
                optionalAsNullable: false,
                useImplicitOperatorString: false);
        }

        public Task DisposeAsync()
        {
            _driver?.Dispose();
            return Task.CompletedTask;
        }
    }
}

[Trait("JsonSchemaTestSuite", "Draft202012")]
public class SuiteLocationIndependentIdentifierWithBaseURIChangeInSubschema : IClassFixture<SuiteLocationIndependentIdentifierWithBaseURIChangeInSubschema.Fixture>
{
    private readonly Fixture _fixture;
    public SuiteLocationIndependentIdentifierWithBaseURIChangeInSubschema(Fixture fixture)
    {
        _fixture = fixture;
    }

    [Fact]
    public void TestMatch()
    {
        using var doc = JsonDocument.Parse("1");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(_fixture.GeneratedType, doc.RootElement.Clone());
        Assert.True(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    [Fact]
    public void TestMismatch()
    {
        using var doc = JsonDocument.Parse("\"a\"");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(_fixture.GeneratedType, doc.RootElement.Clone());
        Assert.False(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    public class Fixture : IAsyncLifetime
    {
        private JsonSchemaBuilderDriver? _driver;

        public global::System.Type GeneratedType { get; private set; } = null!;

        public async Task InitializeAsync()
        {
            _driver = DriverFactory.CreateDraft202012Driver();
            GeneratedType = await _driver.GenerateTypeForJsonSchemaTestSuite(
                "anchor.json",
                "#/2/schema",
                "JsonSchemaTestSuiteDraft202012Anchor",
                "LocationIndependentIdentifierWithBaseURIChangeInSubschema",
                validateFormat: false,
                optionalAsNullable: false,
                useImplicitOperatorString: false);
        }

        public Task DisposeAsync()
        {
            _driver?.Dispose();
            return Task.CompletedTask;
        }
    }
}

[Trait("JsonSchemaTestSuite", "Draft202012")]
public class SuiteSameAnchorWithDifferentBaseUri : IClassFixture<SuiteSameAnchorWithDifferentBaseUri.Fixture>
{
    private readonly Fixture _fixture;
    public SuiteSameAnchorWithDifferentBaseUri(Fixture fixture)
    {
        _fixture = fixture;
    }

    [Fact]
    public void TestRefResolvesToDefsAAllOf1()
    {
        using var doc = JsonDocument.Parse("\"a\"");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(_fixture.GeneratedType, doc.RootElement.Clone());
        Assert.True(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    [Fact]
    public void TestRefDoesNotResolveToDefsAAllOf0()
    {
        using var doc = JsonDocument.Parse("1");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(_fixture.GeneratedType, doc.RootElement.Clone());
        Assert.False(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    public class Fixture : IAsyncLifetime
    {
        private JsonSchemaBuilderDriver? _driver;

        public global::System.Type GeneratedType { get; private set; } = null!;

        public async Task InitializeAsync()
        {
            _driver = DriverFactory.CreateDraft202012Driver();
            GeneratedType = await _driver.GenerateTypeForJsonSchemaTestSuite(
                "anchor.json",
                "#/3/schema",
                "JsonSchemaTestSuiteDraft202012Anchor",
                "SameAnchorWithDifferentBaseUri",
                validateFormat: false,
                optionalAsNullable: false,
                useImplicitOperatorString: false);
        }

        public Task DisposeAsync()
        {
            _driver?.Dispose();
            return Task.CompletedTask;
        }
    }
}
