// <copyright file="JsonPathCodeGenerator.cs" company="Endjin Limited">
// Copyright (c) Endjin Limited. All rights reserved.
// </copyright>

using System.Collections.Immutable;
using System.Text;
using Corvus.Text.Json.JsonPath;

namespace Corvus.Text.Json.JsonPath.CodeGeneration;

/// <summary>
/// Generates static C# evaluation code from a JSONPath (RFC 9535) expression string.
/// </summary>
/// <remarks>
/// <para>
/// The generator walks the JSONPath AST and emits inline C# code that calls
/// <c>JsonPathCodeGenHelpers</c> methods. The generated code uses
/// <see cref="System.Buffers.ArrayPool{T}"/> for intermediate node-list management
/// and supports all selector, filter, and function constructs defined by RFC 9535.
/// </para>
/// </remarks>
public static class JsonPathCodeGenerator
{
    private const string H = "JsonPathCodeGenHelpers";

    /// <summary>
    /// Generates a complete C# source file containing a static class with an
    /// <c>Evaluate</c> method that evaluates the given JSONPath expression.
    /// </summary>
    /// <param name="expression">The JSONPath expression string.</param>
    /// <param name="className">The name of the generated static class.</param>
    /// <param name="namespaceName">The namespace for the generated class.</param>
    /// <param name="accessibility">The accessibility modifier (e.g. <c>"internal"</c> or <c>"public"</c>).</param>
    /// <param name="isPartial">Whether to emit the <c>partial</c> modifier on the class.</param>
    /// <returns>A complete C# source file as a string.</returns>
    /// <exception cref="JsonPathException">
    /// Thrown if <paramref name="expression"/> is not a valid JSONPath expression.
    /// </exception>
    public static string Generate(
        string expression,
        string className,
        string namespaceName,
        string accessibility = "internal",
        bool isPartial = false)
    {
        byte[] utf8 = Encoding.UTF8.GetBytes(expression);
        QueryNode ast = Parser.Parse(utf8);

        Emitter emitter = new();
        StringBuilder nodesBody = new(4096);

        emitter.EmitQueryNodes(nodesBody, ast, "        ");

        StringBuilder sb = new(8192);
        L(sb, "", "// <auto-generated/>");
        L(sb, "", "#nullable enable");
        L(sb, "", "using System;");
        L(sb, "", "using System.Buffers;");

        if (emitter.RegexFields.Count > 0)
        {
            L(sb, "", "using System.Text.RegularExpressions;");
        }

        L(sb, "", "using Corvus.Text.Json;");
        L(sb, "", "using Corvus.Text.Json.JsonPath;");
        Blank(sb);
        L(sb, "", $"namespace {namespaceName};");
        Blank(sb);

        string partialKeyword = isPartial ? " partial" : string.Empty;
        L(sb, "", $"{accessibility} static{partialKeyword} class {className}");
        L(sb, "", "{");

        // Emit static literal fields
        if (emitter.StaticFields.Count > 0)
        {
            L(sb, "", "#pragma warning disable SA1306");
            L(sb, "", "#pragma warning disable SA1311");
            foreach ((string _, string declaration) in emitter.StaticFields)
            {
                L(sb, "    ", declaration);
            }

            L(sb, "", "#pragma warning restore SA1311");
            L(sb, "", "#pragma warning restore SA1306");
            Blank(sb);
        }

        // Emit static name fields
        foreach ((string _, string declaration) in emitter.NameFields)
        {
            L(sb, "    ", declaration);
        }

        if (emitter.NameFields.Count > 0)
        {
            Blank(sb);
        }

        // Emit static regex fields
        if (emitter.RegexFields.Count > 0)
        {
            foreach ((string _, string declaration) in emitter.RegexFields)
            {
                L(sb, "    ", declaration);
            }

            Blank(sb);
        }

        // Emit EvaluateNodes method (zero-alloc core)
        L(sb, "    ", "/// <summary>");
        L(sb, "    ", "/// Evaluates the JSONPath expression and appends matched nodes to <paramref name=\"result\"/>.");
        L(sb, "    ", "/// </summary>");
        L(sb, "    ", "/// <param name=\"data\">The root JSON element.</param>");
        L(sb, "    ", "/// <param name=\"result\">The result buffer to populate.</param>");
        L(sb, "    ", "public static void EvaluateNodes(in JsonElement data, ref JsonPathResult result)");
        L(sb, "    ", "{");
        sb.Append(nodesBody);
        L(sb, "    ", "}");
        Blank(sb);

        // Emit QueryNodes convenience (pooled)
        L(sb, "    ", "/// <summary>");
        L(sb, "    ", "/// Evaluates the JSONPath expression and returns matched nodes.");
        L(sb, "    ", "/// </summary>");
        L(sb, "    ", "/// <param name=\"data\">The root JSON element.</param>");
        L(sb, "    ", "/// <returns>A <see cref=\"JsonPathResult\"/> that must be disposed.</returns>");
        L(sb, "    ", "public static JsonPathResult QueryNodes(in JsonElement data)");
        L(sb, "    ", "{");
        L(sb, "    ", "    JsonPathResult result = JsonPathResult.CreatePooled(16);");
        L(sb, "    ", "    try");
        L(sb, "    ", "    {");
        L(sb, "    ", "        EvaluateNodes(data, ref result);");
        L(sb, "    ", "        return result;");
        L(sb, "    ", "    }");
        L(sb, "    ", "    catch");
        L(sb, "    ", "    {");
        L(sb, "    ", "        result.Dispose();");
        L(sb, "    ", "        throw;");
        L(sb, "    ", "    }");
        L(sb, "    ", "}");
        Blank(sb);

        // Emit Evaluate convenience (materializes to JsonElement array)
        L(sb, "    ", "/// <summary>");
        L(sb, "    ", "/// Evaluates the JSONPath expression and returns a JSON array of matched nodes.");
        L(sb, "    ", "/// </summary>");
        L(sb, "    ", "/// <param name=\"data\">The root JSON element.</param>");
        L(sb, "    ", "/// <param name=\"workspace\">The workspace for document allocation.</param>");
        L(sb, "    ", "/// <returns>A JSON array element containing the matched nodes.</returns>");
        L(sb, "    ", "public static JsonElement Evaluate(in JsonElement data, JsonWorkspace workspace)");
        L(sb, "    ", "{");
        L(sb, "    ", "    JsonPathResult result = JsonPathResult.CreatePooled(16);");
        L(sb, "    ", "    try");
        L(sb, "    ", "    {");
        L(sb, "    ", "        EvaluateNodes(data, ref result);");
        L(sb, "    ", "        return JsonPathCodeGenHelpers.BuildArrayFromSpan(result.Nodes, workspace);");
        L(sb, "    ", "    }");
        L(sb, "    ", "    finally");
        L(sb, "    ", "    {");
        L(sb, "    ", "        result.Dispose();");
        L(sb, "    ", "    }");
        L(sb, "    ", "}");

        // Emit helper methods
        foreach (string helperMethod in emitter.HelperMethods)
        {
            Blank(sb);
            sb.Append(helperMethod);
        }

        // Close class — no trailing newline (SA1518)
        sb.Append('}');

        return sb.ToString();
    }

    private static void L(StringBuilder sb, string indent, string line)
    {
        sb.Append(indent).Append(line).Append('\n');
    }

    private static void Blank(StringBuilder sb)
    {
        sb.Append('\n');
    }

    private static string Utf8Literal(byte[] bytes)
    {
        StringBuilder sb = new(bytes.Length * 4 + 4);
        sb.Append("new byte[] { ");
        for (int i = 0; i < bytes.Length; i++)
        {
            if (i > 0)
            {
                sb.Append(", ");
            }

            sb.Append("0x");
            sb.Append(bytes[i].ToString("X2"));
        }

        sb.Append(" }");
        return sb.ToString();
    }

    private static string EscapeStringLiteral(string value)
    {
        StringBuilder sb = new(value.Length + 4);
        foreach (char ch in value)
        {
            switch (ch)
            {
                case '"': sb.Append("\\\""); break;
                case '\\': sb.Append("\\\\"); break;
                case '\n': sb.Append("\\n"); break;
                case '\r': sb.Append("\\r"); break;
                case '\t': sb.Append("\\t"); break;
                case '\0': sb.Append("\\0"); break;
                default:
                    if (ch < 0x20)
                    {
                        sb.Append($"\\u{(int)ch:X4}");
                    }
                    else
                    {
                        sb.Append(ch);
                    }

                    break;
            }
        }

        return sb.ToString();
    }

    private static byte[] LiteralToUtf8(string rawJson)
    {
        return Encoding.UTF8.GetBytes(rawJson);
    }

    /// <summary>
    /// Unescapes a JSON string literal (including surrounding double quotes)
    /// to produce the actual string value. Handles standard JSON escape sequences:
    /// <c>\\</c>, <c>\"</c>, <c>\/</c>, <c>\b</c>, <c>\f</c>, <c>\n</c>,
    /// <c>\r</c>, <c>\t</c>, and <c>\uXXXX</c>.
    /// </summary>
    private static string UnescapeJsonString(string rawJson)
    {
        // Strip surrounding double quotes
        string content = rawJson.Substring(1, rawJson.Length - 2);

        if (content.IndexOf('\\') < 0)
        {
            return content;
        }

        StringBuilder sb = new(content.Length);
        for (int i = 0; i < content.Length; i++)
        {
            if (content[i] == '\\' && i + 1 < content.Length)
            {
                char next = content[i + 1];
                switch (next)
                {
                    case '"': sb.Append('"'); i++; break;
                    case '\\': sb.Append('\\'); i++; break;
                    case '/': sb.Append('/'); i++; break;
                    case 'b': sb.Append('\b'); i++; break;
                    case 'f': sb.Append('\f'); i++; break;
                    case 'n': sb.Append('\n'); i++; break;
                    case 'r': sb.Append('\r'); i++; break;
                    case 't': sb.Append('\t'); i++; break;
                    case 'u':
                        if (i + 5 <= content.Length)
                        {
#if NETSTANDARD2_0
                            string hex = content.Substring(i + 2, 4);
#else
                            ReadOnlySpan<char> hex = content.AsSpan(i + 2, 4);
#endif
                            if (int.TryParse(hex, System.Globalization.NumberStyles.HexNumber, null, out int codePoint))
                            {
                                sb.Append((char)codePoint);
                                i += 5;
                            }
                            else
                            {
                                sb.Append(content[i]);
                            }
                        }
                        else
                        {
                            sb.Append(content[i]);
                        }

                        break;

                    default:
                        sb.Append(content[i]);
                        break;
                }
            }
            else
            {
                sb.Append(content[i]);
            }
        }

        return sb.ToString();
    }

    private static string TranslateIRegexpForCodeGen(string pattern)
    {
        const string iRegexpDot = @"(?:[^\r\n\uD800-\uDFFF]|[\uD800-\uDBFF][\uDC00-\uDFFF])";

        StringBuilder sb = new(pattern.Length * 2);
        for (int i = 0; i < pattern.Length; i++)
        {
            char c = pattern[i];
            if (c == '\\' && i + 1 < pattern.Length)
            {
                sb.Append(c);
                sb.Append(pattern[i + 1]);
                i++;
            }
            else if (c == '[')
            {
                sb.Append(c);
                i++;
                if (i < pattern.Length && pattern[i] == '^')
                {
                    sb.Append(pattern[i]);
                    i++;
                }

                if (i < pattern.Length && pattern[i] == ']')
                {
                    sb.Append(pattern[i]);
                    i++;
                }

                while (i < pattern.Length && pattern[i] != ']')
                {
                    if (pattern[i] == '\\' && i + 1 < pattern.Length)
                    {
                        sb.Append(pattern[i]);
                        sb.Append(pattern[i + 1]);
                        i += 2;
                    }
                    else
                    {
                        sb.Append(pattern[i]);
                        i++;
                    }
                }

                if (i < pattern.Length)
                {
                    sb.Append(pattern[i]);
                }
            }
            else if (c == '.')
            {
                sb.Append(iRegexpDot);
            }
            else
            {
                sb.Append(c);
            }
        }

        return sb.ToString();
    }

    /// <summary>
    /// Walks the JSONPath AST and emits C# code into a StringBuilder.
    /// </summary>
    private sealed class Emitter
    {
        private int varCounter;
        private int nameCounter;
        private int literalCounter;
        private int regexCounter;
        private int filterQueryCounter;
        private string rootVarName = "data";

        public List<(string FieldName, string Declaration)> StaticFields { get; } = [];

        public List<(string FieldName, string Declaration)> NameFields { get; } = [];

        public List<(string FieldName, string Declaration)> RegexFields { get; } = [];

        public List<string> HelperMethods { get; } = [];

        private string NextVar() => $"v{this.varCounter++}";

        public void EmitQueryNodes(StringBuilder body, QueryNode query, string indent)
        {
            ImmutableArray<SegmentNode> segments = query.Segments;

            if (segments.Length == 0)
            {
                L(body, indent, "result.Append(data);");
                return;
            }

            // Find the first non-singleton segment
            int splitIdx = 0;
            while (splitIdx < segments.Length && IsSingletonSegment(segments[splitIdx]))
            {
                splitIdx++;
            }

            // Emit singleton prefix
            string currentVar = "data";
            for (int i = 0; i < splitIdx; i++)
            {
                currentVar = this.EmitSingletonLookup(
                    body, (ChildSegmentNode)segments[i], indent, currentVar);
                L(body, indent, $"if ({currentVar}.IsNullOrUndefined()) {{ return; }}");
                Blank(body);
            }

            if (splitIdx == segments.Length)
            {
                // All segments are singleton — append single result
                L(body, indent, $"result.Append({currentVar});");
                return;
            }

            // Streaming: emit remaining segments as nested loops writing directly to result
            this.EmitStreamingChain(body, segments, splitIdx, indent, currentVar);
        }

        private static bool IsSingletonSegment(SegmentNode segment)
        {
            if (segment is not ChildSegmentNode)
            {
                return false;
            }

            if (segment.Selectors.Length != 1)
            {
                return false;
            }

            return segment.Selectors[0] is NameSelectorNode or IndexSelectorNode;
        }

        private string EmitSingletonLookup(
            StringBuilder body,
            ChildSegmentNode segment,
            string indent,
            string inputVar)
        {
            SelectorNode sel = segment.Selectors[0];
            string resultVar = this.NextVar();

            if (sel is NameSelectorNode name)
            {
                string nameField = this.EmitNameField(name.Name);
                L(body, indent, $"JsonElement {resultVar} = default;");
                L(body, indent, $"if ({inputVar}.ValueKind == JsonValueKind.Object)");
                L(body, indent, "{");
                L(body, indent, $"    {inputVar}.TryGetProperty({nameField}, out {resultVar});");
                L(body, indent, "}");
            }
            else if (sel is IndexSelectorNode idx)
            {
                L(body, indent, $"JsonElement {resultVar} = default;");
                L(body, indent, $"if ({inputVar}.ValueKind == JsonValueKind.Array)");
                L(body, indent, "{");
                L(body, indent, $"    int _len_{resultVar} = {inputVar}.GetArrayLength();");
                L(body, indent, $"    int _idx_{resultVar} = {H}.NormalizeIndex({idx.Index}L, _len_{resultVar});");
                L(body, indent, $"    if (_idx_{resultVar} >= 0 && _idx_{resultVar} < _len_{resultVar})");
                L(body, indent, "    {");
                L(body, indent, $"        {resultVar} = {inputVar}[_idx_{resultVar}];");
                L(body, indent, "    }");
                L(body, indent, "}");
            }

            return resultVar;
        }

        /// <summary>
        /// Emits a streaming chain of segments starting at <paramref name="segmentIndex"/>.
        /// Each segment generates a loop or check, nesting the remaining segments inside.
        /// When <paramref name="counterTarget"/> is null, the terminal writes to <c>result.Append(...)</c>.
        /// When set, the terminal increments the count and captures the first element (used by helper methods).
        /// </summary>
        private void EmitStreamingChain(
            StringBuilder body,
            ImmutableArray<SegmentNode> segments,
            int segmentIndex,
            string indent,
            string inputVar,
            (string Count, string First)? counterTarget = null)
        {
            if (segmentIndex >= segments.Length)
            {
                if (counterTarget is var (cnt, first))
                {
                    L(body, indent, $"if ({cnt} == 0) {{ {first} = {inputVar}; }}");
                    L(body, indent, $"{cnt}++;");
                }
                else
                {
                    L(body, indent, $"result.Append({inputVar});");
                }

                return;
            }

            SegmentNode segment = segments[segmentIndex];

            if (segment is DescendantSegmentNode)
            {
                this.EmitDescendantStreaming(body, segment.Selectors, segments, segmentIndex, indent, inputVar, counterTarget);
            }
            else
            {
                for (int i = 0; i < segment.Selectors.Length; i++)
                {
                    this.EmitSelectorStreaming(body, segment.Selectors[i], segments, segmentIndex + 1, indent, inputVar, counterTarget);
                }
            }
        }

        private void EmitSelectorStreaming(
            StringBuilder body,
            SelectorNode selector,
            ImmutableArray<SegmentNode> segments,
            int nextSegmentIndex,
            string indent,
            string nodeVar,
            (string Count, string First)? counterTarget)
        {
            switch (selector)
            {
                case NameSelectorNode name:
                    this.EmitNameSelectorStreaming(body, name, segments, nextSegmentIndex, indent, nodeVar, counterTarget);
                    break;
                case IndexSelectorNode idx:
                    this.EmitIndexSelectorStreaming(body, idx, segments, nextSegmentIndex, indent, nodeVar, counterTarget);
                    break;
                case WildcardSelectorNode:
                    this.EmitWildcardSelectorStreaming(body, segments, nextSegmentIndex, indent, nodeVar, counterTarget);
                    break;
                case SliceSelectorNode slice:
                    this.EmitSliceSelectorStreaming(body, slice, segments, nextSegmentIndex, indent, nodeVar, counterTarget);
                    break;
                case FilterSelectorNode filter:
                    this.EmitFilterSelectorStreaming(body, filter, segments, nextSegmentIndex, indent, nodeVar, counterTarget);
                    break;
            }
        }

        private void EmitNameSelectorStreaming(
            StringBuilder body,
            NameSelectorNode name,
            ImmutableArray<SegmentNode> segments,
            int nextSegmentIndex,
            string indent,
            string nodeVar,
            (string Count, string First)? counterTarget)
        {
            string nameField = this.EmitNameField(name.Name);
            string propVar = $"_prop{this.varCounter++}";
            L(body, indent, $"if ({nodeVar}.ValueKind == JsonValueKind.Object && {nodeVar}.TryGetProperty({nameField}, out JsonElement {propVar}))");
            L(body, indent, "{");
            this.EmitStreamingChain(body, segments, nextSegmentIndex, indent + "    ", propVar, counterTarget);
            L(body, indent, "}");
        }

        private void EmitIndexSelectorStreaming(
            StringBuilder body,
            IndexSelectorNode idx,
            ImmutableArray<SegmentNode> segments,
            int nextSegmentIndex,
            string indent,
            string nodeVar,
            (string Count, string First)? counterTarget)
        {
            string c = this.varCounter++.ToString();
            L(body, indent, $"if ({nodeVar}.ValueKind == JsonValueKind.Array)");
            L(body, indent, "{");

            string ii = indent + "    ";
            L(body, ii, $"int _len{c} = {nodeVar}.GetArrayLength();");
            L(body, ii, $"int _idx{c} = {H}.NormalizeIndex({idx.Index}L, _len{c});");
            L(body, ii, $"if (_idx{c} >= 0 && _idx{c} < _len{c})");
            L(body, ii, "{");
            this.EmitStreamingChain(body, segments, nextSegmentIndex, ii + "    ", $"{nodeVar}[_idx{c}]", counterTarget);
            L(body, ii, "}");

            L(body, indent, "}");
        }

        private void EmitWildcardSelectorStreaming(
            StringBuilder body,
            ImmutableArray<SegmentNode> segments,
            int nextSegmentIndex,
            string indent,
            string nodeVar,
            (string Count, string First)? counterTarget)
        {
            string c = this.varCounter++.ToString();
            L(body, indent, $"if ({nodeVar}.ValueKind == JsonValueKind.Object)");
            L(body, indent, "{");
            L(body, indent, $"    foreach (var _wp{c} in {nodeVar}.EnumerateObject())");
            L(body, indent, "    {");
            this.EmitStreamingChain(body, segments, nextSegmentIndex, indent + "        ", $"_wp{c}.Value", counterTarget);
            L(body, indent, "    }");
            L(body, indent, "}");
            L(body, indent, $"else if ({nodeVar}.ValueKind == JsonValueKind.Array)");
            L(body, indent, "{");
            L(body, indent, $"    foreach (JsonElement _wi{c} in {nodeVar}.EnumerateArray())");
            L(body, indent, "    {");
            this.EmitStreamingChain(body, segments, nextSegmentIndex, indent + "        ", $"_wi{c}", counterTarget);
            L(body, indent, "    }");
            L(body, indent, "}");
        }

        private void EmitSliceSelectorStreaming(
            StringBuilder body,
            SliceSelectorNode slice,
            ImmutableArray<SegmentNode> segments,
            int nextSegmentIndex,
            string indent,
            string nodeVar,
            (string Count, string First)? counterTarget)
        {
            string c = this.varCounter++.ToString();
            string startExpr = slice.Start.HasValue ? $"{slice.Start.Value}L" : "null";
            string endExpr = slice.End.HasValue ? $"{slice.End.Value}L" : "null";
            string stepExpr = slice.Step.HasValue ? $"{slice.Step.Value}L" : "null";

            L(body, indent, $"if ({nodeVar}.ValueKind == JsonValueKind.Array)");
            L(body, indent, "{");

            string ii = indent + "    ";
            L(body, ii, $"int _sLen{c} = {nodeVar}.GetArrayLength();");
            L(body, ii, $"var _slice{c} = {H}.NormalizeSlice({startExpr}, {endExpr}, {stepExpr}, _sLen{c});");
            L(body, ii, $"if (_slice{c}.Step > 0)");
            L(body, ii, "{");
            L(body, ii, $"    for (int _sI{c} = _slice{c}.Start; _sI{c} < _slice{c}.End; _sI{c} += _slice{c}.Step)");
            L(body, ii, "    {");
            this.EmitStreamingChain(body, segments, nextSegmentIndex, ii + "        ", $"{nodeVar}[_sI{c}]", counterTarget);
            L(body, ii, "    }");
            L(body, ii, "}");
            L(body, ii, $"else if (_slice{c}.Step < 0)");
            L(body, ii, "{");
            L(body, ii, $"    for (int _sI{c} = _slice{c}.Start; _sI{c} > _slice{c}.End; _sI{c} += _slice{c}.Step)");
            L(body, ii, "    {");
            this.EmitStreamingChain(body, segments, nextSegmentIndex, ii + "        ", $"{nodeVar}[_sI{c}]", counterTarget);
            L(body, ii, "    }");
            L(body, ii, "}");

            L(body, indent, "}");
        }

        private void EmitFilterSelectorStreaming(
            StringBuilder body,
            FilterSelectorNode filter,
            ImmutableArray<SegmentNode> segments,
            int nextSegmentIndex,
            string indent,
            string nodeVar,
            (string Count, string First)? counterTarget)
        {
            string c = this.varCounter++.ToString();

            // Array case
            L(body, indent, $"if ({nodeVar}.ValueKind == JsonValueKind.Array)");
            L(body, indent, "{");
            string itemVar = $"_fi{c}";
            L(body, indent, $"    foreach (JsonElement {itemVar} in {nodeVar}.EnumerateArray())");
            L(body, indent, "    {");

            string filterIndent = indent + "        ";
            string boolVar = this.EmitFilterBool(body, filter.Expression, filterIndent, itemVar);
            L(body, filterIndent, $"if ({boolVar})");
            L(body, filterIndent, "{");
            this.EmitStreamingChain(body, segments, nextSegmentIndex, filterIndent + "    ", itemVar, counterTarget);
            L(body, filterIndent, "}");

            L(body, indent, "    }");
            L(body, indent, "}");

            // Object case
            L(body, indent, $"else if ({nodeVar}.ValueKind == JsonValueKind.Object)");
            L(body, indent, "{");
            string propVar = $"_fp{c}";
            L(body, indent, $"    foreach (var {propVar} in {nodeVar}.EnumerateObject())");
            L(body, indent, "    {");

            string boolVar2 = this.EmitFilterBool(body, filter.Expression, filterIndent, $"{propVar}.Value");
            L(body, filterIndent, $"if ({boolVar2})");
            L(body, filterIndent, "{");
            this.EmitStreamingChain(body, segments, nextSegmentIndex, filterIndent + "    ", $"{propVar}.Value", counterTarget);
            L(body, filterIndent, "}");

            L(body, indent, "    }");
            L(body, indent, "}");
        }

        private void EmitDescendantStreaming(
            StringBuilder body,
            ImmutableArray<SelectorNode> selectors,
            ImmutableArray<SegmentNode> segments,
            int segmentIndex,
            string indent,
            string inputVar,
            (string Count, string First)? counterTarget)
        {
            // Specialization: descendant with single name selector
            if (selectors.Length == 1 && selectors[0] is NameSelectorNode nameSelector)
            {
                this.EmitDescendantForNameStreaming(body, nameSelector, segments, segmentIndex, indent, inputVar, counterTarget);
                return;
            }

            // General DFS: pop node, apply selectors, push container children only.
            string c = this.varCounter++.ToString();
            string stackVar = $"_dStk{c}";
            string capVar = $"_dCap{c}";
            string sizeVar = $"_dSz{c}";
            string curVar = $"_dCur{c}";

            L(body, indent, $"int {capVar} = 64;");
            L(body, indent, $"JsonElement[] {stackVar} = ArrayPool<JsonElement>.Shared.Rent({capVar});");
            L(body, indent, "try");
            L(body, indent, "{");

            string ti = indent + "    ";
            L(body, ti, $"int {sizeVar} = 0;");
            L(body, ti, $"{stackVar}[{sizeVar}++] = {inputVar};");

            L(body, ti, $"while ({sizeVar} > 0)");
            L(body, ti, "{");

            string wi = ti + "    ";
            L(body, wi, $"JsonElement {curVar} = {stackVar}[--{sizeVar}];");

            // Apply selectors at this node — streaming into downstream
            for (int i = 0; i < selectors.Length; i++)
            {
                this.EmitSelectorStreaming(body, selectors[i], segments, segmentIndex + 1, wi, curVar, counterTarget);
            }

            // Push container children only — skip primitives
            string csVar = $"_dCs{c}";
            L(body, wi, $"if ({curVar}.ValueKind == JsonValueKind.Object)");
            L(body, wi, "{");

            string oi = wi + "    ";
            L(body, oi, $"int {csVar} = {sizeVar};");
            L(body, oi, $"foreach (var _dp{c} in {curVar}.EnumerateObject())");
            L(body, oi, "{");
            L(body, oi, $"    if (_dp{c}.Value.ValueKind == JsonValueKind.Object || _dp{c}.Value.ValueKind == JsonValueKind.Array)");
            L(body, oi, "    {");
            L(body, oi, $"        if ({sizeVar} >= {capVar}) {{ {H}.GrowStack(ref {stackVar}, ref {capVar}, {sizeVar}); }}");
            L(body, oi, $"        {stackVar}[{sizeVar}++] = _dp{c}.Value;");
            L(body, oi, "    }");
            L(body, oi, "}");
            L(body, oi, $"{H}.ReverseRegion({stackVar}, {csVar}, {sizeVar} - {csVar});");

            L(body, wi, "}");
            L(body, wi, $"else if ({curVar}.ValueKind == JsonValueKind.Array)");
            L(body, wi, "{");

            string ai = wi + "    ";
            L(body, ai, $"int {csVar} = {sizeVar};");
            L(body, ai, $"foreach (JsonElement _da{c} in {curVar}.EnumerateArray())");
            L(body, ai, "{");
            L(body, ai, $"    if (_da{c}.ValueKind == JsonValueKind.Object || _da{c}.ValueKind == JsonValueKind.Array)");
            L(body, ai, "    {");
            L(body, ai, $"        if ({sizeVar} >= {capVar}) {{ {H}.GrowStack(ref {stackVar}, ref {capVar}, {sizeVar}); }}");
            L(body, ai, $"        {stackVar}[{sizeVar}++] = _da{c};");
            L(body, ai, "    }");
            L(body, ai, "}");
            L(body, ai, $"{H}.ReverseRegion({stackVar}, {csVar}, {sizeVar} - {csVar});");

            L(body, wi, "}");

            L(body, ti, "}");

            L(body, indent, "}");
            L(body, indent, "finally");
            L(body, indent, "{");
            L(body, indent, $"    ArrayPool<JsonElement>.Shared.Return({stackVar});");
            L(body, indent, "}");
        }

        private void EmitDescendantForNameStreaming(
            StringBuilder body,
            NameSelectorNode name,
            ImmutableArray<SegmentNode> segments,
            int segmentIndex,
            string indent,
            string inputVar,
            (string Count, string First)? counterTarget)
        {
            string nameField = this.EmitNameField(name.Name);
            int nextIndex = segmentIndex + 1;

            // Terminal segment: use recursive helper (no ArrayPool at all)
            if (nextIndex >= segments.Length)
            {
                if (counterTarget is var (cnt, first))
                {
                    L(body, indent, $"{H}.DescendantsForNameCount({inputVar}, {nameField}, ref {cnt}, ref {first});");
                }
                else
                {
                    L(body, indent, $"{H}.DescendantsForName({inputVar}, {nameField}, ref result);");
                }

                return;
            }

            // Non-terminal: optimized iterative DFS, only push containers, inline name check
            string c = this.varCounter++.ToString();
            string stackVar = $"_dStk{c}";
            string capVar = $"_dCap{c}";
            string sizeVar = $"_dSz{c}";
            string curVar = $"_dCur{c}";
            string csVar = $"_dCs{c}";

            L(body, indent, $"int {capVar} = 64;");
            L(body, indent, $"JsonElement[] {stackVar} = ArrayPool<JsonElement>.Shared.Rent({capVar});");
            L(body, indent, "try");
            L(body, indent, "{");

            string ti = indent + "    ";
            L(body, ti, $"int {sizeVar} = 0;");
            L(body, ti, $"{stackVar}[{sizeVar}++] = {inputVar};");
            L(body, ti, $"while ({sizeVar} > 0)");
            L(body, ti, "{");

            string wi = ti + "    ";
            L(body, wi, $"JsonElement {curVar} = {stackVar}[--{sizeVar}];");

            // Inline name selector — single-pass: check name and push containers in one enumeration
            L(body, wi, $"if ({curVar}.ValueKind == JsonValueKind.Object)");
            L(body, wi, "{");

            string oi = wi + "    ";
            L(body, oi, $"int {csVar} = {sizeVar};");
            L(body, oi, $"foreach (var _dp{c} in {curVar}.EnumerateObject())");
            L(body, oi, "{");

            string fi = oi + "    ";
            L(body, fi, $"if (_dp{c}.NameEquals({nameField}))");
            L(body, fi, "{");
            this.EmitStreamingChain(body, segments, nextIndex, fi + "    ", $"_dp{c}.Value", counterTarget);
            L(body, fi, "}");
            L(body, fi, $"if (_dp{c}.Value.ValueKind == JsonValueKind.Object || _dp{c}.Value.ValueKind == JsonValueKind.Array)");
            L(body, fi, "{");
            L(body, fi, $"    if ({sizeVar} >= {capVar}) {{ {H}.GrowStack(ref {stackVar}, ref {capVar}, {sizeVar}); }}");
            L(body, fi, $"    {stackVar}[{sizeVar}++] = _dp{c}.Value;");
            L(body, fi, "}");

            L(body, oi, "}");
            L(body, oi, $"{H}.ReverseRegion({stackVar}, {csVar}, {sizeVar} - {csVar});");

            L(body, wi, "}");
            L(body, wi, $"else if ({curVar}.ValueKind == JsonValueKind.Array)");
            L(body, wi, "{");

            string ai = wi + "    ";
            L(body, ai, $"int {csVar} = {sizeVar};");
            L(body, ai, $"foreach (JsonElement _da{c} in {curVar}.EnumerateArray())");
            L(body, ai, "{");
            L(body, ai, $"    if (_da{c}.ValueKind == JsonValueKind.Object || _da{c}.ValueKind == JsonValueKind.Array)");
            L(body, ai, "    {");
            L(body, ai, $"        if ({sizeVar} >= {capVar}) {{ {H}.GrowStack(ref {stackVar}, ref {capVar}, {sizeVar}); }}");
            L(body, ai, $"        {stackVar}[{sizeVar}++] = _da{c};");
            L(body, ai, "    }");
            L(body, ai, "}");
            L(body, ai, $"{H}.ReverseRegion({stackVar}, {csVar}, {sizeVar} - {csVar});");

            L(body, wi, "}");
            L(body, ti, "}");

            L(body, indent, "}");
            L(body, indent, "finally");
            L(body, indent, "{");
            L(body, indent, $"    ArrayPool<JsonElement>.Shared.Return({stackVar});");
            L(body, indent, "}");
        }

        // ── Filter expression emission (bool context) ────────────────────
        private string EmitFilterBool(
            StringBuilder body,
            FilterExpressionNode expr,
            string indent,
            string currentVar)
        {
            switch (expr)
            {
                case ComparisonNode cmp:
                    return this.EmitComparison(body, cmp, indent, currentVar);
                case LogicalAndNode and:
                    return this.EmitLogicalAnd(body, and, indent, currentVar);
                case LogicalOrNode or:
                    return this.EmitLogicalOr(body, or, indent, currentVar);
                case LogicalNotNode not:
                    return this.EmitLogicalNot(body, not, indent, currentVar);
                case FilterQueryNode query:
                    return this.EmitFilterQueryAsTest(body, query, indent, currentVar);
                case FunctionCallNode func when func.Name == "match" || func.Name == "search":
                    return this.EmitMatchOrSearch(body, func, indent, currentVar);
                case ParenExpressionNode paren:
                    return this.EmitFilterBool(body, paren.Inner, indent, currentVar);
                default:
                    // Fallback: treat as existence (non-null = true)
                    string valVar = this.EmitFilterValue(body, expr, indent, currentVar);
                    string boolVar = this.NextVar();
                    L(body, indent, $"bool {boolVar} = {valVar}.ValueKind != JsonValueKind.Undefined;");
                    return boolVar;
            }
        }

        private string EmitComparison(
            StringBuilder body,
            ComparisonNode cmp,
            string indent,
            string currentVar)
        {
            string leftVar = this.EmitFilterValue(body, cmp.Left, indent, currentVar);
            string rightVar = this.EmitFilterValue(body, cmp.Right, indent, currentVar);
            int opInt = (int)cmp.Op;
            string resultVar = this.NextVar();
            L(body, indent, $"bool {resultVar} = {H}.CompareValues({leftVar}, {rightVar}, {opInt});");
            return resultVar;
        }

        private string EmitLogicalAnd(
            StringBuilder body,
            LogicalAndNode and,
            string indent,
            string currentVar)
        {
            string resultVar = this.NextVar();
            L(body, indent, $"bool {resultVar} = false;");
            L(body, indent, "{");

            string innerIndent = indent + "    ";
            string leftVar = this.EmitFilterBool(body, and.Left, innerIndent, currentVar);
            L(body, innerIndent, $"if ({leftVar})");
            L(body, innerIndent, "{");

            string rightIndent = innerIndent + "    ";
            string rightVar = this.EmitFilterBool(body, and.Right, rightIndent, currentVar);
            L(body, rightIndent, $"{resultVar} = {rightVar};");

            L(body, innerIndent, "}");
            L(body, indent, "}");

            return resultVar;
        }

        private string EmitLogicalOr(
            StringBuilder body,
            LogicalOrNode or,
            string indent,
            string currentVar)
        {
            string resultVar = this.NextVar();
            L(body, indent, $"bool {resultVar} = true;");
            L(body, indent, "{");

            string innerIndent = indent + "    ";
            string leftVar = this.EmitFilterBool(body, or.Left, innerIndent, currentVar);
            L(body, innerIndent, $"if (!{leftVar})");
            L(body, innerIndent, "{");

            string rightIndent = innerIndent + "    ";
            string rightVar = this.EmitFilterBool(body, or.Right, rightIndent, currentVar);
            L(body, rightIndent, $"{resultVar} = {rightVar};");

            L(body, innerIndent, "}");
            L(body, indent, "}");

            return resultVar;
        }

        private string EmitLogicalNot(
            StringBuilder body,
            LogicalNotNode not,
            string indent,
            string currentVar)
        {
            string operandVar = this.EmitFilterBool(body, not.Operand, indent, currentVar);
            string resultVar = this.NextVar();
            L(body, indent, $"bool {resultVar} = !{operandVar};");
            return resultVar;
        }

        private string EmitFilterQueryAsTest(
            StringBuilder body,
            FilterQueryNode query,
            string indent,
            string currentVar)
        {
            if (IsSingularQuery(query))
            {
                // Singular: existence test — check if the final value is defined
                string source = query.IsRelative ? currentVar : this.rootVarName;
                string valVar = this.EmitSingularQueryChain(body, query.Segments, indent, source);
                string resultVar = this.NextVar();
                L(body, indent, $"bool {resultVar} = !{valVar}.IsUndefined();");
                return resultVar;
            }
            else
            {
                // Non-singular: evaluate with counter, check count > 0
                (string countVar, string _) = this.EmitFilterQueryCounter(body, query, indent, currentVar);
                string resultVar = this.NextVar();
                L(body, indent, $"bool {resultVar} = {countVar} > 0;");
                return resultVar;
            }
        }

        // ── Filter expression emission (value/comparable context) ────────
        private string EmitFilterValue(
            StringBuilder body,
            FilterExpressionNode expr,
            string indent,
            string currentVar)
        {
            switch (expr)
            {
                case FilterQueryNode query:
                    return this.EmitFilterQueryAsValue(body, query, indent, currentVar);
                case LiteralNode lit:
                    return this.EmitLiteral(body, lit, indent);
                case FunctionCallNode func:
                    return this.EmitFunctionValue(body, func, indent, currentVar);
                case ParenExpressionNode paren:
                    return this.EmitFilterValue(body, paren.Inner, indent, currentVar);
                default:
                    // Shouldn't happen if parser validated types; return Undefined
                    string v = this.NextVar();
                    L(body, indent, $"JsonElement {v} = default;");
                    return v;
            }
        }

        private string EmitLiteral(
            StringBuilder body,
            LiteralNode lit,
            string indent)
        {
            string fieldRef = this.EmitLiteralFieldRef(lit);
            string resultVar = this.NextVar();
            L(body, indent, $"JsonElement {resultVar} = {fieldRef};");
            return resultVar;
        }

        private string EmitFilterQueryAsValue(
            StringBuilder body,
            FilterQueryNode query,
            string indent,
            string currentVar)
        {
            if (IsSingularQuery(query))
            {
                string source = query.IsRelative ? currentVar : this.rootVarName;
                return this.EmitSingularQueryChain(body, query.Segments, indent, source);
            }
            else
            {
                // Non-singular as comparable: count==1 → first, else Undefined
                (string countVar, string firstVar) = this.EmitFilterQueryCounter(body, query, indent, currentVar);
                string resultVar = this.NextVar();
                L(body, indent, $"JsonElement {resultVar} = {countVar} == 1 ? {firstVar} : default;");
                return resultVar;
            }
        }

        private (string CountVar, string FirstVar) EmitFilterQueryCounter(
            StringBuilder body,
            FilterQueryNode query,
            string indent,
            string currentVar)
        {
            // Generate a helper method for the non-singular query
            string methodName = $"FilterQuery{this.filterQueryCounter++}";
            this.GenerateFilterQueryHelper(query, methodName);

            string source = query.IsRelative ? currentVar : this.rootVarName;
            string countVar = this.NextVar();
            string firstVar = this.NextVar();
            L(body, indent, $"int {countVar} = 0;");
            L(body, indent, $"JsonElement {firstVar} = default;");
            L(body, indent, $"{methodName}({source}, {this.rootVarName}, ref {countVar}, ref {firstVar});");
            return (countVar, firstVar);
        }

        // ── Function emission ────────────────────────────────────────────
        private string EmitFunctionValue(
            StringBuilder body,
            FunctionCallNode func,
            string indent,
            string currentVar)
        {
            switch (func.Name)
            {
                case "length":
                    return this.EmitLengthFunction(body, func, indent, currentVar);
                case "count":
                    return this.EmitCountFunction(body, func, indent, currentVar);
                case "value":
                    return this.EmitValueFunction(body, func, indent, currentVar);
                default:
                    // Unknown function — return Undefined
                    string v = this.NextVar();
                    L(body, indent, $"JsonElement {v} = default;");
                    return v;
            }
        }

        private string EmitLengthFunction(
            StringBuilder body,
            FunctionCallNode func,
            string indent,
            string currentVar)
        {
            string argVar = this.EmitFilterValue(body, func.Arguments[0], indent, currentVar);
            string lenVar = this.NextVar();
            string resultVar = this.NextVar();
            L(body, indent, $"int {lenVar} = {H}.LengthValue({argVar});");
            L(body, indent, $"JsonElement {resultVar} = {lenVar} >= 0 ? {H}.IntToElement({lenVar}) : default;");
            return resultVar;
        }

        private string EmitCountFunction(
            StringBuilder body,
            FunctionCallNode func,
            string indent,
            string currentVar)
        {
            // Argument must be a filter query (NodesType)
            string countVar;
            if (func.Arguments[0] is FilterQueryNode fq)
            {
                (string cVar, string _) = this.EmitFilterQueryCounter(body, fq, indent, currentVar);
                countVar = cVar;
            }
            else
            {
                string nodesVar = this.EmitFilterValue(body, func.Arguments[0], indent, currentVar);
                countVar = this.NextVar();
                L(body, indent, $"int {countVar} = {H}.CountNodes({nodesVar});");
            }

            string resultVar = this.NextVar();
            L(body, indent, $"JsonElement {resultVar} = {H}.IntToElement({countVar});");
            return resultVar;
        }

        private string EmitValueFunction(
            StringBuilder body,
            FunctionCallNode func,
            string indent,
            string currentVar)
        {
            if (func.Arguments[0] is FilterQueryNode fq)
            {
                (string countVar, string firstVar) = this.EmitFilterQueryCounter(body, fq, indent, currentVar);
                string resultVar = this.NextVar();
                L(body, indent, $"JsonElement {resultVar} = {countVar} == 1 ? {firstVar} : default;");
                return resultVar;
            }
            else
            {
                string nodesVar = this.EmitFilterValue(body, func.Arguments[0], indent, currentVar);
                string resultVar = this.NextVar();
                L(body, indent, $"JsonElement {resultVar} = {H}.ValueOfNodes({nodesVar});");
                return resultVar;
            }
        }

        private string EmitMatchOrSearch(
            StringBuilder body,
            FunctionCallNode func,
            string indent,
            string currentVar)
        {
            bool isMatch = func.Name == "match";
            string strVar = this.EmitFilterValue(body, func.Arguments[0], indent, currentVar);
            string resultVar = this.NextVar();
            L(body, indent, $"bool {resultVar} = false;");

            // Check if pattern is a literal string — pre-compile regex
            if (func.Arguments[1] is LiteralNode patLit &&
                patLit.Kind == LiteralKind.String)
            {
                // Unescape the JSON string literal to get the actual pattern value
                string patternStr = UnescapeJsonString(patLit.RawJson);
                string regexField = this.EmitRegexField(patternStr, isMatch);

                L(body, indent, $"if ({strVar}.ValueKind == JsonValueKind.String)");
                L(body, indent, "{");
                L(body, indent, $"    {resultVar} = {regexField}.IsMatch({strVar}.GetString()!);");
                L(body, indent, "}");
            }
            else
            {
                // Dynamic pattern — runtime regex creation
                string patVar = this.EmitFilterValue(body, func.Arguments[1], indent, currentVar);
                L(body, indent, $"if ({strVar}.ValueKind == JsonValueKind.String && {patVar}.ValueKind == JsonValueKind.String)");
                L(body, indent, "{");
                L(body, indent, "    try");
                L(body, indent, "    {");

                string anchor = isMatch ? "\"^(?:\" + " : "\"\"+ ";
                string anchorEnd = isMatch ? " + \")$\"" : string.Empty;
                L(body, indent, $"        string _dp{this.varCounter} = {H}.TranslateIRegexp({patVar}.GetString()!);");
                L(body, indent, $"        var _re{this.varCounter} = new System.Text.RegularExpressions.Regex({anchor}_dp{this.varCounter}{anchorEnd}, System.Text.RegularExpressions.RegexOptions.None, System.TimeSpan.FromSeconds(1));");
                L(body, indent, $"        {resultVar} = _re{this.varCounter}.IsMatch({strVar}.GetString()!);");
                this.varCounter++;

                L(body, indent, "    }");
                L(body, indent, "    catch (System.ArgumentException)");
                L(body, indent, "    {");
                L(body, indent, "    }");
                L(body, indent, "}");
            }

            return resultVar;
        }

        // ── Singular query chain ─────────────────────────────────────────
        private static bool IsSingularQuery(FilterQueryNode query)
        {
            foreach (SegmentNode seg in query.Segments)
            {
                if (seg is not ChildSegmentNode)
                {
                    return false;
                }

                if (seg.Selectors.Length != 1)
                {
                    return false;
                }

                if (seg.Selectors[0] is not (NameSelectorNode or IndexSelectorNode))
                {
                    return false;
                }
            }

            return true;
        }

        private string EmitSingularQueryChain(
            StringBuilder body,
            ImmutableArray<SegmentNode> segments,
            string indent,
            string source)
        {
            string currentVar = source;
            for (int i = 0; i < segments.Length; i++)
            {
                SelectorNode sel = segments[i].Selectors[0];
                string resultVar = this.NextVar();

                if (sel is NameSelectorNode name)
                {
                    string nameField = this.EmitNameField(name.Name);
                    L(body, indent, $"JsonElement {resultVar} = default;");
                    L(body, indent, $"if ({currentVar}.ValueKind == JsonValueKind.Object) {{ {currentVar}.TryGetProperty({nameField}, out {resultVar}); }}");
                }
                else if (sel is IndexSelectorNode idx)
                {
                    L(body, indent, $"JsonElement {resultVar} = default;");
                    L(body, indent, $"if ({currentVar}.ValueKind == JsonValueKind.Array)");
                    L(body, indent, "{");
                    L(body, indent, $"    int _qLen{resultVar} = {currentVar}.GetArrayLength();");
                    L(body, indent, $"    int _qIdx{resultVar} = {H}.NormalizeIndex({idx.Index}L, _qLen{resultVar});");
                    L(body, indent, $"    if (_qIdx{resultVar} >= 0 && _qIdx{resultVar} < _qLen{resultVar}) {{ {resultVar} = {currentVar}[_qIdx{resultVar}]; }}");
                    L(body, indent, "}");
                }

                currentVar = resultVar;
            }

            return currentVar;
        }

        // ── Filter query helper method generation ────────────────────────
        private void GenerateFilterQueryHelper(FilterQueryNode query, string methodName)
        {
            StringBuilder mb = new(2048);
            const string methodIndent = "    ";

            L(mb, methodIndent, $"private static void {methodName}(in JsonElement source, in JsonElement root, ref int count, ref JsonElement first)");
            L(mb, methodIndent, "{");

            const string bodyIndent = methodIndent + "    ";

            if (query.Segments.Length == 0)
            {
                L(mb, bodyIndent, "if (count == 0) { first = source; }");
                L(mb, bodyIndent, "count++;");
                L(mb, methodIndent, "}");
                this.HelperMethods.Add(mb.ToString());
                return;
            }

            // Use streaming chain with counterTarget to write directly to count/first.
            // Set rootVarName to "root" for the helper method scope.
            string savedRootVarName = this.rootVarName;
            this.rootVarName = "root";
            try
            {
                this.EmitStreamingChain(mb, query.Segments, 0, bodyIndent, "source", counterTarget: ("count", "first"));
            }
            finally
            {
                this.rootVarName = savedRootVarName;
            }

            L(mb, methodIndent, "}");
            this.HelperMethods.Add(mb.ToString());
        }

        // ── Field emission helpers ───────────────────────────────────────
        private string EmitNameField(byte[] name)
        {
            string fieldName = $"s_name{this.nameCounter++}";
            this.NameFields.Add((fieldName, $"private static readonly byte[] {fieldName} = {Utf8Literal(name)};"));
            return fieldName;
        }

        private string EmitLiteralFieldRef(LiteralNode lit)
        {
            switch (lit.Kind)
            {
                case LiteralKind.Null:
                    return $"{H}.NullElement";
                case LiteralKind.True:
                    return $"{H}.TrueElement";
                case LiteralKind.False:
                    return $"{H}.FalseElement";
                default:
                    string fieldName = $"s_literal{this.literalCounter++}";
                    byte[] utf8 = LiteralToUtf8(lit.RawJson);
                    this.StaticFields.Add((fieldName, $"private static readonly JsonElement {fieldName} = JsonElement.ParseValue({Utf8Literal(utf8)});"));
                    return fieldName;
            }
        }

        private string EmitRegexField(string pattern, bool fullMatch)
        {
            string fieldName = $"s_regex{this.regexCounter++}";
            string translated = TranslateIRegexpForCodeGen(pattern);
            string escaped;

            if (fullMatch)
            {
                escaped = EscapeStringLiteral("^(?:" + translated + ")$");
            }
            else
            {
                escaped = EscapeStringLiteral(translated);
            }

            this.RegexFields.Add((
                fieldName,
                $"private static readonly System.Text.RegularExpressions.Regex {fieldName} = new System.Text.RegularExpressions.Regex(\"{escaped}\", System.Text.RegularExpressions.RegexOptions.None, System.TimeSpan.FromSeconds(1));"));
            return fieldName;
        }
    }
}