// <copyright file="V3InteropTests.cs" company="Endjin Limited">
// Copyright (c) Endjin Limited. All rights reserved.
// </copyright>

#pragma warning disable SA1600 // Elements should be documented

using System.Text.Json;
using Corvus.Json;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace Corvus.Json.Specs.Tests.JsonModel.V3Interop;

[TestClass]
public class V3InteropTests
{
    [TestMethod]
    [DataRow("\"\"", false, "Flag", 0, "JsonElement")]
    [DataRow("\"\"", false, "Basic", 1, "JsonElement")]
    [DataRow("\"\"", false, "Detailed", 1, "JsonElement")]
    [DataRow("\"\"", false, "Verbose", 210, "JsonElement")]
    [DataRow("\"foo\"", false, "Flag", 0, "JsonElement")]
    [DataRow("\"foo\"", false, "Basic", 1, "JsonElement")]
    [DataRow("\"foo\"", false, "Detailed", 1, "JsonElement")]
    [DataRow("\"foo\"", false, "Verbose", 211, "JsonElement")]
    [DataRow("\"#\\\\foor\\\\bar\"", false, "Flag", 0, "JsonElement")]
    [DataRow("\"#\\\\foor\\\\bar\"", false, "Basic", 1, "JsonElement")]
    [DataRow("\"#\\\\foor\\\\bar\"", false, "Detailed", 1, "JsonElement")]
    [DataRow("\"#\\\\foor\\\\bar\"", false, "Verbose", 209, "JsonElement")]
    [DataRow("\"01234567890123456789012345678901234567890123456789\"", false, "Flag", 0, "JsonElement")]
    [DataRow("\"01234567890123456789012345678901234567890123456789\"", false, "Basic", 1, "JsonElement")]
    [DataRow("\"01234567890123456789012345678901234567890123456789\"", false, "Detailed", 1, "JsonElement")]
    [DataRow("\"01234567890123456789012345678901234567890123456789\"", false, "Verbose", 211, "JsonElement")]
    [DataRow("\"1\"", false, "Flag", 0, "JsonElement")]
    [DataRow("\"2\"", false, "Flag", 0, "JsonElement")]
    [DataRow("\"3\"", false, "Flag", 0, "JsonElement")]
    [DataRow("\"4\"", false, "Flag", 0, "JsonElement")]
    [DataRow("\"5\"", false, "Flag", 0, "JsonElement")]
    [DataRow("\"6\"", false, "Flag", 0, "JsonElement")]
    [DataRow("\"7\"", false, "Flag", 0, "JsonElement")]
    [DataRow("\"8\"", false, "Flag", 0, "JsonElement")]
    [DataRow("\"1\"", false, "Basic", 1, "JsonElement")]
    [DataRow("\"2\"", false, "Basic", 1, "JsonElement")]
    [DataRow("\"3\"", false, "Basic", 1, "JsonElement")]
    [DataRow("\"4\"", false, "Basic", 1, "JsonElement")]
    [DataRow("\"5\"", false, "Basic", 1, "JsonElement")]
    [DataRow("\"6\"", false, "Basic", 1, "JsonElement")]
    [DataRow("\"7\"", false, "Basic", 1, "JsonElement")]
    [DataRow("\"8\"", false, "Basic", 1, "JsonElement")]
    [DataRow("\"1\"", false, "Detailed", 1, "JsonElement")]
    [DataRow("\"2\"", false, "Detailed", 1, "JsonElement")]
    [DataRow("\"3\"", false, "Detailed", 1, "JsonElement")]
    [DataRow("\"4\"", false, "Detailed", 1, "JsonElement")]
    [DataRow("\"5\"", false, "Detailed", 1, "JsonElement")]
    [DataRow("\"6\"", false, "Detailed", 1, "JsonElement")]
    [DataRow("\"7\"", false, "Detailed", 1, "JsonElement")]
    [DataRow("\"8\"", false, "Detailed", 1, "JsonElement")]
    [DataRow("\"1\"", false, "Verbose", 211, "JsonElement")]
    [DataRow("\"2\"", false, "Verbose", 211, "JsonElement")]
    [DataRow("\"3\"", false, "Verbose", 211, "JsonElement")]
    [DataRow("\"4\"", false, "Verbose", 211, "JsonElement")]
    [DataRow("\"5\"", false, "Verbose", 211, "JsonElement")]
    [DataRow("\"6\"", false, "Verbose", 211, "JsonElement")]
    [DataRow("\"7\"", false, "Verbose", 211, "JsonElement")]
    [DataRow("\"8\"", false, "Verbose", 211, "JsonElement")]
    [DataRow("null", false, "Flag", 0, "JsonElement")]
    [DataRow("null", false, "Basic", 1, "JsonElement")]
    [DataRow("null", false, "Detailed", 1, "JsonElement")]
    [DataRow("null", false, "Verbose", 179, "JsonElement")]
    [DataRow("-1", false, "Flag", 0, "JsonElement")]
    [DataRow("0", false, "Flag", 0, "JsonElement")]
    [DataRow("1", false, "Flag", 0, "JsonElement")]
    [DataRow("256", false, "Flag", 0, "JsonElement")]
    [DataRow("-256", false, "Flag", 0, "JsonElement")]
    [DataRow("256.1", false, "Flag", 0, "JsonElement")]
    [DataRow("-256.1", false, "Flag", 0, "JsonElement")]
    [DataRow("-32769", false, "Flag", 0, "JsonElement")]
    [DataRow("32769", false, "Flag", 0, "JsonElement")]
    [DataRow("-32769.1", false, "Flag", 0, "JsonElement")]
    [DataRow("32769.1", false, "Flag", 0, "JsonElement")]
    [DataRow("-65536", false, "Flag", 0, "JsonElement")]
    [DataRow("65536", false, "Flag", 0, "JsonElement")]
    [DataRow("-65536.1", false, "Flag", 0, "JsonElement")]
    [DataRow("65536.1", false, "Flag", 0, "JsonElement")]
    [DataRow("-2147483648", false, "Flag", 0, "JsonElement")]
    [DataRow("2147483648", false, "Flag", 0, "JsonElement")]
    [DataRow("-2147483648.1", false, "Flag", 0, "JsonElement")]
    [DataRow("2147483648.1", false, "Flag", 0, "JsonElement")]
    [DataRow("true", false, "Flag", 0, "JsonElement")]
    [DataRow("[1,2,3]", false, "Flag", 0, "JsonElement")]
    [DataRow("{ \"foo\": \"bar\" }", true, "Flag", 0, "JsonElement")]
    [DataRow("-1", false, "Basic", 1, "JsonElement")]
    [DataRow("0", false, "Basic", 1, "JsonElement")]
    [DataRow("1", false, "Basic", 1, "JsonElement")]
    [DataRow("256", false, "Basic", 1, "JsonElement")]
    [DataRow("-256", false, "Basic", 1, "JsonElement")]
    [DataRow("256.1", false, "Basic", 1, "JsonElement")]
    [DataRow("-256.1", false, "Basic", 1, "JsonElement")]
    [DataRow("-32769", false, "Basic", 1, "JsonElement")]
    [DataRow("32769", false, "Basic", 1, "JsonElement")]
    [DataRow("-32769.1", false, "Basic", 1, "JsonElement")]
    [DataRow("32769.1", false, "Basic", 1, "JsonElement")]
    [DataRow("-65536", false, "Basic", 1, "JsonElement")]
    [DataRow("65536", false, "Basic", 1, "JsonElement")]
    [DataRow("-65536.1", false, "Basic", 1, "JsonElement")]
    [DataRow("65536.1", false, "Basic", 1, "JsonElement")]
    [DataRow("-2147483648", false, "Basic", 1, "JsonElement")]
    [DataRow("2147483648", false, "Basic", 1, "JsonElement")]
    [DataRow("-2147483648.1", false, "Basic", 1, "JsonElement")]
    [DataRow("2147483648.1", false, "Basic", 1, "JsonElement")]
    [DataRow("true", false, "Basic", 1, "JsonElement")]
    [DataRow("[1,2,3]", false, "Basic", 1, "JsonElement")]
    [DataRow("{ \"foo\": \"bar\" }", true, "Basic", 0, "JsonElement")]
    [DataRow("-1", false, "Detailed", 1, "JsonElement")]
    [DataRow("0", false, "Detailed", 1, "JsonElement")]
    [DataRow("1", false, "Detailed", 1, "JsonElement")]
    [DataRow("256", false, "Detailed", 1, "JsonElement")]
    [DataRow("-256", false, "Detailed", 1, "JsonElement")]
    [DataRow("256.1", false, "Detailed", 1, "JsonElement")]
    [DataRow("-256.1", false, "Detailed", 1, "JsonElement")]
    [DataRow("-32769", false, "Detailed", 1, "JsonElement")]
    [DataRow("32769", false, "Detailed", 1, "JsonElement")]
    [DataRow("-32769.1", false, "Detailed", 1, "JsonElement")]
    [DataRow("32769.1", false, "Detailed", 1, "JsonElement")]
    [DataRow("-65536", false, "Detailed", 1, "JsonElement")]
    [DataRow("65536", false, "Detailed", 1, "JsonElement")]
    [DataRow("-65536.1", false, "Detailed", 1, "JsonElement")]
    [DataRow("65536.1", false, "Detailed", 1, "JsonElement")]
    [DataRow("-2147483648", false, "Detailed", 1, "JsonElement")]
    [DataRow("2147483648", false, "Detailed", 1, "JsonElement")]
    [DataRow("-2147483648.1", false, "Detailed", 1, "JsonElement")]
    [DataRow("2147483648.1", false, "Detailed", 1, "JsonElement")]
    [DataRow("true", false, "Detailed", 1, "JsonElement")]
    [DataRow("[1,2,3]", false, "Detailed", 1, "JsonElement")]
    [DataRow("{ \"foo\": \"bar\" }", true, "Detailed", 0, "JsonElement")]
    [DataRow("-1", false, "Verbose", 203, "JsonElement")]
    [DataRow("0", false, "Verbose", 209, "JsonElement")]
    [DataRow("1", false, "Verbose", 209, "JsonElement")]
    [DataRow("256", false, "Verbose", 207, "JsonElement")]
    [DataRow("-256", false, "Verbose", 202, "JsonElement")]
    [DataRow("256.1", false, "Verbose", 198, "JsonElement")]
    [DataRow("-256.1", false, "Verbose", 198, "JsonElement")]
    [DataRow("-32769", false, "Verbose", 201, "JsonElement")]
    [DataRow("32769", false, "Verbose", 206, "JsonElement")]
    [DataRow("-32769.1", false, "Verbose", 198, "JsonElement")]
    [DataRow("32769.1", false, "Verbose", 198, "JsonElement")]
    [DataRow("-65536", false, "Verbose", 200, "JsonElement")]
    [DataRow("65536", false, "Verbose", 203, "JsonElement")]
    [DataRow("-65536.1", false, "Verbose", 197, "JsonElement")]
    [DataRow("65536.1", false, "Verbose", 197, "JsonElement")]
    [DataRow("-2147483648", false, "Verbose", 200, "JsonElement")]
    [DataRow("2147483648", false, "Verbose", 202, "JsonElement")]
    [DataRow("-2147483648.1", false, "Verbose", 197, "JsonElement")]
    [DataRow("2147483648.1", false, "Verbose", 197, "JsonElement")]
    [DataRow("true", false, "Verbose", 179, "JsonElement")]
    [DataRow("[1,2,3]", false, "Verbose", 180, "JsonElement")]
    [DataRow("{ \"foo\": \"bar\" }", true, "Verbose", 179, "JsonElement")]
    [DataRow("\"\"", false, "Flag", 0, "dotnet")]
    [DataRow("\"\"", false, "Basic", 1, "dotnet")]
    [DataRow("\"\"", false, "Detailed", 1, "dotnet")]
    [DataRow("\"\"", false, "Verbose", 210, "dotnet")]
    [DataRow("\"foo\"", false, "Flag", 0, "dotnet")]
    [DataRow("\"foo\"", false, "Basic", 1, "dotnet")]
    [DataRow("\"foo\"", false, "Detailed", 1, "dotnet")]
    [DataRow("\"foo\"", false, "Verbose", 211, "dotnet")]
    [DataRow("\"01234567890123456789012345678901234567890123456789\"", false, "Flag", 0, "dotnet")]
    [DataRow("\"01234567890123456789012345678901234567890123456789\"", false, "Basic", 1, "dotnet")]
    [DataRow("\"01234567890123456789012345678901234567890123456789\"", false, "Detailed", 1, "dotnet")]
    [DataRow("\"01234567890123456789012345678901234567890123456789\"", false, "Verbose", 211, "dotnet")]
    [DataRow("\"#\\\\foo\\\\bar\"", false, "Flag", 0, "dotnet")]
    [DataRow("\"#\\\\foo\\\\bar\"", false, "Basic", 1, "dotnet")]
    [DataRow("\"#\\\\foo\\\\bar\"", false, "Detailed", 1, "dotnet")]
    [DataRow("\"#\\\\foo\\\\bar\"", false, "Verbose", 209, "dotnet")]
    [DataRow("\"1\"", false, "Flag", 0, "dotnet")]
    [DataRow("\"2\"", false, "Flag", 0, "dotnet")]
    [DataRow("\"3\"", false, "Flag", 0, "dotnet")]
    [DataRow("\"4\"", false, "Flag", 0, "dotnet")]
    [DataRow("\"5\"", false, "Flag", 0, "dotnet")]
    [DataRow("\"6\"", false, "Flag", 0, "dotnet")]
    [DataRow("\"7\"", false, "Flag", 0, "dotnet")]
    [DataRow("\"8\"", false, "Flag", 0, "dotnet")]
    [DataRow("\"1\"", false, "Basic", 1, "dotnet")]
    [DataRow("\"2\"", false, "Basic", 1, "dotnet")]
    [DataRow("\"3\"", false, "Basic", 1, "dotnet")]
    [DataRow("\"4\"", false, "Basic", 1, "dotnet")]
    [DataRow("\"5\"", false, "Basic", 1, "dotnet")]
    [DataRow("\"6\"", false, "Basic", 1, "dotnet")]
    [DataRow("\"7\"", false, "Basic", 1, "dotnet")]
    [DataRow("\"8\"", false, "Basic", 1, "dotnet")]
    [DataRow("\"1\"", false, "Detailed", 1, "dotnet")]
    [DataRow("\"2\"", false, "Detailed", 1, "dotnet")]
    [DataRow("\"3\"", false, "Detailed", 1, "dotnet")]
    [DataRow("\"4\"", false, "Detailed", 1, "dotnet")]
    [DataRow("\"5\"", false, "Detailed", 1, "dotnet")]
    [DataRow("\"6\"", false, "Detailed", 1, "dotnet")]
    [DataRow("\"7\"", false, "Detailed", 1, "dotnet")]
    [DataRow("\"8\"", false, "Detailed", 1, "dotnet")]
    [DataRow("\"1\"", false, "Verbose", 211, "dotnet")]
    [DataRow("\"2\"", false, "Verbose", 211, "dotnet")]
    [DataRow("\"3\"", false, "Verbose", 211, "dotnet")]
    [DataRow("\"4\"", false, "Verbose", 211, "dotnet")]
    [DataRow("\"5\"", false, "Verbose", 211, "dotnet")]
    [DataRow("\"6\"", false, "Verbose", 211, "dotnet")]
    [DataRow("\"7\"", false, "Verbose", 211, "dotnet")]
    [DataRow("\"8\"", false, "Verbose", 211, "dotnet")]
    [DataRow("null", false, "Flag", 0, "dotnet")]
    [DataRow("null", false, "Basic", 1, "dotnet")]
    [DataRow("null", false, "Detailed", 1, "dotnet")]
    [DataRow("null", false, "Verbose", 179, "dotnet")]
    [DataRow("-1", false, "Flag", 0, "dotnet")]
    [DataRow("0", false, "Flag", 0, "dotnet")]
    [DataRow("1", false, "Flag", 0, "dotnet")]
    [DataRow("256", false, "Flag", 0, "dotnet")]
    [DataRow("-256", false, "Flag", 0, "dotnet")]
    [DataRow("256.1", false, "Flag", 0, "dotnet")]
    [DataRow("-256.1", false, "Flag", 0, "dotnet")]
    [DataRow("-32769", false, "Flag", 0, "dotnet")]
    [DataRow("32769", false, "Flag", 0, "dotnet")]
    [DataRow("-32769.1", false, "Flag", 0, "dotnet")]
    [DataRow("32769.1", false, "Flag", 0, "dotnet")]
    [DataRow("-65536", false, "Flag", 0, "dotnet")]
    [DataRow("65536", false, "Flag", 0, "dotnet")]
    [DataRow("-65536.1", false, "Flag", 0, "dotnet")]
    [DataRow("65536.1", false, "Flag", 0, "dotnet")]
    [DataRow("-2147483648", false, "Flag", 0, "dotnet")]
    [DataRow("2147483648", false, "Flag", 0, "dotnet")]
    [DataRow("-2147483648.1", false, "Flag", 0, "dotnet")]
    [DataRow("2147483648.1", false, "Flag", 0, "dotnet")]
    [DataRow("true", false, "Flag", 0, "dotnet")]
    [DataRow("[1,2,3]", false, "Flag", 0, "dotnet")]
    [DataRow("{ \"foo\": \"bar\" }", true, "Flag", 0, "dotnet")]
    [DataRow("-1", false, "Basic", 1, "dotnet")]
    [DataRow("0", false, "Basic", 1, "dotnet")]
    [DataRow("1", false, "Basic", 1, "dotnet")]
    [DataRow("256", false, "Basic", 1, "dotnet")]
    [DataRow("-256", false, "Basic", 1, "dotnet")]
    [DataRow("256.1", false, "Basic", 1, "dotnet")]
    [DataRow("-256.1", false, "Basic", 1, "dotnet")]
    [DataRow("-32769", false, "Basic", 1, "dotnet")]
    [DataRow("32769", false, "Basic", 1, "dotnet")]
    [DataRow("-32769.1", false, "Basic", 1, "dotnet")]
    [DataRow("32769.1", false, "Basic", 1, "dotnet")]
    [DataRow("-65536", false, "Basic", 1, "dotnet")]
    [DataRow("65536", false, "Basic", 1, "dotnet")]
    [DataRow("-65536.1", false, "Basic", 1, "dotnet")]
    [DataRow("65536.1", false, "Basic", 1, "dotnet")]
    [DataRow("-2147483648", false, "Basic", 1, "dotnet")]
    [DataRow("2147483648", false, "Basic", 1, "dotnet")]
    [DataRow("-2147483648.1", false, "Basic", 1, "dotnet")]
    [DataRow("2147483648.1", false, "Basic", 1, "dotnet")]
    [DataRow("true", false, "Basic", 1, "dotnet")]
    [DataRow("[1,2,3]", false, "Basic", 1, "dotnet")]
    [DataRow("{ \"foo\": \"bar\" }", true, "Basic", 0, "dotnet")]
    [DataRow("-1", false, "Detailed", 1, "dotnet")]
    [DataRow("0", false, "Detailed", 1, "dotnet")]
    [DataRow("1", false, "Detailed", 1, "dotnet")]
    [DataRow("256", false, "Detailed", 1, "dotnet")]
    [DataRow("-256", false, "Detailed", 1, "dotnet")]
    [DataRow("256.1", false, "Detailed", 1, "dotnet")]
    [DataRow("-256.1", false, "Detailed", 1, "dotnet")]
    [DataRow("-32769", false, "Detailed", 1, "dotnet")]
    [DataRow("32769", false, "Detailed", 1, "dotnet")]
    [DataRow("-32769.1", false, "Detailed", 1, "dotnet")]
    [DataRow("32769.1", false, "Detailed", 1, "dotnet")]
    [DataRow("-65536", false, "Detailed", 1, "dotnet")]
    [DataRow("65536", false, "Detailed", 1, "dotnet")]
    [DataRow("-65536.1", false, "Detailed", 1, "dotnet")]
    [DataRow("65536.1", false, "Detailed", 1, "dotnet")]
    [DataRow("-2147483648", false, "Detailed", 1, "dotnet")]
    [DataRow("2147483648", false, "Detailed", 1, "dotnet")]
    [DataRow("-2147483648.1", false, "Detailed", 1, "dotnet")]
    [DataRow("2147483648.1", false, "Detailed", 1, "dotnet")]
    [DataRow("true", false, "Detailed", 1, "dotnet")]
    [DataRow("[1,2,3]", false, "Detailed", 1, "dotnet")]
    [DataRow("{ \"foo\": \"bar\" }", true, "Detailed", 0, "dotnet")]
    [DataRow("-1", false, "Verbose", 203, "dotnet")]
    [DataRow("0", false, "Verbose", 209, "dotnet")]
    [DataRow("1", false, "Verbose", 209, "dotnet")]
    [DataRow("256", false, "Verbose", 207, "dotnet")]
    [DataRow("-256", false, "Verbose", 202, "dotnet")]
    [DataRow("256.1", false, "Verbose", 198, "dotnet")]
    [DataRow("-256.1", false, "Verbose", 198, "dotnet")]
    [DataRow("-32769", false, "Verbose", 201, "dotnet")]
    [DataRow("32769", false, "Verbose", 206, "dotnet")]
    [DataRow("-32769.1", false, "Verbose", 198, "dotnet")]
    [DataRow("32769.1", false, "Verbose", 198, "dotnet")]
    [DataRow("-65536", false, "Verbose", 200, "dotnet")]
    [DataRow("65536", false, "Verbose", 203, "dotnet")]
    [DataRow("-65536.1", false, "Verbose", 197, "dotnet")]
    [DataRow("65536.1", false, "Verbose", 197, "dotnet")]
    [DataRow("-2147483648", false, "Verbose", 200, "dotnet")]
    [DataRow("2147483648", false, "Verbose", 202, "dotnet")]
    [DataRow("-2147483648.1", false, "Verbose", 197, "dotnet")]
    [DataRow("2147483648.1", false, "Verbose", 197, "dotnet")]
    [DataRow("true", false, "Verbose", 179, "dotnet")]
    [DataRow("[1,2,3]", false, "Verbose", 180, "dotnet")]
    [DataRow("{ \"foo\": \"bar\" }", true, "Verbose", 179, "dotnet")]
    public void ValidateV3Model(string inputData, bool valid, string level, int count, string instanceType)
    {
        using var doc = JsonDocument.Parse(inputData);
        JsonElement jsonElement = doc.RootElement.Clone();

        Corvus.Json.ValidationLevel validationLevel = level switch
        {
            "Flag" => Corvus.Json.ValidationLevel.Flag,
            "Basic" => Corvus.Json.ValidationLevel.Basic,
            "Detailed" => Corvus.Json.ValidationLevel.Detailed,
            "Verbose" => Corvus.Json.ValidationLevel.Verbose,
            _ => throw new InvalidOperationException($"Unknown validation level: {level}"),
        };

        IJsonValue instance = instanceType switch
        {
            "JsonElement" => global::Model.V3.Basictypes.FromJson(jsonElement),
            "dotnet" => global::Model.V3.Basictypes.FromJson(jsonElement).AsDotnetBackedValue(),
            _ => throw new InvalidOperationException($"Unknown instance type: {instanceType}"),
        };

        Corvus.Json.ValidationContext validationContext = instance.Validate(Corvus.Json.ValidationContext.ValidContext, validationLevel);

        Assert.AreEqual(valid, validationContext.IsValid);
        Assert.AreEqual(count, validationContext.Results.Count);
    }
}