// <copyright file="V3InteropTests.cs" company="Endjin Limited">
// Copyright (c) Endjin Limited. All rights reserved.
// </copyright>

#pragma warning disable SA1600 // Elements should be documented

using System.Text.Json;
using Corvus.Json;
using Xunit;

namespace Corvus.Json.Specs.Tests.JsonModel.V3Interop;

public class V3InteropTests
{
    [Theory]
    [InlineData("\"\"", false, "Flag", 0, "JsonElement")]
    [InlineData("\"\"", false, "Basic", 1, "JsonElement")]
    [InlineData("\"\"", false, "Detailed", 1, "JsonElement")]
    [InlineData("\"\"", false, "Verbose", 210, "JsonElement")]
    [InlineData("\"foo\"", false, "Flag", 0, "JsonElement")]
    [InlineData("\"foo\"", false, "Basic", 1, "JsonElement")]
    [InlineData("\"foo\"", false, "Detailed", 1, "JsonElement")]
    [InlineData("\"foo\"", false, "Verbose", 211, "JsonElement")]
    [InlineData("\"#\\\\foor\\\\bar\"", false, "Flag", 0, "JsonElement")]
    [InlineData("\"#\\\\foor\\\\bar\"", false, "Basic", 1, "JsonElement")]
    [InlineData("\"#\\\\foor\\\\bar\"", false, "Detailed", 1, "JsonElement")]
    [InlineData("\"#\\\\foor\\\\bar\"", false, "Verbose", 209, "JsonElement")]
    [InlineData("\"01234567890123456789012345678901234567890123456789\"", false, "Flag", 0, "JsonElement")]
    [InlineData("\"01234567890123456789012345678901234567890123456789\"", false, "Basic", 1, "JsonElement")]
    [InlineData("\"01234567890123456789012345678901234567890123456789\"", false, "Detailed", 1, "JsonElement")]
    [InlineData("\"01234567890123456789012345678901234567890123456789\"", false, "Verbose", 211, "JsonElement")]
    [InlineData("\"1\"", false, "Flag", 0, "JsonElement")]
    [InlineData("\"2\"", false, "Flag", 0, "JsonElement")]
    [InlineData("\"3\"", false, "Flag", 0, "JsonElement")]
    [InlineData("\"4\"", false, "Flag", 0, "JsonElement")]
    [InlineData("\"5\"", false, "Flag", 0, "JsonElement")]
    [InlineData("\"6\"", false, "Flag", 0, "JsonElement")]
    [InlineData("\"7\"", false, "Flag", 0, "JsonElement")]
    [InlineData("\"8\"", false, "Flag", 0, "JsonElement")]
    [InlineData("\"1\"", false, "Basic", 1, "JsonElement")]
    [InlineData("\"2\"", false, "Basic", 1, "JsonElement")]
    [InlineData("\"3\"", false, "Basic", 1, "JsonElement")]
    [InlineData("\"4\"", false, "Basic", 1, "JsonElement")]
    [InlineData("\"5\"", false, "Basic", 1, "JsonElement")]
    [InlineData("\"6\"", false, "Basic", 1, "JsonElement")]
    [InlineData("\"7\"", false, "Basic", 1, "JsonElement")]
    [InlineData("\"8\"", false, "Basic", 1, "JsonElement")]
    [InlineData("\"1\"", false, "Detailed", 1, "JsonElement")]
    [InlineData("\"2\"", false, "Detailed", 1, "JsonElement")]
    [InlineData("\"3\"", false, "Detailed", 1, "JsonElement")]
    [InlineData("\"4\"", false, "Detailed", 1, "JsonElement")]
    [InlineData("\"5\"", false, "Detailed", 1, "JsonElement")]
    [InlineData("\"6\"", false, "Detailed", 1, "JsonElement")]
    [InlineData("\"7\"", false, "Detailed", 1, "JsonElement")]
    [InlineData("\"8\"", false, "Detailed", 1, "JsonElement")]
    [InlineData("\"1\"", false, "Verbose", 211, "JsonElement")]
    [InlineData("\"2\"", false, "Verbose", 211, "JsonElement")]
    [InlineData("\"3\"", false, "Verbose", 211, "JsonElement")]
    [InlineData("\"4\"", false, "Verbose", 211, "JsonElement")]
    [InlineData("\"5\"", false, "Verbose", 211, "JsonElement")]
    [InlineData("\"6\"", false, "Verbose", 211, "JsonElement")]
    [InlineData("\"7\"", false, "Verbose", 211, "JsonElement")]
    [InlineData("\"8\"", false, "Verbose", 211, "JsonElement")]
    [InlineData("null", false, "Flag", 0, "JsonElement")]
    [InlineData("null", false, "Basic", 1, "JsonElement")]
    [InlineData("null", false, "Detailed", 1, "JsonElement")]
    [InlineData("null", false, "Verbose", 179, "JsonElement")]
    [InlineData("-1", false, "Flag", 0, "JsonElement")]
    [InlineData("0", false, "Flag", 0, "JsonElement")]
    [InlineData("1", false, "Flag", 0, "JsonElement")]
    [InlineData("256", false, "Flag", 0, "JsonElement")]
    [InlineData("-256", false, "Flag", 0, "JsonElement")]
    [InlineData("256.1", false, "Flag", 0, "JsonElement")]
    [InlineData("-256.1", false, "Flag", 0, "JsonElement")]
    [InlineData("-32769", false, "Flag", 0, "JsonElement")]
    [InlineData("32769", false, "Flag", 0, "JsonElement")]
    [InlineData("-32769.1", false, "Flag", 0, "JsonElement")]
    [InlineData("32769.1", false, "Flag", 0, "JsonElement")]
    [InlineData("-65536", false, "Flag", 0, "JsonElement")]
    [InlineData("65536", false, "Flag", 0, "JsonElement")]
    [InlineData("-65536.1", false, "Flag", 0, "JsonElement")]
    [InlineData("65536.1", false, "Flag", 0, "JsonElement")]
    [InlineData("-2147483648", false, "Flag", 0, "JsonElement")]
    [InlineData("2147483648", false, "Flag", 0, "JsonElement")]
    [InlineData("-2147483648.1", false, "Flag", 0, "JsonElement")]
    [InlineData("2147483648.1", false, "Flag", 0, "JsonElement")]
    [InlineData("true", false, "Flag", 0, "JsonElement")]
    [InlineData("[1,2,3]", false, "Flag", 0, "JsonElement")]
    [InlineData("{ \"foo\": \"bar\" }", true, "Flag", 0, "JsonElement")]
    [InlineData("-1", false, "Basic", 1, "JsonElement")]
    [InlineData("0", false, "Basic", 1, "JsonElement")]
    [InlineData("1", false, "Basic", 1, "JsonElement")]
    [InlineData("256", false, "Basic", 1, "JsonElement")]
    [InlineData("-256", false, "Basic", 1, "JsonElement")]
    [InlineData("256.1", false, "Basic", 1, "JsonElement")]
    [InlineData("-256.1", false, "Basic", 1, "JsonElement")]
    [InlineData("-32769", false, "Basic", 1, "JsonElement")]
    [InlineData("32769", false, "Basic", 1, "JsonElement")]
    [InlineData("-32769.1", false, "Basic", 1, "JsonElement")]
    [InlineData("32769.1", false, "Basic", 1, "JsonElement")]
    [InlineData("-65536", false, "Basic", 1, "JsonElement")]
    [InlineData("65536", false, "Basic", 1, "JsonElement")]
    [InlineData("-65536.1", false, "Basic", 1, "JsonElement")]
    [InlineData("65536.1", false, "Basic", 1, "JsonElement")]
    [InlineData("-2147483648", false, "Basic", 1, "JsonElement")]
    [InlineData("2147483648", false, "Basic", 1, "JsonElement")]
    [InlineData("-2147483648.1", false, "Basic", 1, "JsonElement")]
    [InlineData("2147483648.1", false, "Basic", 1, "JsonElement")]
    [InlineData("true", false, "Basic", 1, "JsonElement")]
    [InlineData("[1,2,3]", false, "Basic", 1, "JsonElement")]
    [InlineData("{ \"foo\": \"bar\" }", true, "Basic", 0, "JsonElement")]
    [InlineData("-1", false, "Detailed", 1, "JsonElement")]
    [InlineData("0", false, "Detailed", 1, "JsonElement")]
    [InlineData("1", false, "Detailed", 1, "JsonElement")]
    [InlineData("256", false, "Detailed", 1, "JsonElement")]
    [InlineData("-256", false, "Detailed", 1, "JsonElement")]
    [InlineData("256.1", false, "Detailed", 1, "JsonElement")]
    [InlineData("-256.1", false, "Detailed", 1, "JsonElement")]
    [InlineData("-32769", false, "Detailed", 1, "JsonElement")]
    [InlineData("32769", false, "Detailed", 1, "JsonElement")]
    [InlineData("-32769.1", false, "Detailed", 1, "JsonElement")]
    [InlineData("32769.1", false, "Detailed", 1, "JsonElement")]
    [InlineData("-65536", false, "Detailed", 1, "JsonElement")]
    [InlineData("65536", false, "Detailed", 1, "JsonElement")]
    [InlineData("-65536.1", false, "Detailed", 1, "JsonElement")]
    [InlineData("65536.1", false, "Detailed", 1, "JsonElement")]
    [InlineData("-2147483648", false, "Detailed", 1, "JsonElement")]
    [InlineData("2147483648", false, "Detailed", 1, "JsonElement")]
    [InlineData("-2147483648.1", false, "Detailed", 1, "JsonElement")]
    [InlineData("2147483648.1", false, "Detailed", 1, "JsonElement")]
    [InlineData("true", false, "Detailed", 1, "JsonElement")]
    [InlineData("[1,2,3]", false, "Detailed", 1, "JsonElement")]
    [InlineData("{ \"foo\": \"bar\" }", true, "Detailed", 0, "JsonElement")]
    [InlineData("-1", false, "Verbose", 203, "JsonElement")]
    [InlineData("0", false, "Verbose", 209, "JsonElement")]
    [InlineData("1", false, "Verbose", 209, "JsonElement")]
    [InlineData("256", false, "Verbose", 207, "JsonElement")]
    [InlineData("-256", false, "Verbose", 202, "JsonElement")]
    [InlineData("256.1", false, "Verbose", 198, "JsonElement")]
    [InlineData("-256.1", false, "Verbose", 198, "JsonElement")]
    [InlineData("-32769", false, "Verbose", 201, "JsonElement")]
    [InlineData("32769", false, "Verbose", 206, "JsonElement")]
    [InlineData("-32769.1", false, "Verbose", 198, "JsonElement")]
    [InlineData("32769.1", false, "Verbose", 198, "JsonElement")]
    [InlineData("-65536", false, "Verbose", 200, "JsonElement")]
    [InlineData("65536", false, "Verbose", 203, "JsonElement")]
    [InlineData("-65536.1", false, "Verbose", 197, "JsonElement")]
    [InlineData("65536.1", false, "Verbose", 197, "JsonElement")]
    [InlineData("-2147483648", false, "Verbose", 200, "JsonElement")]
    [InlineData("2147483648", false, "Verbose", 202, "JsonElement")]
    [InlineData("-2147483648.1", false, "Verbose", 197, "JsonElement")]
    [InlineData("2147483648.1", false, "Verbose", 197, "JsonElement")]
    [InlineData("true", false, "Verbose", 179, "JsonElement")]
    [InlineData("[1,2,3]", false, "Verbose", 180, "JsonElement")]
    [InlineData("{ \"foo\": \"bar\" }", true, "Verbose", 179, "JsonElement")]
    [InlineData("\"\"", false, "Flag", 0, "dotnet")]
    [InlineData("\"\"", false, "Basic", 1, "dotnet")]
    [InlineData("\"\"", false, "Detailed", 1, "dotnet")]
    [InlineData("\"\"", false, "Verbose", 210, "dotnet")]
    [InlineData("\"foo\"", false, "Flag", 0, "dotnet")]
    [InlineData("\"foo\"", false, "Basic", 1, "dotnet")]
    [InlineData("\"foo\"", false, "Detailed", 1, "dotnet")]
    [InlineData("\"foo\"", false, "Verbose", 211, "dotnet")]
    [InlineData("\"01234567890123456789012345678901234567890123456789\"", false, "Flag", 0, "dotnet")]
    [InlineData("\"01234567890123456789012345678901234567890123456789\"", false, "Basic", 1, "dotnet")]
    [InlineData("\"01234567890123456789012345678901234567890123456789\"", false, "Detailed", 1, "dotnet")]
    [InlineData("\"01234567890123456789012345678901234567890123456789\"", false, "Verbose", 211, "dotnet")]
    [InlineData("\"#\\\\foo\\\\bar\"", false, "Flag", 0, "dotnet")]
    [InlineData("\"#\\\\foo\\\\bar\"", false, "Basic", 1, "dotnet")]
    [InlineData("\"#\\\\foo\\\\bar\"", false, "Detailed", 1, "dotnet")]
    [InlineData("\"#\\\\foo\\\\bar\"", false, "Verbose", 209, "dotnet")]
    [InlineData("\"1\"", false, "Flag", 0, "dotnet")]
    [InlineData("\"2\"", false, "Flag", 0, "dotnet")]
    [InlineData("\"3\"", false, "Flag", 0, "dotnet")]
    [InlineData("\"4\"", false, "Flag", 0, "dotnet")]
    [InlineData("\"5\"", false, "Flag", 0, "dotnet")]
    [InlineData("\"6\"", false, "Flag", 0, "dotnet")]
    [InlineData("\"7\"", false, "Flag", 0, "dotnet")]
    [InlineData("\"8\"", false, "Flag", 0, "dotnet")]
    [InlineData("\"1\"", false, "Basic", 1, "dotnet")]
    [InlineData("\"2\"", false, "Basic", 1, "dotnet")]
    [InlineData("\"3\"", false, "Basic", 1, "dotnet")]
    [InlineData("\"4\"", false, "Basic", 1, "dotnet")]
    [InlineData("\"5\"", false, "Basic", 1, "dotnet")]
    [InlineData("\"6\"", false, "Basic", 1, "dotnet")]
    [InlineData("\"7\"", false, "Basic", 1, "dotnet")]
    [InlineData("\"8\"", false, "Basic", 1, "dotnet")]
    [InlineData("\"1\"", false, "Detailed", 1, "dotnet")]
    [InlineData("\"2\"", false, "Detailed", 1, "dotnet")]
    [InlineData("\"3\"", false, "Detailed", 1, "dotnet")]
    [InlineData("\"4\"", false, "Detailed", 1, "dotnet")]
    [InlineData("\"5\"", false, "Detailed", 1, "dotnet")]
    [InlineData("\"6\"", false, "Detailed", 1, "dotnet")]
    [InlineData("\"7\"", false, "Detailed", 1, "dotnet")]
    [InlineData("\"8\"", false, "Detailed", 1, "dotnet")]
    [InlineData("\"1\"", false, "Verbose", 211, "dotnet")]
    [InlineData("\"2\"", false, "Verbose", 211, "dotnet")]
    [InlineData("\"3\"", false, "Verbose", 211, "dotnet")]
    [InlineData("\"4\"", false, "Verbose", 211, "dotnet")]
    [InlineData("\"5\"", false, "Verbose", 211, "dotnet")]
    [InlineData("\"6\"", false, "Verbose", 211, "dotnet")]
    [InlineData("\"7\"", false, "Verbose", 211, "dotnet")]
    [InlineData("\"8\"", false, "Verbose", 211, "dotnet")]
    [InlineData("null", false, "Flag", 0, "dotnet")]
    [InlineData("null", false, "Basic", 1, "dotnet")]
    [InlineData("null", false, "Detailed", 1, "dotnet")]
    [InlineData("null", false, "Verbose", 179, "dotnet")]
    [InlineData("-1", false, "Flag", 0, "dotnet")]
    [InlineData("0", false, "Flag", 0, "dotnet")]
    [InlineData("1", false, "Flag", 0, "dotnet")]
    [InlineData("256", false, "Flag", 0, "dotnet")]
    [InlineData("-256", false, "Flag", 0, "dotnet")]
    [InlineData("256.1", false, "Flag", 0, "dotnet")]
    [InlineData("-256.1", false, "Flag", 0, "dotnet")]
    [InlineData("-32769", false, "Flag", 0, "dotnet")]
    [InlineData("32769", false, "Flag", 0, "dotnet")]
    [InlineData("-32769.1", false, "Flag", 0, "dotnet")]
    [InlineData("32769.1", false, "Flag", 0, "dotnet")]
    [InlineData("-65536", false, "Flag", 0, "dotnet")]
    [InlineData("65536", false, "Flag", 0, "dotnet")]
    [InlineData("-65536.1", false, "Flag", 0, "dotnet")]
    [InlineData("65536.1", false, "Flag", 0, "dotnet")]
    [InlineData("-2147483648", false, "Flag", 0, "dotnet")]
    [InlineData("2147483648", false, "Flag", 0, "dotnet")]
    [InlineData("-2147483648.1", false, "Flag", 0, "dotnet")]
    [InlineData("2147483648.1", false, "Flag", 0, "dotnet")]
    [InlineData("true", false, "Flag", 0, "dotnet")]
    [InlineData("[1,2,3]", false, "Flag", 0, "dotnet")]
    [InlineData("{ \"foo\": \"bar\" }", true, "Flag", 0, "dotnet")]
    [InlineData("-1", false, "Basic", 1, "dotnet")]
    [InlineData("0", false, "Basic", 1, "dotnet")]
    [InlineData("1", false, "Basic", 1, "dotnet")]
    [InlineData("256", false, "Basic", 1, "dotnet")]
    [InlineData("-256", false, "Basic", 1, "dotnet")]
    [InlineData("256.1", false, "Basic", 1, "dotnet")]
    [InlineData("-256.1", false, "Basic", 1, "dotnet")]
    [InlineData("-32769", false, "Basic", 1, "dotnet")]
    [InlineData("32769", false, "Basic", 1, "dotnet")]
    [InlineData("-32769.1", false, "Basic", 1, "dotnet")]
    [InlineData("32769.1", false, "Basic", 1, "dotnet")]
    [InlineData("-65536", false, "Basic", 1, "dotnet")]
    [InlineData("65536", false, "Basic", 1, "dotnet")]
    [InlineData("-65536.1", false, "Basic", 1, "dotnet")]
    [InlineData("65536.1", false, "Basic", 1, "dotnet")]
    [InlineData("-2147483648", false, "Basic", 1, "dotnet")]
    [InlineData("2147483648", false, "Basic", 1, "dotnet")]
    [InlineData("-2147483648.1", false, "Basic", 1, "dotnet")]
    [InlineData("2147483648.1", false, "Basic", 1, "dotnet")]
    [InlineData("true", false, "Basic", 1, "dotnet")]
    [InlineData("[1,2,3]", false, "Basic", 1, "dotnet")]
    [InlineData("{ \"foo\": \"bar\" }", true, "Basic", 0, "dotnet")]
    [InlineData("-1", false, "Detailed", 1, "dotnet")]
    [InlineData("0", false, "Detailed", 1, "dotnet")]
    [InlineData("1", false, "Detailed", 1, "dotnet")]
    [InlineData("256", false, "Detailed", 1, "dotnet")]
    [InlineData("-256", false, "Detailed", 1, "dotnet")]
    [InlineData("256.1", false, "Detailed", 1, "dotnet")]
    [InlineData("-256.1", false, "Detailed", 1, "dotnet")]
    [InlineData("-32769", false, "Detailed", 1, "dotnet")]
    [InlineData("32769", false, "Detailed", 1, "dotnet")]
    [InlineData("-32769.1", false, "Detailed", 1, "dotnet")]
    [InlineData("32769.1", false, "Detailed", 1, "dotnet")]
    [InlineData("-65536", false, "Detailed", 1, "dotnet")]
    [InlineData("65536", false, "Detailed", 1, "dotnet")]
    [InlineData("-65536.1", false, "Detailed", 1, "dotnet")]
    [InlineData("65536.1", false, "Detailed", 1, "dotnet")]
    [InlineData("-2147483648", false, "Detailed", 1, "dotnet")]
    [InlineData("2147483648", false, "Detailed", 1, "dotnet")]
    [InlineData("-2147483648.1", false, "Detailed", 1, "dotnet")]
    [InlineData("2147483648.1", false, "Detailed", 1, "dotnet")]
    [InlineData("true", false, "Detailed", 1, "dotnet")]
    [InlineData("[1,2,3]", false, "Detailed", 1, "dotnet")]
    [InlineData("{ \"foo\": \"bar\" }", true, "Detailed", 0, "dotnet")]
    [InlineData("-1", false, "Verbose", 203, "dotnet")]
    [InlineData("0", false, "Verbose", 209, "dotnet")]
    [InlineData("1", false, "Verbose", 209, "dotnet")]
    [InlineData("256", false, "Verbose", 207, "dotnet")]
    [InlineData("-256", false, "Verbose", 202, "dotnet")]
    [InlineData("256.1", false, "Verbose", 198, "dotnet")]
    [InlineData("-256.1", false, "Verbose", 198, "dotnet")]
    [InlineData("-32769", false, "Verbose", 201, "dotnet")]
    [InlineData("32769", false, "Verbose", 206, "dotnet")]
    [InlineData("-32769.1", false, "Verbose", 198, "dotnet")]
    [InlineData("32769.1", false, "Verbose", 198, "dotnet")]
    [InlineData("-65536", false, "Verbose", 200, "dotnet")]
    [InlineData("65536", false, "Verbose", 203, "dotnet")]
    [InlineData("-65536.1", false, "Verbose", 197, "dotnet")]
    [InlineData("65536.1", false, "Verbose", 197, "dotnet")]
    [InlineData("-2147483648", false, "Verbose", 200, "dotnet")]
    [InlineData("2147483648", false, "Verbose", 202, "dotnet")]
    [InlineData("-2147483648.1", false, "Verbose", 197, "dotnet")]
    [InlineData("2147483648.1", false, "Verbose", 197, "dotnet")]
    [InlineData("true", false, "Verbose", 179, "dotnet")]
    [InlineData("[1,2,3]", false, "Verbose", 180, "dotnet")]
    [InlineData("{ \"foo\": \"bar\" }", true, "Verbose", 179, "dotnet")]
    public void ValidateV3Model(string inputData, bool valid, string level, int count, string instanceType)
    {
        using var doc = JsonDocument.Parse(inputData);
        JsonElement jsonElement = doc.RootElement.Clone();

        Corvus.Json.ValidationLevel validationLevel = level switch
        {
            "Flag" => Corvus.Json.ValidationLevel.Flag,
            "Basic" => Corvus.Json.ValidationLevel.Basic,
            "Detailed" => Corvus.Json.ValidationLevel.Detailed,
            "Verbose" => Corvus.Json.ValidationLevel.Verbose,
            _ => throw new InvalidOperationException($"Unknown validation level: {level}"),
        };

        IJsonValue instance = instanceType switch
        {
            "JsonElement" => global::Model.V3.Basictypes.FromJson(jsonElement),
            "dotnet" => global::Model.V3.Basictypes.FromJson(jsonElement).AsDotnetBackedValue(),
            _ => throw new InvalidOperationException($"Unknown instance type: {instanceType}"),
        };

        Corvus.Json.ValidationContext validationContext = instance.Validate(Corvus.Json.ValidationContext.ValidContext, validationLevel);

        Assert.Equal(valid, validationContext.IsValid);
        Assert.Equal(count, validationContext.Results.Count);
    }
}