// <copyright file="JMESPathCodeGenerator.cs" company="Endjin Limited">
// Copyright (c) Endjin Limited. All rights reserved.
// </copyright>

using System.Text;
using Corvus.Text.Json.JMESPath;

namespace Corvus.Text.Json.JMESPath.CodeGeneration;

/// <summary>
/// Generates static C# evaluation code from a JMESPath expression string.
/// </summary>
/// <remarks>
/// <para>
/// The generator walks the JMESPath AST and emits inline C# code that calls
/// <c>JMESPathCodeGenHelpers</c> methods. All JMESPath constructs are supported
/// directly — there is no runtime fallback.
/// </para>
/// </remarks>
public static class JMESPathCodeGenerator
{
    private const string H = "JMESPathCodeGenHelpers";

    /// <summary>
    /// Generates a complete C# source file containing a static class with an
    /// <c>Evaluate</c> method that evaluates the given JMESPath expression.
    /// </summary>
    /// <param name="expression">The JMESPath expression string.</param>
    /// <param name="className">The name of the generated static class.</param>
    /// <param name="namespaceName">The namespace for the generated class.</param>
    /// <param name="accessibility">The accessibility modifier (e.g. <c>"internal"</c> or <c>"public"</c>).</param>
    /// <param name="isPartial">Whether to emit the <c>partial</c> modifier on the class.</param>
    /// <returns>A complete C# source file as a string.</returns>
    /// <exception cref="JMESPathException">
    /// Thrown if <paramref name="expression"/> is not a valid JMESPath expression.
    /// </exception>
    public static string Generate(
        string expression,
        string className,
        string namespaceName,
        string accessibility = "internal",
        bool isPartial = false)
    {
        byte[] utf8 = Encoding.UTF8.GetBytes(expression);
        JMESPathNode ast = Parser.Parse(utf8);

        Emitter emitter = new();
        StringBuilder body = new(4096);

        string resultVar = emitter.EmitExpression(body, ast, "        ", "data");

        StringBuilder sb = new(8192);
        L(sb, "", "// <auto-generated/>");
        L(sb, "", "#nullable enable");
        L(sb, "", "using System;");
        L(sb, "", "using Corvus.Text.Json;");
        L(sb, "", "using Corvus.Text.Json.JMESPath;");
        Blank(sb);
        L(sb, "", $"namespace {namespaceName};");
        Blank(sb);

        string partialKeyword = isPartial ? " partial" : string.Empty;
        L(sb, "", $"{accessibility} static{partialKeyword} class {className}");
        L(sb, "", "{");

        // Emit static literal fields inside the class
        if (emitter.StaticFields.Count > 0)
        {
            L(sb, "", $"#pragma warning disable SA1306");
            L(sb, "", $"#pragma warning disable SA1311");
            foreach ((string fieldName, string literal) in emitter.StaticFields)
            {
                L(sb, "    ", literal);
            }

            L(sb, "", $"#pragma warning restore SA1311");
            L(sb, "", $"#pragma warning restore SA1306");
            Blank(sb);
        }

        // Emit static name fields inside the class
        foreach ((string fieldName, string declaration) in emitter.NameFields)
        {
            L(sb, "    ", declaration);
        }

        if (emitter.NameFields.Count > 0)
        {
            Blank(sb);
        }

        // Emit Evaluate method
        L(sb, "    ", "public static JsonElement Evaluate(in JsonElement data, JsonWorkspace workspace)");
        L(sb, "    ", "{");
        sb.Append(body);
        L(sb, "        ", $"return {resultVar};");
        L(sb, "    ", "}");

        // Emit expression-ref helper methods
        foreach (string helperMethod in emitter.HelperMethods)
        {
            Blank(sb);
            sb.Append(helperMethod);
        }

        // Close class — no trailing newline (SA1518)
        sb.Append('}');

        return sb.ToString();
    }

    private static void L(StringBuilder sb, string indent, string line)
    {
        sb.Append(indent).Append(line).Append('\n');
    }

    private static void Blank(StringBuilder sb)
    {
        sb.Append('\n');
    }

    private static string Utf8Literal(byte[] bytes)
    {
        StringBuilder sb = new(bytes.Length * 4 + 4);
        sb.Append("new byte[] { ");
        for (int i = 0; i < bytes.Length; i++)
        {
            if (i > 0)
            {
                sb.Append(", ");
            }

            sb.Append("0x");
            sb.Append(bytes[i].ToString("X2"));
        }

        sb.Append(" }");
        return sb.ToString();
    }

    private static string EscapeStringLiteral(string value)
    {
        StringBuilder sb = new(value.Length + 4);
        foreach (char ch in value)
        {
            switch (ch)
            {
                case '"': sb.Append("\\\""); break;
                case '\\': sb.Append("\\\\"); break;
                case '\n': sb.Append("\\n"); break;
                case '\r': sb.Append("\\r"); break;
                case '\t': sb.Append("\\t"); break;
                case '\0': sb.Append("\\0"); break;
                default:
                    if (ch < 0x20)
                    {
                        sb.Append($"\\u{(int)ch:X4}");
                    }
                    else
                    {
                        sb.Append(ch);
                    }

                    break;
            }
        }

        return sb.ToString();
    }

    /// <summary>
    /// Walks the JMESPath AST and emits C# code into a StringBuilder.
    /// Each call to <see cref="EmitExpression"/> appends code to the body
    /// and returns the name of the variable holding the result.
    /// </summary>
    private sealed class Emitter
    {
        private int varCounter;
        private int nameCounter;
        private int literalCounter;
        private int exprRefCounter;

        public List<(string FieldName, string Declaration)> StaticFields { get; } = [];

        public List<(string FieldName, string Declaration)> NameFields { get; } = [];

        public List<string> HelperMethods { get; } = [];

        public string EmitExpression(StringBuilder body, JMESPathNode node, string indent, string inputVar)
        {
            return node switch
            {
                CurrentNode => inputVar,
                IdentifierNode id => EmitIdentifier(body, id, indent, inputVar),
                RawStringNode raw => EmitRawString(body, raw, indent),
                LiteralNode lit => EmitLiteral(body, lit, indent),
                SubExpressionNode sub => EmitSubExpression(body, sub, indent, inputVar),
                IndexNode idx => EmitIndex(body, idx, indent, inputVar),
                SliceNode sl => EmitSlice(body, sl, indent, inputVar),
                PipeNode pipe => EmitPipe(body, pipe, indent, inputVar),
                OrNode or => EmitOr(body, or, indent, inputVar),
                AndNode and => EmitAnd(body, and, indent, inputVar),
                NotNode not => EmitNot(body, not, indent, inputVar),
                ComparisonNode cmp => EmitComparison(body, cmp, indent, inputVar),
                MultiSelectListNode msl => EmitMultiSelectList(body, msl, indent, inputVar),
                MultiSelectHashNode msh => EmitMultiSelectHash(body, msh, indent, inputVar),
                ListProjectionNode lp => EmitListProjection(body, lp, indent, inputVar),
                ValueProjectionNode vp => EmitValueProjection(body, vp, indent, inputVar),
                FlattenProjectionNode fp => EmitFlattenProjection(body, fp, indent, inputVar),
                FilterProjectionNode filt => EmitFilterProjection(body, filt, indent, inputVar),
                FunctionCallNode fn => EmitFunctionCall(body, fn, indent, inputVar),
                ExpressionRefNode => throw new JMESPathException("Expression references (&expr) cannot appear at the top level."),
                _ => throw new JMESPathException($"Unsupported AST node type: {node.GetType().Name}."),
            };
        }

        private string NextVar() => $"v{varCounter++}";

        private string EmitIdentifier(StringBuilder body, IdentifierNode node, string indent, string inputVar)
        {
            string resultVar = NextVar();
            string nameField = $"s_name{nameCounter++}";
            string nameStr = Encoding.UTF8.GetString(node.Name);

            NameFields.Add((nameField, $"private static readonly byte[] {nameField} = {Utf8Literal(node.Name)};"));

            L(body, indent, $"JsonElement {resultVar} = default;");
            L(body, indent, $"if ({inputVar}.ValueKind == JsonValueKind.Object)");
            L(body, indent, "{");
            L(body, indent, $"    {inputVar}.TryGetProperty({nameField}, out {resultVar});");
            L(body, indent, "}");
            Blank(body);

            return resultVar;
        }

        private string EmitRawString(StringBuilder body, RawStringNode node, string indent)
        {
            string resultVar = NextVar();
            string fieldName = $"s_literal{literalCounter++}";
            string escaped = EscapeStringLiteral(Encoding.UTF8.GetString(node.Value));
            string jsonEscaped = EscapeStringLiteral($"\"{Encoding.UTF8.GetString(node.Value)}\"");

            // Use the helper to create the element statically
            StaticFields.Add((fieldName, $"private static readonly JsonElement {fieldName} = {H}.StringToElement(\"{escaped}\");"));

            L(body, indent, $"JsonElement {resultVar} = {fieldName};");
            return resultVar;
        }

        private string EmitLiteral(StringBuilder body, LiteralNode node, string indent)
        {
            string resultVar = NextVar();
            string fieldName = $"s_literal{literalCounter++}";
            StaticFields.Add((fieldName, $"private static readonly JsonElement {fieldName} = JsonElement.ParseValue({Utf8Literal(node.JsonValue)});"));

            L(body, indent, $"JsonElement {resultVar} = {fieldName};");
            return resultVar;
        }

        private string EmitSubExpression(StringBuilder body, SubExpressionNode node, string indent, string inputVar)
        {
            string leftVar = EmitExpression(body, node.Left, indent, inputVar);
            string resultVar = NextVar();
            L(body, indent, $"JsonElement {resultVar} = default;");
            L(body, indent, $"if (!{leftVar}.IsNullOrUndefined())");
            L(body, indent, "{");
            string rightVar = EmitExpression(body, node.Right, indent + "    ", leftVar);
            L(body, indent, $"    {resultVar} = {rightVar};");
            L(body, indent, "}");
            Blank(body);
            return resultVar;
        }

        private string EmitIndex(StringBuilder body, IndexNode node, string indent, string inputVar)
        {
            string resultVar = NextVar();
            int index = node.Index;
            L(body, indent, $"JsonElement {resultVar} = default;");
            L(body, indent, $"if ({inputVar}.ValueKind == JsonValueKind.Array)");
            L(body, indent, "{");
            L(body, indent, $"    int len_{resultVar} = {inputVar}.GetArrayLength();");
            if (index < 0)
            {
                L(body, indent, $"    int idx_{resultVar} = len_{resultVar} + ({index});");
            }
            else
            {
                L(body, indent, $"    int idx_{resultVar} = {index};");
            }

            L(body, indent, $"    if (idx_{resultVar} >= 0 && idx_{resultVar} < len_{resultVar})");
            L(body, indent, "    {");
            L(body, indent, $"        {resultVar} = {inputVar}[idx_{resultVar}];");
            L(body, indent, "    }");
            L(body, indent, "}");
            Blank(body);
            return resultVar;
        }

        private string EmitSlice(StringBuilder body, SliceNode node, string indent, string inputVar)
        {
            string resultVar = NextVar();
            string startVal = node.Start.HasValue ? node.Start.Value.ToString() : "null";
            string stopVal = node.Stop.HasValue ? node.Stop.Value.ToString() : "null";
            string stepVal = node.Step.HasValue ? node.Step.Value.ToString() : "1";

            L(body, indent, $"JsonElement {resultVar} = default;");
            L(body, indent, $"if ({inputVar}.ValueKind == JsonValueKind.Array)");
            L(body, indent, "{");
            L(body, indent, $"    int len_{resultVar} = {inputVar}.GetArrayLength();");
            L(body, indent, $"    int step_{resultVar} = {stepVal};");

            if (node.Step.HasValue && node.Step.Value == 0)
            {
                L(body, indent, $"    throw new JMESPathException(\"Slice step cannot be 0.\");");
            }
            else
            {
                // Positive step defaults
                L(body, indent, $"    int start_{resultVar};");
                L(body, indent, $"    int stop_{resultVar};");
                L(body, indent, $"    if (step_{resultVar} > 0)");
                L(body, indent, "    {");
                if (node.Start.HasValue)
                {
                    L(body, indent, $"        start_{resultVar} = {H}.NormalizeSliceIndex({node.Start.Value}, len_{resultVar}, true, true);");
                }
                else
                {
                    L(body, indent, $"        start_{resultVar} = 0;");
                }

                if (node.Stop.HasValue)
                {
                    L(body, indent, $"        stop_{resultVar} = {H}.NormalizeSliceIndex({node.Stop.Value}, len_{resultVar}, false, true);");
                }
                else
                {
                    L(body, indent, $"        stop_{resultVar} = len_{resultVar};");
                }

                L(body, indent, "    }");
                L(body, indent, "    else");
                L(body, indent, "    {");
                if (node.Start.HasValue)
                {
                    L(body, indent, $"        start_{resultVar} = {H}.NormalizeSliceIndex({node.Start.Value}, len_{resultVar}, true, false);");
                }
                else
                {
                    L(body, indent, $"        start_{resultVar} = len_{resultVar} - 1;");
                }

                if (node.Stop.HasValue)
                {
                    L(body, indent, $"        stop_{resultVar} = {H}.NormalizeSliceIndex({node.Stop.Value}, len_{resultVar}, false, false);");
                }
                else
                {
                    L(body, indent, $"        stop_{resultVar} = -1;");
                }

                L(body, indent, "    }");

                L(body, indent, $"    var doc_{resultVar} = JsonElement.CreateArrayBuilder(workspace, len_{resultVar});");
                L(body, indent, $"    var root_{resultVar} = doc_{resultVar}.RootElement;");
                L(body, indent, $"    if (step_{resultVar} > 0)");
                L(body, indent, "    {");
                L(body, indent, $"        for (int i_{resultVar} = start_{resultVar}; i_{resultVar} < stop_{resultVar}; i_{resultVar} += step_{resultVar})");
                L(body, indent, "        {");
                L(body, indent, $"            root_{resultVar}.AddItem({inputVar}[i_{resultVar}]);");
                L(body, indent, "        }");
                L(body, indent, "    }");
                L(body, indent, "    else");
                L(body, indent, "    {");
                L(body, indent, $"        for (int i_{resultVar} = start_{resultVar}; i_{resultVar} > stop_{resultVar}; i_{resultVar} += step_{resultVar})");
                L(body, indent, "        {");
                L(body, indent, $"            root_{resultVar}.AddItem({inputVar}[i_{resultVar}]);");
                L(body, indent, "        }");
                L(body, indent, "    }");

                L(body, indent, $"    {resultVar} = (JsonElement)root_{resultVar};");
            }

            L(body, indent, "}");
            Blank(body);
            return resultVar;
        }

        private string EmitPipe(StringBuilder body, PipeNode node, string indent, string inputVar)
        {
            string leftVar = EmitExpression(body, node.Left, indent, inputVar);
            return EmitExpression(body, node.Right, indent, leftVar);
        }

        private string EmitOr(StringBuilder body, OrNode node, string indent, string inputVar)
        {
            string leftVar = EmitExpression(body, node.Left, indent, inputVar);
            string resultVar = NextVar();
            L(body, indent, $"JsonElement {resultVar};");
            L(body, indent, $"if ({H}.IsTruthy({leftVar}))");
            L(body, indent, "{");
            L(body, indent, $"    {resultVar} = {leftVar};");
            L(body, indent, "}");
            L(body, indent, "else");
            L(body, indent, "{");
            string rightVar = EmitExpression(body, node.Right, indent + "    ", inputVar);
            L(body, indent, $"    {resultVar} = {rightVar};");
            L(body, indent, "}");
            Blank(body);
            return resultVar;
        }

        private string EmitAnd(StringBuilder body, AndNode node, string indent, string inputVar)
        {
            string leftVar = EmitExpression(body, node.Left, indent, inputVar);
            string resultVar = NextVar();
            L(body, indent, $"JsonElement {resultVar};");
            L(body, indent, $"if (!{H}.IsTruthy({leftVar}))");
            L(body, indent, "{");
            L(body, indent, $"    {resultVar} = {leftVar};");
            L(body, indent, "}");
            L(body, indent, "else");
            L(body, indent, "{");
            string rightVar = EmitExpression(body, node.Right, indent + "    ", inputVar);
            L(body, indent, $"    {resultVar} = {rightVar};");
            L(body, indent, "}");
            Blank(body);
            return resultVar;
        }

        private string EmitNot(StringBuilder body, NotNode node, string indent, string inputVar)
        {
            string exprVar = EmitExpression(body, node.Expression, indent, inputVar);
            string resultVar = NextVar();
            L(body, indent, $"JsonElement {resultVar} = {H}.IsTruthy({exprVar}) ? {H}.FalseElement : {H}.TrueElement;");
            return resultVar;
        }

        private string EmitComparison(StringBuilder body, ComparisonNode node, string indent, string inputVar)
        {
            string leftVar = EmitExpression(body, node.Left, indent, inputVar);
            string rightVar = EmitExpression(body, node.Right, indent, inputVar);
            string resultVar = NextVar();

            if (node.Operator == CompareOp.Equal)
            {
                L(body, indent, $"JsonElement {resultVar} = {H}.BoolElement({H}.DeepEquals({leftVar}, {rightVar}));");
            }
            else if (node.Operator == CompareOp.NotEqual)
            {
                L(body, indent, $"JsonElement {resultVar} = {H}.BoolElement(!{H}.DeepEquals({leftVar}, {rightVar}));");
            }
            else
            {
                // Ordering comparison — both must be numbers
                string cmpOp = node.Operator switch
                {
                    CompareOp.LessThan => "<",
                    CompareOp.LessThanOrEqual => "<=",
                    CompareOp.GreaterThan => ">",
                    CompareOp.GreaterThanOrEqual => ">=",
                    _ => "==",
                };

                L(body, indent, $"JsonElement {resultVar} = default;");
                L(body, indent, $"if ({leftVar}.ValueKind == JsonValueKind.Number && {rightVar}.ValueKind == JsonValueKind.Number)");
                L(body, indent, "{");
                L(body, indent, $"    {resultVar} = {H}.BoolElement({leftVar}.GetDouble() {cmpOp} {rightVar}.GetDouble());");
                L(body, indent, "}");
                Blank(body);
            }

            return resultVar;
        }

        private string EmitMultiSelectList(StringBuilder body, MultiSelectListNode node, string indent, string inputVar)
        {
            string resultVar = NextVar();
            L(body, indent, $"JsonElement {resultVar} = default;");
            L(body, indent, $"if (!{inputVar}.IsNullOrUndefined())");
            L(body, indent, "{");

            string innerIndent = indent + "    ";
            L(body, innerIndent, $"var doc_{resultVar} = JsonElement.CreateArrayBuilder(workspace, {node.Expressions.Length});");
            L(body, innerIndent, $"var root_{resultVar} = doc_{resultVar}.RootElement;");
            for (int i = 0; i < node.Expressions.Length; i++)
            {
                string exprVar = EmitExpression(body, node.Expressions[i], innerIndent, inputVar);
                L(body, innerIndent, $"root_{resultVar}.AddItem({exprVar}.IsNullOrUndefined() ? {H}.NullElement : {exprVar});");
            }

            L(body, innerIndent, $"{resultVar} = (JsonElement)root_{resultVar};");
            L(body, indent, "}");
            Blank(body);
            return resultVar;
        }

        private string EmitMultiSelectHash(StringBuilder body, MultiSelectHashNode node, string indent, string inputVar)
        {
            string resultVar = NextVar();
            L(body, indent, $"JsonElement {resultVar} = default;");
            L(body, indent, $"if (!{inputVar}.IsNullOrUndefined())");
            L(body, indent, "{");

            string innerIndent = indent + "    ";
            L(body, innerIndent, $"var doc_{resultVar} = JsonElement.CreateObjectBuilder(workspace, {node.Pairs.Length});");
            L(body, innerIndent, $"var root_{resultVar} = doc_{resultVar}.RootElement;");

            for (int i = 0; i < node.Pairs.Length; i++)
            {
                MultiSelectHashNode.KeyValuePair pair = node.Pairs[i];
                string keyField = $"s_name{nameCounter++}";
                NameFields.Add((keyField, $"private static readonly byte[] {keyField} = {Utf8Literal(pair.Key)};"));

                string valVar = EmitExpression(body, pair.Value, innerIndent, inputVar);
                L(body, innerIndent, $"root_{resultVar}.SetProperty({keyField}, {valVar}.IsNullOrUndefined() ? {H}.NullElement : {valVar});");
            }

            L(body, innerIndent, $"{resultVar} = (JsonElement)root_{resultVar};");
            L(body, indent, "}");
            Blank(body);
            return resultVar;
        }

        private string EmitListProjection(StringBuilder body, ListProjectionNode node, string indent, string inputVar)
        {
            string leftVar = EmitExpression(body, node.Left, indent, inputVar);
            string resultVar = NextVar();
            L(body, indent, $"JsonElement {resultVar} = default;");
            L(body, indent, $"if ({leftVar}.ValueKind == JsonValueKind.Array)");
            L(body, indent, "{");

            string innerIndent = indent + "    ";
            L(body, innerIndent, $"int len_{resultVar} = {leftVar}.GetArrayLength();");
            L(body, innerIndent, $"if (len_{resultVar} == 0)");
            L(body, innerIndent, "{");
            L(body, innerIndent, $"    {resultVar} = {leftVar};");
            L(body, innerIndent, "}");
            L(body, innerIndent, "else");
            L(body, innerIndent, "{");

            string loopIndent = innerIndent + "    ";
            string itemVar = $"item_{resultVar}";
            L(body, loopIndent, $"var doc_{resultVar} = JsonElement.CreateArrayBuilder(workspace, len_{resultVar});");
            L(body, loopIndent, $"var root_{resultVar} = doc_{resultVar}.RootElement;");
            L(body, loopIndent, $"foreach (JsonElement {itemVar} in {leftVar}.EnumerateArray())");
            L(body, loopIndent, "{");
            string projectedVar = EmitExpression(body, node.Right, loopIndent + "    ", itemVar);
            L(body, loopIndent, $"    if (!{projectedVar}.IsNullOrUndefined())");
            L(body, loopIndent, "    {");
            L(body, loopIndent, $"        root_{resultVar}.AddItem({projectedVar});");
            L(body, loopIndent, "    }");
            L(body, loopIndent, "}");
            L(body, loopIndent, $"{resultVar} = (JsonElement)root_{resultVar};");
            L(body, innerIndent, "}");

            L(body, indent, "}");
            Blank(body);
            return resultVar;
        }

        private string EmitValueProjection(StringBuilder body, ValueProjectionNode node, string indent, string inputVar)
        {
            string leftVar = EmitExpression(body, node.Left, indent, inputVar);
            string resultVar = NextVar();
            L(body, indent, $"JsonElement {resultVar} = default;");
            L(body, indent, $"if ({leftVar}.ValueKind == JsonValueKind.Object)");
            L(body, indent, "{");

            string innerIndent = indent + "    ";
            string propVar = $"prop_{resultVar}";
            L(body, innerIndent, $"int count_{resultVar} = {leftVar}.GetPropertyCount();");
            L(body, innerIndent, $"var doc_{resultVar} = JsonElement.CreateArrayBuilder(workspace, count_{resultVar});");
            L(body, innerIndent, $"var root_{resultVar} = doc_{resultVar}.RootElement;");
            L(body, innerIndent, $"foreach (JsonProperty<JsonElement> {propVar} in {leftVar}.EnumerateObject())");
            L(body, innerIndent, "{");
            string projectedVar = EmitExpression(body, node.Right, innerIndent + "    ", $"{propVar}.Value");
            L(body, innerIndent, $"    if (!{projectedVar}.IsNullOrUndefined())");
            L(body, innerIndent, "    {");
            L(body, innerIndent, $"        root_{resultVar}.AddItem({projectedVar});");
            L(body, innerIndent, "    }");
            L(body, innerIndent, "}");
            L(body, innerIndent, $"{resultVar} = (JsonElement)root_{resultVar};");

            L(body, indent, "}");
            Blank(body);
            return resultVar;
        }

        private string EmitFlattenProjection(StringBuilder body, FlattenProjectionNode node, string indent, string inputVar)
        {
            string leftVar = EmitExpression(body, node.Left, indent, inputVar);
            string resultVar = NextVar();
            L(body, indent, $"JsonElement {resultVar} = default;");
            L(body, indent, $"if ({leftVar}.ValueKind == JsonValueKind.Array)");
            L(body, indent, "{");

            string innerIndent = indent + "    ";
            string flatVar = $"flat_{resultVar}";
            L(body, innerIndent, $"var flatDoc_{resultVar} = JsonElement.CreateArrayBuilder(workspace, {leftVar}.GetArrayLength());");
            L(body, innerIndent, $"var flatRoot_{resultVar} = flatDoc_{resultVar}.RootElement;");
            L(body, innerIndent, $"foreach (JsonElement flatItem_{resultVar} in {leftVar}.EnumerateArray())");
            L(body, innerIndent, "{");
            L(body, innerIndent, $"    if (flatItem_{resultVar}.ValueKind == JsonValueKind.Array)");
            L(body, innerIndent, "    {");
            L(body, innerIndent, $"        foreach (JsonElement nested_{resultVar} in flatItem_{resultVar}.EnumerateArray())");
            L(body, innerIndent, "        {");
            L(body, innerIndent, $"            flatRoot_{resultVar}.AddItem(nested_{resultVar});");
            L(body, innerIndent, "        }");
            L(body, innerIndent, "    }");
            L(body, innerIndent, "    else");
            L(body, innerIndent, "    {");
            L(body, innerIndent, $"        flatRoot_{resultVar}.AddItem(flatItem_{resultVar});");
            L(body, innerIndent, "    }");
            L(body, innerIndent, "}");
            L(body, innerIndent, $"JsonElement {flatVar} = (JsonElement)flatRoot_{resultVar};");

            // Now project onto the flattened array
            L(body, innerIndent, $"int len_{resultVar} = {flatVar}.GetArrayLength();");
            L(body, innerIndent, $"if (len_{resultVar} == 0)");
            L(body, innerIndent, "{");
            L(body, innerIndent, $"    {resultVar} = {flatVar};");
            L(body, innerIndent, "}");
            L(body, innerIndent, "else");
            L(body, innerIndent, "{");

            string loopIndent = innerIndent + "    ";
            string itemVar = $"item_{resultVar}";
            L(body, loopIndent, $"var doc_{resultVar} = JsonElement.CreateArrayBuilder(workspace, len_{resultVar});");
            L(body, loopIndent, $"var root_{resultVar} = doc_{resultVar}.RootElement;");
            L(body, loopIndent, $"foreach (JsonElement {itemVar} in {flatVar}.EnumerateArray())");
            L(body, loopIndent, "{");
            string projectedVar = EmitExpression(body, node.Right, loopIndent + "    ", itemVar);
            L(body, loopIndent, $"    if (!{projectedVar}.IsNullOrUndefined())");
            L(body, loopIndent, "    {");
            L(body, loopIndent, $"        root_{resultVar}.AddItem({projectedVar});");
            L(body, loopIndent, "    }");
            L(body, loopIndent, "}");
            L(body, loopIndent, $"{resultVar} = (JsonElement)root_{resultVar};");
            L(body, innerIndent, "}");

            L(body, indent, "}");
            Blank(body);
            return resultVar;
        }

        private string EmitFilterProjection(StringBuilder body, FilterProjectionNode node, string indent, string inputVar)
        {
            string leftVar = EmitExpression(body, node.Left, indent, inputVar);
            string resultVar = NextVar();
            L(body, indent, $"JsonElement {resultVar} = default;");
            L(body, indent, $"if ({leftVar}.ValueKind == JsonValueKind.Array)");
            L(body, indent, "{");

            string innerIndent = indent + "    ";
            string itemVar = $"item_{resultVar}";
            L(body, innerIndent, $"var doc_{resultVar} = JsonElement.CreateArrayBuilder(workspace, {leftVar}.GetArrayLength());");
            L(body, innerIndent, $"var root_{resultVar} = doc_{resultVar}.RootElement;");
            L(body, innerIndent, $"foreach (JsonElement {itemVar} in {leftVar}.EnumerateArray())");
            L(body, innerIndent, "{");

            string condVar = EmitExpression(body, node.Condition, innerIndent + "    ", itemVar);
            L(body, innerIndent, $"    if ({H}.IsTruthy({condVar}))");
            L(body, innerIndent, "    {");
            string projectedVar = EmitExpression(body, node.Right, innerIndent + "        ", itemVar);
            L(body, innerIndent, $"        if (!{projectedVar}.IsNullOrUndefined())");
            L(body, innerIndent, "        {");
            L(body, innerIndent, $"            root_{resultVar}.AddItem({projectedVar});");
            L(body, innerIndent, "        }");
            L(body, innerIndent, "    }");

            L(body, innerIndent, "}");
            L(body, innerIndent, $"{resultVar} = (JsonElement)root_{resultVar};");

            L(body, indent, "}");
            Blank(body);
            return resultVar;
        }

        private string EmitFunctionCall(StringBuilder body, FunctionCallNode node, string indent, string inputVar)
        {
            string funcName = Encoding.UTF8.GetString(node.Name);
            JMESPathNode[] args = node.Arguments;

            return funcName switch
            {
                "abs" => EmitUnaryFunc(body, "Abs", args, indent, inputVar, needsWorkspace: true),
                "avg" => EmitUnaryFunc(body, "Avg", args, indent, inputVar, needsWorkspace: true),
                "ceil" => EmitUnaryFunc(body, "Ceil", args, indent, inputVar, needsWorkspace: true),
                "contains" => EmitBinaryFunc(body, "Contains", args, indent, inputVar, needsWorkspace: false),
                "ends_with" => EmitBinaryFunc(body, "EndsWith", args, indent, inputVar, needsWorkspace: false),
                "floor" => EmitUnaryFunc(body, "Floor", args, indent, inputVar, needsWorkspace: true),
                "join" => EmitBinaryFunc(body, "Join", args, indent, inputVar, needsWorkspace: true),
                "keys" => EmitUnaryFunc(body, "Keys", args, indent, inputVar, needsWorkspace: true),
                "length" => EmitUnaryFunc(body, "Length", args, indent, inputVar, needsWorkspace: true),
                "map" => EmitMapFunc(body, args, indent, inputVar),
                "max" => EmitUnaryFunc(body, "Max", args, indent, inputVar, needsWorkspace: false),
                "max_by" => EmitExprRefBinaryFunc(body, "MaxBy", args, indent, inputVar),
                "merge" => EmitMergeFunc(body, args, indent, inputVar),
                "min" => EmitUnaryFunc(body, "Min", args, indent, inputVar, needsWorkspace: false),
                "min_by" => EmitExprRefBinaryFunc(body, "MinBy", args, indent, inputVar),
                "not_null" => EmitNotNullFunc(body, args, indent, inputVar),
                "reverse" => EmitUnaryFunc(body, "Reverse", args, indent, inputVar, needsWorkspace: true),
                "sort" => EmitUnaryFunc(body, "Sort", args, indent, inputVar, needsWorkspace: true),
                "sort_by" => EmitSortByFunc(body, args, indent, inputVar),
                "starts_with" => EmitBinaryFunc(body, "StartsWith", args, indent, inputVar, needsWorkspace: false),
                "sum" => EmitUnaryFunc(body, "Sum", args, indent, inputVar, needsWorkspace: true),
                "to_array" => EmitUnaryFunc(body, "ToArray", args, indent, inputVar, needsWorkspace: true),
                "to_number" => EmitUnaryFunc(body, "ToNumber", args, indent, inputVar, needsWorkspace: true),
                "to_string" => EmitUnaryFunc(body, "ToString", args, indent, inputVar, needsWorkspace: true),
                "type" => EmitUnaryFunc(body, "TypeOf", args, indent, inputVar, needsWorkspace: false),
                "values" => EmitUnaryFunc(body, "Values", args, indent, inputVar, needsWorkspace: true),
                _ => throw new JMESPathException($"Unknown function: {funcName}()"),
            };
        }

        private string EmitUnaryFunc(StringBuilder body, string helperName, JMESPathNode[] args, string indent, string inputVar, bool needsWorkspace)
        {
            if (args.Length != 1)
            {
                throw new JMESPathException($"invalid-arity: {helperName}() takes exactly 1 argument, got {args.Length}.");
            }

            string argVar = EmitExpression(body, args[0], indent, inputVar);
            string resultVar = NextVar();
            string wsArg = needsWorkspace ? ", workspace" : string.Empty;
            L(body, indent, $"JsonElement {resultVar} = {H}.{helperName}({argVar}{wsArg});");
            return resultVar;
        }

        private string EmitBinaryFunc(StringBuilder body, string helperName, JMESPathNode[] args, string indent, string inputVar, bool needsWorkspace)
        {
            if (args.Length != 2)
            {
                throw new JMESPathException($"invalid-arity: {helperName}() takes exactly 2 arguments, got {args.Length}.");
            }

            string arg0Var = EmitExpression(body, args[0], indent, inputVar);
            string arg1Var = EmitExpression(body, args[1], indent, inputVar);
            string resultVar = NextVar();
            string wsArg = needsWorkspace ? ", workspace" : string.Empty;
            L(body, indent, $"JsonElement {resultVar} = {H}.{helperName}({arg0Var}, {arg1Var}{wsArg});");
            return resultVar;
        }

        private string EmitExprRefBinaryFunc(StringBuilder body, string helperName, JMESPathNode[] args, string indent, string inputVar)
        {
            if (args.Length != 2)
            {
                throw new JMESPathException($"invalid-arity: {helperName}() takes exactly 2 arguments, got {args.Length}.");
            }

            string arrVar = EmitExpression(body, args[0], indent, inputVar);
            string exprRefMethod = EmitExpressionRef(args[1]);

            string resultVar = NextVar();
            L(body, indent, $"JsonElement {resultVar} = {H}.{helperName}({arrVar}, {exprRefMethod}, workspace);");
            return resultVar;
        }

        private string EmitSortByFunc(StringBuilder body, JMESPathNode[] args, string indent, string inputVar)
        {
            if (args.Length != 2)
            {
                throw new JMESPathException("invalid-arity: sort_by() takes exactly 2 arguments.");
            }

            string arrVar = EmitExpression(body, args[0], indent, inputVar);
            string exprRefMethod = EmitExpressionRef(args[1]);

            string resultVar = NextVar();
            L(body, indent, $"JsonElement {resultVar} = {H}.SortBy({arrVar}, {exprRefMethod}, workspace);");
            return resultVar;
        }

        private string EmitMapFunc(StringBuilder body, JMESPathNode[] args, string indent, string inputVar)
        {
            if (args.Length != 2)
            {
                throw new JMESPathException("invalid-arity: map() takes exactly 2 arguments.");
            }

            string exprRefMethod = EmitExpressionRef(args[0]);
            string arrVar = EmitExpression(body, args[1], indent, inputVar);

            string resultVar = NextVar();
            L(body, indent, $"JsonElement {resultVar} = {H}.Map({exprRefMethod}, {arrVar}, workspace);");
            return resultVar;
        }

        private string EmitMergeFunc(StringBuilder body, JMESPathNode[] args, string indent, string inputVar)
        {
            if (args.Length < 1)
            {
                throw new JMESPathException("invalid-arity: merge() takes at least 1 argument.");
            }

            string[] argVars = new string[args.Length];
            for (int i = 0; i < args.Length; i++)
            {
                argVars[i] = EmitExpression(body, args[i], indent, inputVar);
            }

            string resultVar = NextVar();
            string argsArray = string.Join(", ", argVars);
            L(body, indent, $"JsonElement {resultVar} = {H}.Merge(new JsonElement[] {{ {argsArray} }}, workspace);");
            return resultVar;
        }

        private string EmitNotNullFunc(StringBuilder body, JMESPathNode[] args, string indent, string inputVar)
        {
            if (args.Length < 1)
            {
                throw new JMESPathException("invalid-arity: not_null() takes at least 1 argument.");
            }

            string[] argVars = new string[args.Length];
            for (int i = 0; i < args.Length; i++)
            {
                argVars[i] = EmitExpression(body, args[i], indent, inputVar);
            }

            string resultVar = NextVar();
            string argsArray = string.Join(", ", argVars);
            L(body, indent, $"JsonElement {resultVar} = {H}.NotNull(new JsonElement[] {{ {argsArray} }});");
            return resultVar;
        }

        private string EmitExpressionRef(JMESPathNode arg)
        {
            if (arg is not ExpressionRefNode exprRef)
            {
                throw new JMESPathException("invalid-type: Expected an expression reference (&expr).");
            }

            int refIdx = exprRefCounter++;
            string methodName = $"ExprRef{refIdx}";

            // Build the expression-ref method body
            Emitter innerEmitter = new()
            {
                varCounter = 0,
                nameCounter = this.nameCounter,
                literalCounter = this.literalCounter,
                exprRefCounter = this.exprRefCounter,
            };

            StringBuilder innerBody = new(512);
            string innerResult = innerEmitter.EmitExpression(innerBody, exprRef.Expression, "        ", "data");

            // Merge inner emitter's fields into ours
            StaticFields.AddRange(innerEmitter.StaticFields);
            NameFields.AddRange(innerEmitter.NameFields);
            HelperMethods.AddRange(innerEmitter.HelperMethods);

            this.nameCounter = innerEmitter.nameCounter;
            this.literalCounter = innerEmitter.literalCounter;
            this.exprRefCounter = innerEmitter.exprRefCounter;

            // Build the helper method
            StringBuilder method2 = new(1024);
            L(method2, "    ", $"private static JsonElement {methodName}(in JsonElement data, JsonWorkspace workspace)");
            L(method2, "    ", "{");
            method2.Append(innerBody);
            L(method2, "        ", $"return {innerResult};");
            L(method2, "    ", "}");

            HelperMethods.Add(method2.ToString());

            return methodName;
        }
    }
}