Feature: Validate a V3 Model against V4

Scenario Outline: All of the format types
	Given the input data value <inputData>
	And I construct an instance of the V3 generated type as a <InstanceType> backed object
	When I validate the instance with level <level>
	Then the result will be <valid>
	And there will be <count> results

Examples:
	| inputData                                            | valid | level    | count | InstanceType |
	| ""                                                   | false | Flag     | 0     | JsonElement  |
	| ""                                                   | false | Basic    | 1     | JsonElement  |
	| ""                                                   | false | Detailed | 1     | JsonElement  |
	| ""                                                   | false | Verbose  | 210   | JsonElement  |
	| "foo"                                                | false | Flag     | 0     | JsonElement  |
	| "foo"                                                | false | Basic    | 1     | JsonElement  |
	| "foo"                                                | false | Detailed | 1     | JsonElement  |
	| "foo"                                                | false | Verbose  | 211   | JsonElement  |
	| "#\\foor\\bar"                                       | false | Flag     | 0     | JsonElement  |
	| "#\\foor\\bar"                                       | false | Basic    | 1     | JsonElement  |
	| "#\\foor\\bar"                                       | false | Detailed | 1     | JsonElement  |
	| "#\\foor\\bar"                                       | false | Verbose  | 210   | JsonElement  |
	| "01234567890123456789012345678901234567890123456789" | false | Flag     | 0     | JsonElement  |
	| "01234567890123456789012345678901234567890123456789" | false | Basic    | 1     | JsonElement  |
	| "01234567890123456789012345678901234567890123456789" | false | Detailed | 1     | JsonElement  |
	| "01234567890123456789012345678901234567890123456789" | false | Verbose  | 211   | JsonElement  |
	| "1"                                                  | false | Flag     | 0     | JsonElement  |
	| "2"                                                  | false | Flag     | 0     | JsonElement  |
	| "3"                                                  | false | Flag     | 0     | JsonElement  |
	| "4"                                                  | false | Flag     | 0     | JsonElement  |
	| "5"                                                  | false | Flag     | 0     | JsonElement  |
	| "6"                                                  | false | Flag     | 0     | JsonElement  |
	| "7"                                                  | false | Flag     | 0     | JsonElement  |
	| "8"                                                  | false | Flag     | 0     | JsonElement  |
	| "1"                                                  | false | Basic    | 1     | JsonElement  |
	| "2"                                                  | false | Basic    | 1     | JsonElement  |
	| "3"                                                  | false | Basic    | 1     | JsonElement  |
	| "4"                                                  | false | Basic    | 1     | JsonElement  |
	| "5"                                                  | false | Basic    | 1     | JsonElement  |
	| "6"                                                  | false | Basic    | 1     | JsonElement  |
	| "7"                                                  | false | Basic    | 1     | JsonElement  |
	| "8"                                                  | false | Basic    | 1     | JsonElement  |
	| "1"                                                  | false | Detailed | 1     | JsonElement  |
	| "2"                                                  | false | Detailed | 1     | JsonElement  |
	| "3"                                                  | false | Detailed | 1     | JsonElement  |
	| "4"                                                  | false | Detailed | 1     | JsonElement  |
	| "5"                                                  | false | Detailed | 1     | JsonElement  |
	| "6"                                                  | false | Detailed | 1     | JsonElement  |
	| "7"                                                  | false | Detailed | 1     | JsonElement  |
	| "8"                                                  | false | Detailed | 1     | JsonElement  |
	| "1"                                                  | false | Verbose  | 211   | JsonElement  |
	| "2"                                                  | false | Verbose  | 211   | JsonElement  |
	| "3"                                                  | false | Verbose  | 211   | JsonElement  |
	| "4"                                                  | false | Verbose  | 211   | JsonElement  |
	| "5"                                                  | false | Verbose  | 211   | JsonElement  |
	| "6"                                                  | false | Verbose  | 211   | JsonElement  |
	| "7"                                                  | false | Verbose  | 211   | JsonElement  |
	| "8"                                                  | false | Verbose  | 211   | JsonElement  |
	| null                                                 | false | Flag     | 0     | JsonElement  |
	| null                                                 | false | Basic    | 1     | JsonElement  |
	| null                                                 | false | Detailed | 1     | JsonElement  |
	| null                                                 | false | Verbose  | 179   | JsonElement  |
	| -1                                                   | false | Flag     | 0     | JsonElement  |
	| 0                                                    | false | Flag     | 0     | JsonElement  |
	| 1                                                    | false | Flag     | 0     | JsonElement  |
	| 256                                                  | false | Flag     | 0     | JsonElement  |
	| -256                                                 | false | Flag     | 0     | JsonElement  |
	| 256.1                                                | false | Flag     | 0     | JsonElement  |
	| -256.1                                               | false | Flag     | 0     | JsonElement  |
	| 256                                                  | false | Flag     | 0     | JsonElement  |
	| -32769                                               | false | Flag     | 0     | JsonElement  |
	| 32769                                                | false | Flag     | 0     | JsonElement  |
	| -32769.1                                             | false | Flag     | 0     | JsonElement  |
	| 32769.1                                              | false | Flag     | 0     | JsonElement  |
	| -65536                                               | false | Flag     | 0     | JsonElement  |
	| 65536                                                | false | Flag     | 0     | JsonElement  |
	| -65536.1                                             | false | Flag     | 0     | JsonElement  |
	| 65536.1                                              | false | Flag     | 0     | JsonElement  |
	| -2147483648                                          | false | Flag     | 0     | JsonElement  |
	| 2147483648                                           | false | Flag     | 0     | JsonElement  |
	| -2147483648.1                                        | false | Flag     | 0     | JsonElement  |
	| 2147483648.1                                         | false | Flag     | 0     | JsonElement  |
	| true                                                 | false | Flag     | 0     | JsonElement  |
	| [1,2,3]                                              | false | Flag     | 0     | JsonElement  |
	| { "foo": "bar" }                                     | true  | Flag     | 0     | JsonElement  |
	| -1                                                   | false | Basic    | 1     | JsonElement  |
	| 0                                                    | false | Basic    | 1     | JsonElement  |
	| 1                                                    | false | Basic    | 1     | JsonElement  |
	| 256                                                  | false | Basic    | 1     | JsonElement  |
	| -256                                                 | false | Basic    | 1     | JsonElement  |
	| 256.1                                                | false | Basic    | 1     | JsonElement  |
	| -256.1                                               | false | Basic    | 1     | JsonElement  |
	| 256                                                  | false | Basic    | 1     | JsonElement  |
	| -32769                                               | false | Basic    | 1     | JsonElement  |
	| 32769                                                | false | Basic    | 1     | JsonElement  |
	| -32769.1                                             | false | Basic    | 1     | JsonElement  |
	| 32769.1                                              | false | Basic    | 1     | JsonElement  |
	| -65536                                               | false | Basic    | 1     | JsonElement  |
	| 65536                                                | false | Basic    | 1     | JsonElement  |
	| -65536.1                                             | false | Basic    | 1     | JsonElement  |
	| 65536.1                                              | false | Basic    | 1     | JsonElement  |
	| -2147483648                                          | false | Basic    | 1     | JsonElement  |
	| 2147483648                                           | false | Basic    | 1     | JsonElement  |
	| -2147483648.1                                        | false | Basic    | 1     | JsonElement  |
	| 2147483648.1                                         | false | Basic    | 1     | JsonElement  |
	| true                                                 | false | Basic    | 1     | JsonElement  |
	| [1,2,3]                                              | false | Basic    | 1     | JsonElement  |
	| { "foo": "bar" }                                     | true  | Basic    | 0     | JsonElement  |
	| -1                                                   | false | Detailed | 1     | JsonElement  |
	| 0                                                    | false | Detailed | 1     | JsonElement  |
	| 1                                                    | false | Detailed | 1     | JsonElement  |
	| 256                                                  | false | Detailed | 1     | JsonElement  |
	| -256                                                 | false | Detailed | 1     | JsonElement  |
	| 256.1                                                | false | Detailed | 1     | JsonElement  |
	| -256.1                                               | false | Detailed | 1     | JsonElement  |
	| 256                                                  | false | Detailed | 1     | JsonElement  |
	| -32769                                               | false | Detailed | 1     | JsonElement  |
	| 32769                                                | false | Detailed | 1     | JsonElement  |
	| -32769.1                                             | false | Detailed | 1     | JsonElement  |
	| 32769.1                                              | false | Detailed | 1     | JsonElement  |
	| -65536                                               | false | Detailed | 1     | JsonElement  |
	| 65536                                                | false | Detailed | 1     | JsonElement  |
	| -65536.1                                             | false | Detailed | 1     | JsonElement  |
	| 65536.1                                              | false | Detailed | 1     | JsonElement  |
	| -2147483648                                          | false | Detailed | 1     | JsonElement  |
	| 2147483648                                           | false | Detailed | 1     | JsonElement  |
	| -2147483648.1                                        | false | Detailed | 1     | JsonElement  |
	| 2147483648.1                                         | false | Detailed | 1     | JsonElement  |
	| true                                                 | false | Detailed | 1     | JsonElement  |
	| [1,2,3]                                              | false | Detailed | 1     | JsonElement  |
	| { "foo": "bar" }                                     | true  | Detailed | 0     | JsonElement  |
	| -1                                                   | false | Verbose  | 203   | JsonElement  |
	| 0                                                    | false | Verbose  | 209   | JsonElement  |
	| 1                                                    | false | Verbose  | 209   | JsonElement  |
	| 256                                                  | false | Verbose  | 207   | JsonElement  |
	| -256                                                 | false | Verbose  | 202   | JsonElement  |
	| 256.1                                                | false | Verbose  | 198   | JsonElement  |
	| -256.1                                               | false | Verbose  | 198   | JsonElement  |
	| -32769                                               | false | Verbose  | 201   | JsonElement  |
	| 32769                                                | false | Verbose  | 206   | JsonElement  |
	| -32769.1                                             | false | Verbose  | 198   | JsonElement  |
	| 32769.1                                              | false | Verbose  | 198   | JsonElement  |
	| -65536                                               | false | Verbose  | 200   | JsonElement  |
	| 65536                                                | false | Verbose  | 203   | JsonElement  |
	| -65536.1                                             | false | Verbose  | 197   | JsonElement  |
	| 65536.1                                              | false | Verbose  | 197   | JsonElement  |
	| -2147483648                                          | false | Verbose  | 200   | JsonElement  |
	| 2147483648                                           | false | Verbose  | 202   | JsonElement  |
	| -2147483648.1                                        | false | Verbose  | 197   | JsonElement  |
	| 2147483648.1                                         | false | Verbose  | 197   | JsonElement  |
	| true                                                 | false | Verbose  | 179   | JsonElement  |
	| [1,2,3]                                              | false | Verbose  | 180   | JsonElement  |
	| { "foo": "bar" }                                     | true  | Verbose  | 179   | JsonElement  |
	| ""                                                   | false | Flag     | 0     | dotnet       |
	| ""                                                   | false | Basic    | 1     | dotnet       |
	| ""                                                   | false | Detailed | 1     | dotnet       |
	| ""                                                   | false | Verbose  | 210   | dotnet       |
	| "foo"                                                | false | Flag     | 0     | dotnet       |
	| "foo"                                                | false | Basic    | 1     | dotnet       |
	| "foo"                                                | false | Detailed | 1     | dotnet       |
	| "foo"                                                | false | Verbose  | 211   | dotnet       |
	| "01234567890123456789012345678901234567890123456789" | false | Flag     | 0     | dotnet       |
	| "01234567890123456789012345678901234567890123456789" | false | Basic    | 1     | dotnet       |
	| "01234567890123456789012345678901234567890123456789" | false | Detailed | 1     | dotnet       |
	| "01234567890123456789012345678901234567890123456789" | false | Verbose  | 211   | dotnet       |
	| "#\\foo\\bar"                                        | false | Flag     | 0     | dotnet       |
	| "#\\foo\\bar"                                        | false | Basic    | 1     | dotnet       |
	| "#\\foo\\bar"                                        | false | Detailed | 1     | dotnet       |
	| "#\\foo\\bar"                                        | false | Verbose  | 210   | dotnet       |
	| "1"                                                  | false | Flag     | 0     | dotnet       |
	| "2"                                                  | false | Flag     | 0     | dotnet       |
	| "3"                                                  | false | Flag     | 0     | dotnet       |
	| "4"                                                  | false | Flag     | 0     | dotnet       |
	| "5"                                                  | false | Flag     | 0     | dotnet       |
	| "6"                                                  | false | Flag     | 0     | dotnet       |
	| "7"                                                  | false | Flag     | 0     | dotnet       |
	| "8"                                                  | false | Flag     | 0     | dotnet       |
	| "1"                                                  | false | Basic    | 1     | dotnet       |
	| "2"                                                  | false | Basic    | 1     | dotnet       |
	| "3"                                                  | false | Basic    | 1     | dotnet       |
	| "4"                                                  | false | Basic    | 1     | dotnet       |
	| "5"                                                  | false | Basic    | 1     | dotnet       |
	| "6"                                                  | false | Basic    | 1     | dotnet       |
	| "7"                                                  | false | Basic    | 1     | dotnet       |
	| "8"                                                  | false | Basic    | 1     | dotnet       |
	| "1"                                                  | false | Detailed | 1     | dotnet       |
	| "2"                                                  | false | Detailed | 1     | dotnet       |
	| "3"                                                  | false | Detailed | 1     | dotnet       |
	| "4"                                                  | false | Detailed | 1     | dotnet       |
	| "5"                                                  | false | Detailed | 1     | dotnet       |
	| "6"                                                  | false | Detailed | 1     | dotnet       |
	| "7"                                                  | false | Detailed | 1     | dotnet       |
	| "8"                                                  | false | Detailed | 1     | dotnet       |
	| "1"                                                  | false | Verbose  | 211   | dotnet       |
	| "2"                                                  | false | Verbose  | 211   | dotnet       |
	| "3"                                                  | false | Verbose  | 211   | dotnet       |
	| "4"                                                  | false | Verbose  | 211   | dotnet       |
	| "5"                                                  | false | Verbose  | 211   | dotnet       |
	| "6"                                                  | false | Verbose  | 211   | dotnet       |
	| "7"                                                  | false | Verbose  | 211   | dotnet       |
	| "8"                                                  | false | Verbose  | 211   | dotnet       |
	| null                                                 | false | Flag     | 0     | dotnet       |
	| null                                                 | false | Basic    | 1     | dotnet       |
	| null                                                 | false | Detailed | 1     | dotnet       |
	| null                                                 | false | Verbose  | 179   | dotnet       |
	| -1                                                   | false | Flag     | 0     | dotnet       |
	| 0                                                    | false | Flag     | 0     | dotnet       |
	| 1                                                    | false | Flag     | 0     | dotnet       |
	| 256                                                  | false | Flag     | 0     | dotnet       |
	| -256                                                 | false | Flag     | 0     | dotnet       |
	| 256.1                                                | false | Flag     | 0     | dotnet       |
	| -256.1                                               | false | Flag     | 0     | dotnet       |
	| 256                                                  | false | Flag     | 0     | dotnet       |
	| -32769                                               | false | Flag     | 0     | dotnet       |
	| 32769                                                | false | Flag     | 0     | dotnet       |
	| -32769.1                                             | false | Flag     | 0     | dotnet       |
	| 32769.1                                              | false | Flag     | 0     | dotnet       |
	| -65536                                               | false | Flag     | 0     | dotnet       |
	| 65536                                                | false | Flag     | 0     | dotnet       |
	| -65536.1                                             | false | Flag     | 0     | dotnet       |
	| 65536.1                                              | false | Flag     | 0     | dotnet       |
	| -2147483648                                          | false | Flag     | 0     | dotnet       |
	| 2147483648                                           | false | Flag     | 0     | dotnet       |
	| -2147483648.1                                        | false | Flag     | 0     | dotnet       |
	| 2147483648.1                                         | false | Flag     | 0     | dotnet       |
	| true                                                 | false | Flag     | 0     | dotnet       |
	| [1,2,3]                                              | false | Flag     | 0     | dotnet       |
	| { "foo": "bar" }                                     | true  | Flag     | 0     | dotnet       |
	| -1                                                   | false | Basic    | 1     | dotnet       |
	| 0                                                    | false | Basic    | 1     | dotnet       |
	| 1                                                    | false | Basic    | 1     | dotnet       |
	| 256                                                  | false | Basic    | 1     | dotnet       |
	| -256                                                 | false | Basic    | 1     | dotnet       |
	| 256.1                                                | false | Basic    | 1     | dotnet       |
	| -256.1                                               | false | Basic    | 1     | dotnet       |
	| 256                                                  | false | Basic    | 1     | dotnet       |
	| -32769                                               | false | Basic    | 1     | dotnet       |
	| 32769                                                | false | Basic    | 1     | dotnet       |
	| -32769.1                                             | false | Basic    | 1     | dotnet       |
	| 32769.1                                              | false | Basic    | 1     | dotnet       |
	| -65536                                               | false | Basic    | 1     | dotnet       |
	| 65536                                                | false | Basic    | 1     | dotnet       |
	| -65536.1                                             | false | Basic    | 1     | dotnet       |
	| 65536.1                                              | false | Basic    | 1     | dotnet       |
	| -2147483648                                          | false | Basic    | 1     | dotnet       |
	| 2147483648                                           | false | Basic    | 1     | dotnet       |
	| -2147483648.1                                        | false | Basic    | 1     | dotnet       |
	| 2147483648.1                                         | false | Basic    | 1     | dotnet       |
	| true                                                 | false | Basic    | 1     | dotnet       |
	| [1,2,3]                                              | false | Basic    | 1     | dotnet       |
	| { "foo": "bar" }                                     | true  | Basic    | 0     | dotnet       |
	| -1                                                   | false | Detailed | 1     | dotnet       |
	| 0                                                    | false | Detailed | 1     | dotnet       |
	| 1                                                    | false | Detailed | 1     | dotnet       |
	| 256                                                  | false | Detailed | 1     | dotnet       |
	| -256                                                 | false | Detailed | 1     | dotnet       |
	| 256.1                                                | false | Detailed | 1     | dotnet       |
	| -256.1                                               | false | Detailed | 1     | dotnet       |
	| 256                                                  | false | Detailed | 1     | dotnet       |
	| -32769                                               | false | Detailed | 1     | dotnet       |
	| 32769                                                | false | Detailed | 1     | dotnet       |
	| -32769.1                                             | false | Detailed | 1     | dotnet       |
	| 32769.1                                              | false | Detailed | 1     | dotnet       |
	| -65536                                               | false | Detailed | 1     | dotnet       |
	| 65536                                                | false | Detailed | 1     | dotnet       |
	| -65536.1                                             | false | Detailed | 1     | dotnet       |
	| 65536.1                                              | false | Detailed | 1     | dotnet       |
	| -2147483648                                          | false | Detailed | 1     | dotnet       |
	| 2147483648                                           | false | Detailed | 1     | dotnet       |
	| -2147483648.1                                        | false | Detailed | 1     | dotnet       |
	| 2147483648.1                                         | false | Detailed | 1     | dotnet       |
	| true                                                 | false | Detailed | 1     | dotnet       |
	| [1,2,3]                                              | false | Detailed | 1     | dotnet       |
	| { "foo": "bar" }                                     | true  | Detailed | 0     | dotnet       |
	| -1                                                   | false | Verbose  | 203   | dotnet       |
	| 0                                                    | false | Verbose  | 209   | dotnet       |
	| 1                                                    | false | Verbose  | 209   | dotnet       |
	| 256                                                  | false | Verbose  | 207   | dotnet       |
	| -256                                                 | false | Verbose  | 202   | dotnet       |
	| 256.1                                                | false | Verbose  | 198   | dotnet       |
	| -256.1                                               | false | Verbose  | 198   | dotnet       |
	| -32769                                               | false | Verbose  | 201   | dotnet       |
	| 32769                                                | false | Verbose  | 206   | dotnet       |
	| -32769.1                                             | false | Verbose  | 198   | dotnet       |
	| 32769.1                                              | false | Verbose  | 198   | dotnet       |
	| -65536                                               | false | Verbose  | 200   | dotnet       |
	| 65536                                                | false | Verbose  | 203   | dotnet       |
	| -65536.1                                             | false | Verbose  | 197   | dotnet       |
	| 65536.1                                              | false | Verbose  | 197   | dotnet       |
	| -2147483648                                          | false | Verbose  | 200   | dotnet       |
	| 2147483648                                           | false | Verbose  | 202   | dotnet       |
	| -2147483648.1                                        | false | Verbose  | 197   | dotnet       |
	| 2147483648.1                                         | false | Verbose  | 197   | dotnet       |
	| true                                                 | false | Verbose  | 179   | dotnet       |
	| [1,2,3]                                              | false | Verbose  | 180   | dotnet       |
	| { "foo": "bar" }                                     | true  | Verbose  | 179   | dotnet       |