// <auto-generated/>
#nullable enable

using System.Text.Json;
using Corvus.Json;
using Corvus.Json.Specs.Tests.Infrastructure;
using Drivers;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace JsonSchemaTestSuite.OpenApi20.Items;

[TestCategory("OpenApi20")]
[TestClass]
public class SuiteASchemaGivenForItems
{
    private static Fixture? s_fixture;

    [ClassInitialize]
    public static async Task ClassInit(TestContext _)
    {
        s_fixture = new Fixture();
        await s_fixture.InitializeAsync();
    }

    [ClassCleanup]
    public static void ClassCleanupMethod()
    {
        if (s_fixture is not null)
        {
            s_fixture.Dispose();
            s_fixture = null;
        }
    }

    [TestMethod]
    public void TestValidItems()
    {
        using var doc = JsonDocument.Parse("[\n                    1,\n                    2,\n                    3\n                ]");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(s_fixture!.GeneratedType, doc.RootElement);
        Assert.IsTrue(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    [TestMethod]
    public void TestWrongTypeOfItems()
    {
        using var doc = JsonDocument.Parse("[\n                    1,\n                    \"x\"\n                ]");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(s_fixture!.GeneratedType, doc.RootElement);
        Assert.IsFalse(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    [TestMethod]
    public void TestIgnoresNonArrays()
    {
        using var doc = JsonDocument.Parse("{\n                    \"foo\": \"bar\"\n                }");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(s_fixture!.GeneratedType, doc.RootElement);
        Assert.IsTrue(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    [TestMethod]
    public void TestJavaScriptPseudoArrayIsValid()
    {
        using var doc = JsonDocument.Parse("{\n                    \"0\": \"invalid\",\n                    \"length\": 1\n                }");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(s_fixture!.GeneratedType, doc.RootElement);
        Assert.IsTrue(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    public class Fixture : IDisposable
    {
        private JsonSchemaBuilderDriver? _driver;

        public global::System.Type GeneratedType { get; private set; } = null!;

        public async Task InitializeAsync()
        {
            _driver = DriverFactory.CreateOpenApi20Driver();
            GeneratedType = await _driver.GenerateTypeForJsonSchemaTestSuite(
                "items.json",
                "#/0/schema",
                "JsonSchemaTestSuiteOpenApi20Items",
                "ASchemaGivenForItems",
                validateFormat: false,
                optionalAsNullable: false,
                useImplicitOperatorString: false);
        }

        public void Dispose()
        {
            _driver?.Dispose();
        }
    }
}

[TestCategory("OpenApi20")]
[TestClass]
public class SuiteAnArrayOfSchemasForItems
{
    private static Fixture? s_fixture;

    [ClassInitialize]
    public static async Task ClassInit(TestContext _)
    {
        s_fixture = new Fixture();
        await s_fixture.InitializeAsync();
    }

    [ClassCleanup]
    public static void ClassCleanupMethod()
    {
        if (s_fixture is not null)
        {
            s_fixture.Dispose();
            s_fixture = null;
        }
    }

    [TestMethod]
    public void TestCorrectTypes()
    {
        using var doc = JsonDocument.Parse("[\n                    1,\n                    \"foo\"\n                ]");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(s_fixture!.GeneratedType, doc.RootElement);
        Assert.IsTrue(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    [TestMethod]
    public void TestWrongTypes()
    {
        using var doc = JsonDocument.Parse("[\n                    \"foo\",\n                    1\n                ]");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(s_fixture!.GeneratedType, doc.RootElement);
        Assert.IsFalse(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    [TestMethod]
    public void TestIncompleteArrayOfItems()
    {
        using var doc = JsonDocument.Parse("[\n                    1\n                ]");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(s_fixture!.GeneratedType, doc.RootElement);
        Assert.IsTrue(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    [TestMethod]
    public void TestArrayWithAdditionalItems()
    {
        using var doc = JsonDocument.Parse("[\n                    1,\n                    \"foo\",\n                    true\n                ]");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(s_fixture!.GeneratedType, doc.RootElement);
        Assert.IsTrue(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    [TestMethod]
    public void TestEmptyArray()
    {
        using var doc = JsonDocument.Parse("[]");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(s_fixture!.GeneratedType, doc.RootElement);
        Assert.IsTrue(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    [TestMethod]
    public void TestJavaScriptPseudoArrayIsValid()
    {
        using var doc = JsonDocument.Parse("{\n                    \"0\": \"invalid\",\n                    \"1\": \"valid\",\n                    \"length\": 2\n                }");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(s_fixture!.GeneratedType, doc.RootElement);
        Assert.IsTrue(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    public class Fixture : IDisposable
    {
        private JsonSchemaBuilderDriver? _driver;

        public global::System.Type GeneratedType { get; private set; } = null!;

        public async Task InitializeAsync()
        {
            _driver = DriverFactory.CreateOpenApi20Driver();
            GeneratedType = await _driver.GenerateTypeForJsonSchemaTestSuite(
                "items.json",
                "#/1/schema",
                "JsonSchemaTestSuiteOpenApi20Items",
                "AnArrayOfSchemasForItems",
                validateFormat: false,
                optionalAsNullable: false,
                useImplicitOperatorString: false);
        }

        public void Dispose()
        {
            _driver?.Dispose();
        }
    }
}

[TestCategory("OpenApi20")]
[TestClass]
public class SuiteNestedItems
{
    private static Fixture? s_fixture;

    [ClassInitialize]
    public static async Task ClassInit(TestContext _)
    {
        s_fixture = new Fixture();
        await s_fixture.InitializeAsync();
    }

    [ClassCleanup]
    public static void ClassCleanupMethod()
    {
        if (s_fixture is not null)
        {
            s_fixture.Dispose();
            s_fixture = null;
        }
    }

    [TestMethod]
    public void TestValidNestedArray()
    {
        using var doc = JsonDocument.Parse("[\n                    [\n                        [\n                            [\n                                1\n                            ]\n                        ],\n                        [\n                            [\n                                2\n                            ],\n                            [\n                                3\n                            ]\n                        ]\n                    ],\n                    [\n                        [\n                            [\n                                4\n                            ],\n                            [\n                                5\n                            ],\n                            [\n                                6\n                            ]\n                        ]\n                    ]\n                ]");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(s_fixture!.GeneratedType, doc.RootElement);
        Assert.IsTrue(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    [TestMethod]
    public void TestNestedArrayWithInvalidType()
    {
        using var doc = JsonDocument.Parse("[\n                    [\n                        [\n                            [\n                                \"1\"\n                            ]\n                        ],\n                        [\n                            [\n                                2\n                            ],\n                            [\n                                3\n                            ]\n                        ]\n                    ],\n                    [\n                        [\n                            [\n                                4\n                            ],\n                            [\n                                5\n                            ],\n                            [\n                                6\n                            ]\n                        ]\n                    ]\n                ]");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(s_fixture!.GeneratedType, doc.RootElement);
        Assert.IsFalse(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    [TestMethod]
    public void TestNotDeepEnough()
    {
        using var doc = JsonDocument.Parse("[\n                    [\n                        [\n                            1\n                        ],\n                        [\n                            2\n                        ],\n                        [\n                            3\n                        ]\n                    ],\n                    [\n                        [\n                            4\n                        ],\n                        [\n                            5\n                        ],\n                        [\n                            6\n                        ]\n                    ]\n                ]");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(s_fixture!.GeneratedType, doc.RootElement);
        Assert.IsFalse(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    public class Fixture : IDisposable
    {
        private JsonSchemaBuilderDriver? _driver;

        public global::System.Type GeneratedType { get; private set; } = null!;

        public async Task InitializeAsync()
        {
            _driver = DriverFactory.CreateOpenApi20Driver();
            GeneratedType = await _driver.GenerateTypeForJsonSchemaTestSuite(
                "items.json",
                "#/2/schema",
                "JsonSchemaTestSuiteOpenApi20Items",
                "NestedItems",
                validateFormat: false,
                optionalAsNullable: false,
                useImplicitOperatorString: false);
        }

        public void Dispose()
        {
            _driver?.Dispose();
        }
    }
}

[TestCategory("OpenApi20")]
[TestClass]
public class SuiteItemsWithNullInstanceElements
{
    private static Fixture? s_fixture;

    [ClassInitialize]
    public static async Task ClassInit(TestContext _)
    {
        s_fixture = new Fixture();
        await s_fixture.InitializeAsync();
    }

    [ClassCleanup]
    public static void ClassCleanupMethod()
    {
        if (s_fixture is not null)
        {
            s_fixture.Dispose();
            s_fixture = null;
        }
    }

    [TestMethod]
    public void TestAllowsNullElements()
    {
        using var doc = JsonDocument.Parse("[\n                    null\n                ]");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(s_fixture!.GeneratedType, doc.RootElement);
        Assert.IsTrue(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    public class Fixture : IDisposable
    {
        private JsonSchemaBuilderDriver? _driver;

        public global::System.Type GeneratedType { get; private set; } = null!;

        public async Task InitializeAsync()
        {
            _driver = DriverFactory.CreateOpenApi20Driver();
            GeneratedType = await _driver.GenerateTypeForJsonSchemaTestSuite(
                "items.json",
                "#/3/schema",
                "JsonSchemaTestSuiteOpenApi20Items",
                "ItemsWithNullInstanceElements",
                validateFormat: false,
                optionalAsNullable: false,
                useImplicitOperatorString: false);
        }

        public void Dispose()
        {
            _driver?.Dispose();
        }
    }
}

[TestCategory("OpenApi20")]
[TestClass]
public class SuiteArrayFormItemsWithNullInstanceElements
{
    private static Fixture? s_fixture;

    [ClassInitialize]
    public static async Task ClassInit(TestContext _)
    {
        s_fixture = new Fixture();
        await s_fixture.InitializeAsync();
    }

    [ClassCleanup]
    public static void ClassCleanupMethod()
    {
        if (s_fixture is not null)
        {
            s_fixture.Dispose();
            s_fixture = null;
        }
    }

    [TestMethod]
    public void TestAllowsNullElements()
    {
        using var doc = JsonDocument.Parse("[\n                    null\n                ]");
        IJsonValue instance = JsonSchemaBuilderDriver.CreateInstance(s_fixture!.GeneratedType, doc.RootElement);
        Assert.IsTrue(instance.Validate(ValidationContext.ValidContext).IsValid);
    }

    public class Fixture : IDisposable
    {
        private JsonSchemaBuilderDriver? _driver;

        public global::System.Type GeneratedType { get; private set; } = null!;

        public async Task InitializeAsync()
        {
            _driver = DriverFactory.CreateOpenApi20Driver();
            GeneratedType = await _driver.GenerateTypeForJsonSchemaTestSuite(
                "items.json",
                "#/4/schema",
                "JsonSchemaTestSuiteOpenApi20Items",
                "ArrayFormItemsWithNullInstanceElements",
                validateFormat: false,
                optionalAsNullable: false,
                useImplicitOperatorString: false);
        }

        public void Dispose()
        {
            _driver?.Dispose();
        }
    }
}
