name: build-website-only
on:
  push:
    branches:
    - feature/fix-web-site-publish    # temporary measure to test workflow
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# permissions:
#   actions: write  # enable cache clean-up
#   checks: write  # enable test result annotations
#   contents: write  # enable creating releases
#   issues: read
#   packages: write  # enable publishing packages
#   pull-requests: write  # enable test result annotations

jobs:
  build:
    name: Build/Deploy Web Site
    runs-on: ubuntu-latest
    steps:
    - name: Enable long paths
      run: git config --global core.longpaths true
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd   # v6.0.2
      with:
        fetch-depth: 0
    - uses: endjin/Endjin.RecommendedPractices.GitHubActions/actions/prepare-env-vars-and-secrets@main
      id: prepareEnvVarsAndSecrets
      with:
        environmentVariablesYaml: |
          BUILDVAR_BasePathPrefix: "${{ format('/{0}', github.event.repository.name) }}"
        secretsEncryptionKey: ${{ secrets.SHARED_WORKFLOW_KEY }}
    - uses: endjin/Endjin.RecommendedPractices.GitHubActions/actions/run-scripted-build@main
      id: run_build
      with:
        displayName: Build Documentation Site
        netSdkVersion: '10.0.x'
        additionalNetSdkVersion: |
          8.0.x
          9.0.x
        tasks: Build,BuildWebsite
        configuration: Release
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f   # v4.8.0
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      with:
        branch: gh-pages
        folder: docs/website/.output
        clean-exclude: pr-preview

