//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using Corvus.Json;

namespace Corvus.Json.JsonSchema.OpenApi30;
public readonly partial struct OpenApiDocument
{
    public readonly partial struct Header
    {
        public readonly partial struct ExamplesEntity
        {
            /// <summary>
            /// Generated from JSON Schema.
            /// </summary>
            public readonly partial struct AdditionalPropertiesEntity
            {
                /// <summary>
                /// Gets the value as a <see cref = "Corvus.Json.JsonSchema.OpenApi30.OpenApiDocument.Example"/>.
                /// </summary>
                public Corvus.Json.JsonSchema.OpenApi30.OpenApiDocument.Example AsExample
                {
                    get
                    {
                        return (Corvus.Json.JsonSchema.OpenApi30.OpenApiDocument.Example)this;
                    }
                }

                /// <summary>
                /// Gets a value indicating whether this is a valid <see cref = "Corvus.Json.JsonSchema.OpenApi30.OpenApiDocument.Example"/>.
                /// </summary>
                public bool IsExample
                {
                    get
                    {
                        return ((Corvus.Json.JsonSchema.OpenApi30.OpenApiDocument.Example)this).IsValid();
                    }
                }

                /// <summary>
                /// Gets the value as a <see cref = "Corvus.Json.JsonSchema.OpenApi30.OpenApiDocument.Example"/>.
                /// </summary>
                /// <param name = "result">The result of the conversion.</param>
                /// <returns><c>True</c> if the conversion was valid.</returns>
                public bool TryGetAsExample(out Corvus.Json.JsonSchema.OpenApi30.OpenApiDocument.Example result)
                {
                    result = (Corvus.Json.JsonSchema.OpenApi30.OpenApiDocument.Example)this;
                    return result.IsValid();
                }

                /// <summary>
                /// Gets the value as a <see cref = "Corvus.Json.JsonSchema.OpenApi30.OpenApiDocument.Reference"/>.
                /// </summary>
                public Corvus.Json.JsonSchema.OpenApi30.OpenApiDocument.Reference AsReference
                {
                    get
                    {
                        return (Corvus.Json.JsonSchema.OpenApi30.OpenApiDocument.Reference)this;
                    }
                }

                /// <summary>
                /// Gets a value indicating whether this is a valid <see cref = "Corvus.Json.JsonSchema.OpenApi30.OpenApiDocument.Reference"/>.
                /// </summary>
                public bool IsReference
                {
                    get
                    {
                        return ((Corvus.Json.JsonSchema.OpenApi30.OpenApiDocument.Reference)this).IsValid();
                    }
                }

                /// <summary>
                /// Gets the value as a <see cref = "Corvus.Json.JsonSchema.OpenApi30.OpenApiDocument.Reference"/>.
                /// </summary>
                /// <param name = "result">The result of the conversion.</param>
                /// <returns><c>True</c> if the conversion was valid.</returns>
                public bool TryGetAsReference(out Corvus.Json.JsonSchema.OpenApi30.OpenApiDocument.Reference result)
                {
                    result = (Corvus.Json.JsonSchema.OpenApi30.OpenApiDocument.Reference)this;
                    return result.IsValid();
                }
            }
        }
    }
}