//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Collections.Immutable;
using System.Text.Json;
using Corvus.Json;
using Corvus.Json.Internal;

namespace JsonSchemaSample.DatabaseApi;
public readonly partial struct DbCustomer
{
    /// <summary>
    /// Generated from JSON Schema.
    /// </summary>
    public readonly partial struct IdDescriptor
    {
        /// <summary>
        /// Conversion to <see cref = "JsonSchemaSample.DatabaseApi.DbCustomer.ApiIdDescriptor"/>.
        /// </summary>
        /// <param name = "value">The value from which to convert.</param>
        public static explicit operator JsonSchemaSample.DatabaseApi.DbCustomer.ApiIdDescriptor(IdDescriptor value)
        {
            if ((value.backing & Backing.JsonElement) != 0)
            {
                return new(value.AsJsonElement);
            }

            if ((value.backing & Backing.Object) != 0)
            {
                return new(value.objectBacking);
            }

            return JsonSchemaSample.DatabaseApi.DbCustomer.ApiIdDescriptor.Undefined;
        }

        /// <summary>
        /// Conversion from <see cref = "JsonSchemaSample.DatabaseApi.DbCustomer.ApiIdDescriptor"/>.
        /// </summary>
        /// <param name = "value">The value from which to convert.</param>
        public static implicit operator IdDescriptor(JsonSchemaSample.DatabaseApi.DbCustomer.ApiIdDescriptor value)
        {
            if (value.HasJsonElementBacking)
            {
                return new(value.AsJsonElement);
            }

            return value.ValueKind switch
            {
                JsonValueKind.Object => new(value.AsPropertyBacking()),
                _ => Undefined
            };
        }

        /// <summary>
        /// Conversion to <see cref = "JsonSchemaSample.DatabaseApi.DbCustomer.CrmIdDescriptor"/>.
        /// </summary>
        /// <param name = "value">The value from which to convert.</param>
        public static explicit operator JsonSchemaSample.DatabaseApi.DbCustomer.CrmIdDescriptor(IdDescriptor value)
        {
            if ((value.backing & Backing.JsonElement) != 0)
            {
                return new(value.AsJsonElement);
            }

            if ((value.backing & Backing.Object) != 0)
            {
                return new(value.objectBacking);
            }

            return JsonSchemaSample.DatabaseApi.DbCustomer.CrmIdDescriptor.Undefined;
        }

        /// <summary>
        /// Conversion from <see cref = "JsonSchemaSample.DatabaseApi.DbCustomer.CrmIdDescriptor"/>.
        /// </summary>
        /// <param name = "value">The value from which to convert.</param>
        public static implicit operator IdDescriptor(JsonSchemaSample.DatabaseApi.DbCustomer.CrmIdDescriptor value)
        {
            if (value.HasJsonElementBacking)
            {
                return new(value.AsJsonElement);
            }

            return value.ValueKind switch
            {
                JsonValueKind.Object => new(value.AsPropertyBacking()),
                _ => Undefined
            };
        }

        /// <summary>
        /// Conversion to <see cref = "JsonSchemaSample.DatabaseApi.DbCustomer.GenericIdDescriptor"/>.
        /// </summary>
        /// <param name = "value">The value from which to convert.</param>
        public static explicit operator JsonSchemaSample.DatabaseApi.DbCustomer.GenericIdDescriptor(IdDescriptor value)
        {
            if ((value.backing & Backing.JsonElement) != 0)
            {
                return new(value.AsJsonElement);
            }

            if ((value.backing & Backing.Object) != 0)
            {
                return new(value.objectBacking);
            }

            return JsonSchemaSample.DatabaseApi.DbCustomer.GenericIdDescriptor.Undefined;
        }

        /// <summary>
        /// Conversion from <see cref = "JsonSchemaSample.DatabaseApi.DbCustomer.GenericIdDescriptor"/>.
        /// </summary>
        /// <param name = "value">The value from which to convert.</param>
        public static implicit operator IdDescriptor(JsonSchemaSample.DatabaseApi.DbCustomer.GenericIdDescriptor value)
        {
            if (value.HasJsonElementBacking)
            {
                return new(value.AsJsonElement);
            }

            return value.ValueKind switch
            {
                JsonValueKind.Object => new(value.AsPropertyBacking()),
                _ => Undefined
            };
        }
    }
}